### ISSUE TITLE
Add format check for Definition

### ISSUE THREAD

**Issue by CLXi** [kubevela/kubevela#1038]
**Is your feature request related to a problem? Please describe.**

When I submitted a wrong Definition file to k8s, I found that vela does not verify the syntax of the file and whether the type parameters are correct.

**Describe the solution you'd like**

Vela needs to ensure that the basic syntax of the Definition submitted by the user is correct, and verify the type of input parameters.
Finally, when the client queries the Definition through the k8s api, vela should point out the location of the Definition error message.

**Comment by wonderflow** [comment]
Yes, this is in our plan, we need to add a webhook to check definition format

**Comment by wonderflow** [comment]
Now I think the webhook has already verified, @captainroy-hy @yangsoon  please check

**Comment by wonderflow** [comment]
Now it's already supported in v1.4, you can use `vela def` command to check, see https://kubevela.net/docs/platform-engineers/cue/definition-edit
