### ISSUE TITLE
[Feature] json logs support

### ISSUE THREAD

**Issue by hprotzek** [kubevela/kubevela#1056]
We are running kubela in GKE and using stackdriver. Currently the logs are are mix from plain strings and json objects. e.g.
```
"2021-02-16T08:05:08.146Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validating-core-oam-dev-v1alpha2-applicationconfigurations", "code": 200, "reason": "", "UID": "e143591a-0948-40ef-addf-0ee3dfc5c606", "allowed": true}"
```
In case of errors its very hard to find these in the log stream, as the actual log message didn't get parsed properly. Same goes for ELK without any special logstash filter logic.

If kubevela would use a logging library that support json formatted log output, e.g [logrus](https://github.com/sirupsen/logrus) this would help debug problems in a great way.

Also render the debug objects as json, so they are readable would be beneficial. 
```
2021-02-16T06:51:15.095Z	INFO	applicationconfiguration mutate webhook	Print the mutated obj	{"obj name": "snrollout-test", "mutated obj": "(v1alpha2.ApplicationConfigurationSpec) {\n Components: ([]v1alpha2.ApplicationConfigurationComponent) (len=1 cap=1) {\n  (v1alpha2.ApplicationConfigurationComponent) {\n   ComponentName: (string) (len=14) \"snrollout-test\",\n   RevisionName: (string) \"\",\n   DataOutputs: ([]v1alpha2.DataOutput) <nil>,\n   DataInputs: ([]v1alpha2.DataInput) <nil>,\n   ParameterValues: ([]v1alpha2.ComponentParameterValue) <nil>,\n   Traits: ([]v1alpha2.ComponentTrait) (len=3 cap=4) {\n    (v1alpha2.ComponentTrait) {\n     Trait: (runtime.RawExtension) &RawExtension{Raw:*[123 34 97 112 105 86 101 114 115 105 111 ...
```

**Comment by ryanzhang-oss** [comment]
I am exploring using the klog/v2 which will print out structured loggings.  We will move the entire project towards that if it proves to be useful after ingesting by ELK type of logging system.

I wonder if you can explain a bit what "json logs" really means?

**Comment by hprotzek** [comment]
Right now we have logs like this:
```
"2021-02-16T08:05:08.146Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validating-core-oam-dev-v1alpha2-applicationconfigurations", "code": 200, "reason": "", "UID": "e143591a-0948-40ef-addf-0ee3dfc5c606", "allowed": true}"
```

this log message as json log format would something look like this:
```
{ "time": "2021-02-16T08:05:08.146Z", "level": "DEBUG", "source": "controller-runtime.webhook.webhooks", "action": "wrote response", "webhook": "/validating-core-oam-dev-v1alpha2-applicationconfigurations", "code": 200, "reason": "", "UID": "e143591a-0948-40ef-addf-0ee3dfc5c606", "allowed": true}"
```

With this json log formated message stackdriver or also ELK can just parse the json message and create index fields of all json keys without additional config. We use logrus in other projects and there you can just switch the log formatter from text to json. So using text for local development, as it's easier to read and json when its running on the cluster, so the log system can parse it properly.

**Comment by ryanzhang-oss** [comment]
Hi, Holger,

Here are the steps we are thinking of doing

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

I wonder if that works for you guys?  Does stackdriver or ELK take only Json format?

**Comment by hprotzek** [comment]
Hi @ryanzhang-oss yes the proposed changes for structured logging would solve our problem, as then the json output is possible.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging#json-output-format

**Comment by wonderflow** [comment]
supported now, the whole project is using klog.
