### ISSUE TITLE
[Feature] pod failure message should report to Application object level

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#1365]
**Is your feature request related to a problem? Please describe.**

To help debug a failure of Application provisioned by a colleague, I didn't find any error message in the application chain application --> applicationrevision --> applicationcontext --> component --> cloneset (workload). All the way down to pod, we found the issue finally.

```
Events:
  Type     Reason          Age                    From                                 Message
  ----     ------          ----                   ----                                 -------
  Normal   Scheduled       <unknown>              default-scheduler                    Successfully assigned default/testapp-xd5qj to cn-huhehaote.xxx
  Normal   SandboxChanged  45m                    kubelet, cn-huhehaote.xxx  Pod sandbox changed, it will be killed and re-created.
  Normal   AllocIPSucceed  45m (x2 over 45m)      terway-daemon                        Alloc IP xxx/24 for Pod
  Warning  Failed          43m (x8 over 45m)      kubelet, cn-huhehaote.xxx  Error: secret "mysql-demo" not found
  Normal   Pulling         5m30s (x119 over 45m)  kubelet, cn-huhehaote.xxx  Pulling image "nginx:latest"
  Normal   Pulled          41s (x133 over 45m)    kubelet, cn-huhehaote.xxx  Successfully pulled image "nginx:latest"
```

It will cost so much time to debug a failure.

#### Note:
`Cloneset` itself didn't catch to error message from pod. I've discussed with OpenKruise guy and I was told the design keep aligning to Kubernetes controller, like `Deployment`

But KubeVela, as a platform engine, might need to catch and display error message form lower workload in upper Application level.

/cc @lowkeyrd 

**Describe the solution you'd like**

Or we don't break the `workload` level to directly retrieve the status of Pod, just report the status of `workload` to Application.

```
➜  /Users/zhouzhengxi/Downloads/xxx k get cloneset
NAME      DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
testapp   1         1         0               0       1       56m
```

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
I hope this feature could help? https://kubevela.io/docs/cue/status The platform builder could define healthPolicy and status for error message.

**Comment by wonderflow** [comment]
It's supported in velaux now.

**Comment by wonderflow** [comment]
We still need some way to use vela ql to read the pod event, this can be related with o11y.

**Comment by wonderflow** [comment]
supported with:

```
vela status --detail --tree
```
