### ISSUE TITLE
[Feature] Upgrade our CUE lib to v0.4.x

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#1400]
CUE is going to release v0.3.0 very soon https://github.com/cuelang/cue/releases/tag/v0.3.0-beta.8 

It contains much of great features that really needed in KubeVela, we should upgrade from 0.2.2 to 0.3.0 after it released.

**Comment by wonderflow** [comment]
pending on https://github.com/cuelang/cue/issues/867

**Comment by hprotzek** [comment]
Any idea if the the problem with cuelang can get fixed in a foreseeable future? This is blocking us quite a lot, as we can't use multiple comprehensions per list, which make the trait development and configuration unnecessary very complicated.

@wonderflow Or can you recommend a workaround for this problem with multiple comprehensions per list?

**Comment by wonderflow** [comment]
@hprotzek  CUE maintainers said they're fixing it.   

 @leejanee Do you have any suggestion for it?

**Comment by wonderflow** [comment]
Refer to https://github.com/cue-lang/cue/issues/867

**Comment by wonderflow** [comment]
still blocking on https://github.com/cue-lang/cue/issues/1414

**Comment by gedw99** [comment]
@wonderflow 
Its now fixed as of a few days ago and released.

worth giving it a try...

**Comment by jcooklin** [comment]
@wonderflow Do you think this issue will be resolved in milestone 1.5 and not pushed again?

**Comment by wonderflow** [comment]
@jcooklin I think we will! It's really sorry to be delayed. We have communicate with the CUE team recently and we're eager to upgrade it.

**Comment by wonderflow** [comment]
Sorry to say that we will delay the upgrade to v1.6 millstone as we need lots of compatible work and still trying to fix some of them as following:

- https://github.com/cue-lang/cue/issues/1826
- https://github.com/cue-lang/cue/issues/1815
- https://github.com/cue-lang/cue/issues/1816
- https://github.com/cue-lang/cue/issues/1813
- https://github.com/cue-lang/cue/issues/1806

Fortunately, the CUE community give us lots of help and we are confidence enough to make it in v1.6.

**Comment by wonderflow** [comment]
The main upgrade has been done by #4425 , while work still needed for the issues above. I'll keep this issue open.

**Comment by wonderflow** [comment]
Finally, we have finished the upgrade in the master branch! Thanks to the CUE community! 

#4851 
#4786
#4758
#4739
#4734

Thanks for your great effort! @FogDong @Somefive
