### ISSUE TITLE
[Feature] Add image build args to record semver of kubevela for latest image

### ISSUE THREAD

**Issue by captainroy-hy** [kubevela/kubevela#1783]
Currently, if use latest image of kubevela, we will get `github.com/kubevela/version.velaversion=latest`.
`latest` doesn't provide any helpful information except the user was using the latest version when he pulled the image.
Only when user specify a specific tag while deploying vela, we can a specific version of vela.
 
Consider adding a new field `VELASEMVER` to track the latest git tags while building vela image.

**Comment by wonderflow** [comment]
Already added now, closing
