### ISSUE TITLE
[Bug] Issues when not using vela-system namespace

### ISSUE THREAD

**Issue by o-otte** [kubevela/kubevela#1897]
**Describe the bug**
Upstream Chart can not be installed into custom namespace.

We are using a quite strict naming policy for the namespaces used in our clusters, e.g. `app-some-name` for application namespaces and `sys-some-name` for cluster services. This implies we can not use the preferred namespace name `vela-system` as described in the installation guide. 

With some manual tweaking of the helm charts templates we got KubeVela running on our dev cluster, but we want to use the upstream helm chart in the future.

We also encountered the problem, that the `vela` CLI tool is not capable of listing showing any traits, components, or apps when using a custom namespace.

**To Reproduce**
1. Install steps as described in the documentation (Advanced with use of cert-manager)
2. Using different namespace for the helm chart: `helm install --create-namespace -n sys-kubevela --set admissionWebhooks.certManager.enabled=true kubevela kubevela/vela-core` configured as a flux2 HelmRelease configuration
3. Observe that KubeVela will not start.
4. Run `helm template` and manually set missing `namespace` fields and overwrite hardcoded vela-system references, apply modified manifests.
5. Observe that everything can by applied, test application runs
6. `vela` CLI tool not functioning:
   ```console
   $ vela show ingress
   Error: could not find ingress in namespace default, or vela-system
   ```
   kubectl vela plugin works as a namespace can be specified as a parameter.

**Expected behavior**
Helm Chart can be installed with custom namespace, tools are working correctly with a given namespace as a parameter, e.g. `vela show -n namespace-name ingress`.

**Screenshots**
none

**KubeVela Version**
1.0.6

**Cluster information**
Kubernetes Version 1.19.9

**Additional context**
- Hardcoded vela-system namespace in:
  ```console
  $ rgrep -n -e vela-system ./charts/vela-core/*
  ./charts/vela-core/crds/core.oam.dev_applications.yaml:5:    cert-manager.io/inject-ca-from: vela-system/kubevela-vela-core-root-cert
  ./charts/vela-core/crds/core.oam.dev_applications.yaml:15:          namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:10:      namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:29:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:32:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:47:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:50:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:53:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:139:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:147:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:155:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:165:                  app.kubernetes.io/instance: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:352:                  app.kubernetes.io/instance: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:567:                  app.kubernetes.io/instance: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:758:                  app.kubernetes.io/instance: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:1273:                  app.kubernetes.io/instance: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:1871:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:2012:                namespace: vela-system
  ./charts/vela-core/templates/addons/fluxcd.yaml:2031:                namespace: vela-system
  ./charts/vela-core/templates/test/test-application.yaml:45:          kubectl -n vela-system wait --for=condition=Applied application helm-test-vela-app --timeout=3m
  ./charts/vela-core/templates/test/test-application.yaml:50:          kubectl -n vela-system wait --for=condition=available deploy helm-test-express-server --timeout 3m
  ./charts/vela-core/templates/test/test-application.yaml:54:          while ! [ `kubectl -n vela-system get ing helm-test-express-server | grep -v NAME | wc -l` = 1 ]; do
  ./charts/vela-core/templates/defwithtemplate/raw.yaml:8:  namespace: vela-system
  ./charts/vela-core/values.yaml:91:systemDefinitionNamespace: vela-system
  ```
- No namespace specified for Issuer and Certificate in `certmanager.yaml`

**Comment by wonderflow** [comment]
Thanks for reporting, I assume KubeVela should be able to deploy in any specified namespace. Maybe it's a bug and needs to be investigated

**Comment by chivalryq** [comment]
Let me provide more info: All files in ./charts/vela-core/templates/addons are ConfigMap for vela CLI. 

And now the namespace of configMap will change to helm chart style( {{.Values.systemDefinitionNamespace}} ). ref to #1915 

Some of the addon like fluxcd as you see. The plenty `vela-system` string are data in configMap, which doesn't have any effect for helm (and now it's was move to flux-system)

**Comment by wangyuan249** [comment]
@o-otte  Hi, I try to reproduce your problem and found you did't specify the systemDefinitionNamespace field.
Therefore, to run kubevela normally, you can install as bellow:

```shell
1.  Install official cert-manager
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.crds.yaml

2. Install chart in remote repository,
helm install --create-namespace -n sys-kubevela --set admissionWebhooks.certManager.enabled=true --set systemDefinitionNamespace=sys-kubevela  kubevela kubevela/vela-core

or Install chart in local repository,
helm install --create-namespace -n sys-kubevela --set admissionWebhooks.certManager.enabled=true --set systemDefinitionNamespace=sys-kubevela  kubevela ./charts/vela-core

you can also use  `--dry-run` args to see that the namespace "sys-kubevela" has be specified for Issuer and Certificate.

```

**Comment by wangyuan249** [comment]
And the vela show CLI currently only support show namespace in "vela-system" and "default"
We intend to fix it to support kubectl vela plugin works as a namespace can be specified as a parameter.
like "vela show -n namespace-name ingress".
Or would you like to contribute a PR to fix this so that other people in community will be able to solve this similar scene problems more smoothly.  @o-otte

**Comment by o-otte** [comment]
@wangyuan249 Hi and thank you for hint with the systemDefiinitionNamespace field! I wasn't aware of it. Nevertheless, I have a question regarding the hardcoded "vela-system" namespace inside the `./charts/vela-core/crds/core.oam.dev_applications.yaml` CRD on lines 5 and 15. For us it seems to produce errors if cert-manager related resources (Issuers, certificates) are deployed in another namespace. The problem did not show on the setup, but on the first use of the webhook. The problem could be solved by changing the namespace in the aforementioned CRD. I think it could be relevant to your PR #1922 

Regarding the PR for the CLI tool, I don't have much time, but I'm willing to help on that. Can you provide my with some info on how and where to start on that specific topic?

**Comment by wangyuan249** [comment]
@o-otte  thanks for your feedback.
When installing a helm chart, the first step is to install pre-resource such as crd or other Dependent sub-chart, the second step is our def template.  While in the first step, the crd could not perceive this variable `systemDefinitionNamespace`
![image](https://user-images.githubusercontent.com/35907099/126095247-197d4382-d26c-425b-9fff-d5cc8e99aebe.png)

Therefore, currently my solution on installing self-def namespace cert is to change the origin path `config/crd/pathes/...yaml`
![image](https://user-images.githubusercontent.com/35907099/126095820-ddd23000-12ad-416c-8b75-5c0f0f3194fb.png)
and use `make  manifests` to gen crd in chart
![image](https://user-images.githubusercontent.com/35907099/126095852-d5eed2dc-8857-4546-8842-f18a2548099d.png)

**Comment by wangyuan249** [comment]
![image](https://user-images.githubusercontent.com/35907099/126096336-da445d80-0b57-47f7-b645-31d6ca89a945.png)
And the specific logic for `vela show` in shown in figure.

**Comment by wonderflow** [comment]
I think this should be supported in v1.3.x. please have a try. Feel free to re-open this issue if there's still any probelm.
