### ISSUE TITLE
Kubevela Helm Chart Target isn't accepting connections from UK

### ISSUE THREAD

**Issue by rfkeith** [kubevela/kubevela#1903]
When trying to install KubeVela I am getting a connection closed error from: kubevelacharts.oss-cn-hangzhou.aliyuncs.com

λ helm --debug install --create-namespace -n vela-system kubevela kubevela/vela-core
install.go:173: [debug] Original chart version: ""
Error: Get "https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core/vela-core-1.0.7.tgz": EOF
helm.go:81: [debug] Get "https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core/vela-core-1.0.7.tgz": EOF

Helm repo update works fine

**Comment by wonderflow** [comment]
Please try this repo: 
```
helm repo add kubevela https://charts.kubevela.net/core
```

**Comment by rfkeith** [comment]
I did add that repository as described in the installation guide. Unfortunately the hosts that have the helm package (tgz) file are not responding and just dump the connection

λ helm repo list
NAME            URL
kubevela        https://charts.kubevela.net/core

λ helm --debug install --create-namespace -n vela-system kubevela kubevela/vela-core
install.go:173: [debug] Original chart version: ""
**Error: Get "https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core/vela-core-1.0.7.tgz"**: EOF
helm.go:81: [debug] Get "https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core/vela-core-1.0.7.tgz": EOF
