### ISSUE TITLE
Converging community docs

### ISSUE THREAD

**Issue by resouer** [kubevela/kubevela#1940]
**Describe the bug**

There are now multiple community documentations (https://github.com/oam-dev/kubevela/blob/master/community.md, https://github.com/oam-dev/spec/blob/master/governance.md) across projects, please consider converging them into a centralized `community` repo.

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
It's done in https://github.com/kubevela/community . Thanks @BinaryHB0916
