### ISSUE TITLE
[Feature] Support to place an application to the cluster in private network 

### ISSUE THREAD

**Issue by luotian-github** [kubevela/kubevela#1941]
How to deploy an application to a cluster in private network by Kubevela? Will Kubevela implement any proxy/agent feature to support the private network cluster?

**Comment by wonderflow** [comment]
Can you explain more about the architecture? I'd like to know your use case.

**Comment by wonderflow** [comment]
I think you can try OCM for this: https://github.com/kubevela/samples/tree/master/12.Open_Cluster_Management_Demo

OCM use a PULL model for resource deployment, only control plane(hub) cluster is needed for public access.
