### ISSUE TITLE
[Feature] Add Capability Catalog Concept

### ISSUE THREAD

**Issue by chivalryq** [kubevela/kubevela#1960]
Currently, our capability system is chaotic. We should build an open and easy-to-use catalog system for KubeVela users.

We have three place to hold capabilities/definitions/addons, they are for different tools and contains different contents.

1. [catalog repo](https://github.com/oam-dev/catalog):This is a place for out vela CLI (use `vela cap` to sync and install) (note this "catalog" isn't the same with "catalog" in title.) 
2. [OSS bucket](registry.kubevela.net/?list-type=2). This is a place for our kubectl vela plugin(use `kubectl vela comp` and `kubectl vela trait` to get and install)
3. ConfigMap in vela-core helm chart. This is for vela CLI to list and enable addon.

## Proposal
We should build a catalog website like [artifacthub](https://artifacthub.io/). This is **only** a website for search KubeVela artifact, tools are still vela CLI and kubectl.
It allow peaple store repo url and artifact infomation, but not provide actual file. It act like a distribution center show all available KubeVela addon/definition group.

Here, **definitions** means compoentDefinition and traitDefinition.

### How catalog store infomation
It only store below metadata for an artifact. 
1. repo URL(This is where artifact is actually stored)
2. artifact name
3. artifact type

### How repo store artifact
As long as it could serve http request and provide static files.

### artifact type
There are two types. 
1. Addon: based on Initializer. It could depends on other initializer. Addon could contains definitions or not. 
An example is [fluxcd addon](https://github.com/oam-dev/kubevela/blob/master/charts/vela-core/templates/addons/fluxcd.yaml). It provide an environment of fluxc to use its CI/CD capability. Along with addon there are  two definition: `kustomization` and `helm`. They can be used in user's application

2. Definition group: It contains a group of definition. It may depends on some intializers or not.
For example, a user is not satisfied with definitions in `fluxcd` addon, so he write an self-made edition(like exposing more field in `helm` definition). Upload to a repo and regiser it on our catalog for more people to use.
why definition group? because (advanced) user may want to customize their definitions and don't need to write intializer again.

### how to refactor tools
We should at least unified [catalog repo](https://github.com/oam-dev/catalog) and [OSS bucket](registry.kubevela.net/?list-type=2) and use one place to hold all definitions. Put this new repo on catalog as first artifact(Definition group type)
And our built-in addon can be put in this catalog too, just don't have to download.(They are already in configMap)

**Comment by chivalryq** [comment]
> Such as give all capability a unified label for better list and management. eg. In addon resource you already give them a unified label "addons.oam.dev/type: XXX" , but in other capability do not have.
That's because nowadays we don't have "other capability" implemented. We only have addon stored in configMap and definition group doesn't even exist. There are only **definitions**. And definitions' GVK natually identify its type so no need for label. But a unified way is needed in catalog.

**Comment by hongchaodeng** [comment]
**Updated the title a bit**. This should go beyond the UI and provide catalog concepts in the Vela core.

> We have three place to hold capabilities/definitions/addons...

I think it has two sides:
- For us, we should unify the way to manage catalogs and caps to provide discovery and installation services.
- For the community, it is perfectly normal that there are multiple ways to provide catalogs (e.g. git repo, OSS bucket, ConfigMap) and plugin to the Vela platform.

This is why we are adding the Catalog concept to enable multiple teams to contribute and extend capability stores.

> artifact type
> There are two types....

I don't think we should go this way. We shouldn't reinvent any new format to manage artifacts of capabilities. Instead, we should reuse what's on the table -- that is the Initializer + Component + Helm/Kustomize/Terraform.

This is also why we adding the Capability concept to adopt existing mechanisms.

**Comment by wonderflow** [comment]
closing as we have addon now: https://github.com/kubevela/catalog
