### ISSUE TITLE
[Feature] Support Standalone Deployment Mode

### ISSUE THREAD

**Issue by hongchaodeng** [kubevela/kubevela#2028]
Currently KubeVela relies on k8s for deployment. We should support standalone deployment mode which is to run inside a single Docker container or a VM. Similar to [Dapr Self-hosted Mode](https://docs.dapr.io/operations/hosting/self-hosted/). 

For a bit more technical details, we could package KubeVela with [kcp](https://github.com/kcp-dev/kcp), and be able to deploy KubeVela anywhere as a control plane.

**Comment by wonderflow** [comment]
Supported now https://kubevela.net/docs/installation/standalone, it relies on k3s.
