### ISSUE TITLE
multiple comprehensions per list not yet supported

### ISSUE THREAD

**Issue by vijay-dcrust** [kubevela/kubevela#2047]
Hi,
  I am getting this error in kubevela logs: "multiple comprehensions per list not yet supported"

I am trying below cue template in my pod definition. This template is working fine with standard cue CLI.

                  "env": [
                    for p,q in parameter
                      if (p != "cloud_resources" )
                      {
                        name: p
                        value: q
                      },
                    for _,cs in parameter.cloud_resources
                      for k, v in cs {
                          _x: ["SPECIAL_VAR" , "\(k)"]
                          name:  strings.Join(_x, "_")
                          value: v
                     },

It looks like multiple loop over a list are not supported by kubevela.
Is there any plan to support this. And is there any workaround for such use cases.

My parameter definition is as below:-

        parameter: {
          service_name            :  string  
          environment             :  string
          account                 :  string
          cloud_resources         : [...{[string]: string},]  
        }

**Comment by Somefive** [comment]
KubeVela currently uses cue v0.2.2 which does not support multiple comprehension per list yet. (It is also true if you install cue v0.2.2 and will find the same problem). For recent cue version (like v0.4.0), it is supported. Therefore, this feature will be supported when KubeVela upgrade its cue dependency to higher level.
While there are some historical compatibility problems for the upgrade, KubeVela team indeed have the plan to use higher level of cue and are also collaborating with cuelang team closely to solve some cue language issues. Currently, we do not have a determined date or version release for the cue upgrade yet but it will be done in the future absolutely. Sorry that you might need to work around for some more time.

**Comment by wonderflow** [comment]
Supported in v1.6.0+
