### ISSUE TITLE
[BUG]The GC is always prompted to upgrade the latest version

### ISSUE THREAD

**Issue by jingliming** [kubevela/kubevela#2051]
**Describe the bug**
The GC is always prompted to upgrade the latest version

**To Reproduce**
1. The version I used
v1.1.0-alpha.5
2. The version I want to upgrade .
v1.1.0-beta.3
3. See error

**Expected behavior**
no error logs

**Screenshots**
![image](https://user-images.githubusercontent.com/9865050/128670267-42a796eb-6861-4e19-8173-81d21ca4a2a2.png)

**KubeVela Version**
v1.1.0-beta.3

**Cluster information**
v1.16.14

**Additional context**

**Comment by wonderflow** [comment]
fixed
