### ISSUE TITLE
[Feature] Build Gitops continuous deployment tools on kubevela

### ISSUE THREAD

**Issue by leejanee** [kubevela/kubevela#2062]
GitOps using Git repositories as the source of truth for defining the desired application state. It is very popular and  user friendly. We will build Gitops continuous deployment tools on kubevela.

**Comment by leejanee** [comment]
@ritwizsinha You can learn about `kubevela` on the website [kuebvela.io](https://kubevela.io/)

**Comment by rahul799** [comment]
Hey @leejanee ,
I have significant experience with GitOps as well as CI/CD.
I will like to apply for the project as part of the LFX Mentorship.

**Comment by MarcaWitt** [comment]
@leejanee I would like apply for this project under the LFX. I have read the previous comments and the requirements you mentioned. Looking forward to it.

**Comment by kaustubhsharma-009** [comment]
Hey, @leejanee I have significant experience in GitOps, DevOps, Cloud Computing, automation, and the core concepts regarding the same. I had gone through the issue of integration with developing time, but when I came across this issue, I felt that my expertise and experiences align with this one. I have applied in LFX for the same. Can you guide me a bit more regarding my contribution to this organization?

PS: I have already done background work before applying by reading the documentation for KubeVela and how does it enhance automation

**Comment by wonderflow** [comment]
We're using fluxcd for this now https://kubevela.net/docs/next/case-studies/gitops
