### ISSUE TITLE
[Feature] vela apiserver should support dry-run and live-diff 

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#2082]
Platform builders who're using KubeVela to build PaaS want to use vela cli in their dashboard, such as dry run and live diff commands. We should support it in apiserver so users can invoke the APIserver instead of using client.

> 有些功能，比如vela system，我想做到服务端去，这样可以让前端也能够通过rest接口来查看dry run结果。

**Comment by barnettZQG** [comment]
Released by #3136
