### ISSUE TITLE
Workflow example: config data passing

### ISSUE THREAD

**Issue by resouer** [kubevela/kubevela#2090]
Ref: https://github.com/oam-dev/kubevela/blob/51669f0e41476f81b7630e817b426055df8f846e/vela-templates/definitions/usage-examples/application-with-configmap.yaml#L18

A workflow example is needed: one component generate data to a config source (ConfigMap or Secret) and another component read data from it.

**Comment by hongchaodeng** [comment]
Shouldn't the ConfigMap be a hidden implementation detail and users just get the data in another component via Workflow Context?

**Comment by resouer** [comment]
@hongchaodeng need real samples. Note that user would choose Secret for sensitive data or even cloud storage to store data, we need to find a way to enable more cases (at least both Secret and ConfigMap) in these samples.

**Comment by wonderflow** [comment]
Refer to https://kubevela.net/docs/next/end-user/workflow/inputs-outputs
