### ISSUE TITLE
Deprecate  `skipAffectRevision` of traitDefition

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#2123]
The `skipAffectRevision` feature can support scaling up/down rollout trait  doesn't generate a new applicationRevision. But this feature cannot be supported in workflow.  Because application don't know how to rerun a completed workflow task. So I propose to deprecate this feature.  Rollout controller should defer `pass rollout's owner to workload` to `handleSucceed` phase, because modifying `batchPartition`  would generate a  appRev and new resourceTracker that will due to rollout's owner is different with workload's owner after whole rollout process complete, this change has been contained by #2121.

**Comment by wonderflow** [comment]
deprecated
