### ISSUE TITLE
Addon install failed due to git pull failure

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#2221]
**Describe the bug**

Latest KubeVela install Kruise and other addons by default. However installing these addons might fail due to various potential problems, for example, unable to pull from github due to network.

The install failure of addons will cause initializer controller and potentially other controllers (like componentdefinition_controller for cloneset-service) report errors frequently. It is still unclear what problems might be caused by them. Some user reports it will make the **controller memory usage constantly increasing**, which should be carefully looked into.

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

1.1.0

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
Does this issue still exist? We should move these charts to OSS.

**Comment by barnettZQG** [comment]
I will close this issue.
