### ISSUE TITLE
[Chore] deprecate manual scaler trait and remove the related code from vela-core

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#2262]
we can use patch trait for the job which only needs to define CUE not using controller.

Things that possible to be removed/refactored:

*  manualscaler CRD
* manualscaler controller
* related test code/configurations

**Comment by arcosx** [comment]
@wonderflow  I am interested in this issue
/assign

**Comment by wonderflow** [comment]
@arcosx Hi, this is a kindly ping. Would you still like to work on this issue.

**Comment by arcosx** [comment]
I'm still working on this issue and have made some progress recently, so I'll submit it this weekend.
