### ISSUE TITLE
[Feature] The stdlib needs to consider compatibility with the old libs

### ISSUE THREAD

**Issue by leejanee** [kubevela/kubevela#2303]
**Is your feature request related to a problem? Please describe.**

The `stdlib` upgrade will make break change.  We need to Support for old `operation` through version management
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FogDong** [comment]
Supported by kubevela/workflow#50.

Designed in kubevela/workflow#46.
