### ISSUE TITLE
Prompt not friendly when executing `vela addon enable fluxcd`

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#2344]
**Describe the bug**

```
➜  obervability git:(remote-hcl) vela addon enable fluxcd
I0924 11:13:29.098912   55563 apply.go:93] "creating object" name="fluxcd" resource="core.oam.dev/v1beta1, Kind=Initializer"
Error: Error occurs when enableing addon: fluxcd
: cannot create object: Internal error occurred: failed calling webhook "validating.core.oam-dev.v1beta1.initializers": Post "https://vela-core-webhook.vela-system.svc:443/validating-core-oam-dev-v1beta1-initializers?timeout=10s": dial tcp 10.96.211.127:443: connect: connection refused
```

**To Reproduce**

1. `Kind create clusters` (1.21)
2. Install kubevela
3. When the pods are ready, enable `fluxcd`

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by dotSlashLu** [comment]
Why is this closed? I have met the same problem enabling velaux:

```bash
 % vela addon enable velaux
Error: Internal error occurred: failed calling webhook "mutating.core.oam.dev.v1beta1.applications": failed to call webhook: Post "https://vela-core-webhook.vela-system.svc:443/mutating-core-oam-dev-v1beta1-applications?timeout=10s": context deadline exceeded
```

What should I do?

**Comment by dotSlashLu** [comment]
> Why is this closed? I have met the same problem enabling velaux:
> 
> ```shell
>  % vela addon enable velaux
> Error: Internal error occurred: failed calling webhook "mutating.core.oam.dev.v1beta1.applications": failed to call webhook: Post "https://vela-core-webhook.vela-system.svc:443/mutating-core-oam-dev-v1beta1-applications?timeout=10s": context deadline exceeded
> ```
> 
> What should I do?

In my case the cause is my CNI plugin in my testing kubernetes is unhealthy.
