### ISSUE TITLE
[Feature] Add addon for GCP and AWS Terraform provider

### ISSUE THREAD

**Issue by emanuelr93** [kubevela/kubevela#2457]
Currently, addons have been created within the addons for the following terraform-providers:
- Azure
- Alibaba

This feature will be used to add addons for GCP and AWS terraform providers which are already supported in the terraform-controller

**Comment by paterson-deshommes** [comment]
It would be cool to update the KubeVela documentation because I don't think I saw anywhere that it had the Azure addon.
