### ISSUE TITLE
[Feature]Air Gapped Kubevela Install

### ISSUE THREAD

**Issue by wanshicheng** [kubevela/kubevela#2584]
**Is your feature request related to a problem? Please describe.**
I want to intall Kubevela in air-gapped enviroment.

**Describe the solution you'd like**
A script that can download all images and other resources needed.
A script that can upload all resources to private repo.
A script that can install Kubevela and addon with private repo.

**Describe alternatives you've considered**
All-in-one install package.

**Additional context**

**Comment by wonderflow** [comment]
seems lots of users required this feature, working on process

**Comment by wonderflow** [comment]
please refer to https://kubevela.io/blog/2022/04/01/offline-deployment-practice for more details, it's Implemented now
