### ISSUE TITLE
[Feature] support fetch sub-cluster workload status from hub-cluster 

### ISSUE THREAD

**Issue by basuotian** [kubevela/kubevela#2682]
**Is your feature request related to a problem? Please describe.**

Currently in multi-cluster delivery, it seems no way to ensure sub-cluster workload status in hub-cluster, we have to call sub-cluster apiserver to get the workload status,  but we don't want to expose sub-cluster to upper platform

**Describe the solution you'd like**
support fetch sub-cluster workload status from hub-cluster, perhaps by: 
- maintain the sub-cluster workload metadata in hub-cluster
- proxy the request to sub-cluster

**Comment by Somefive** [comment]
Currently we are implementing `vela status` to view resources in applications including multi-cluster resources. Also, a list of commands such as `vela exec` and `vela logs` are support remote debugging as well. The incoming v1.2 will give a solution to the raised problems. Thanks for the reporting.

**Comment by wonderflow** [comment]
It's supported now, you can view it from:

* vela status
* velaux with dashboard

Please give it a try in v1.3
