### ISSUE TITLE
helm type component could not be deployed on remote clusters

### ISSUE THREAD

**Issue by yeicandoit** [kubevela/kubevela#2711]
**Describe the bug**
Install kubevela on one k8s clusterA, join another k8s cluster (named k3s).
Write one app with workflow to deploy app to cluster k3s. This app's component type is helm.
Find that this app could not be deployed on cluster k3s and meet the following err:

message: 'step app: step apply: step 0: run step(provider=oam,do=component-apply):
        CollectHealthStatus: app=app-delivering-chart, comp=redis-comp, evaluate workload
        status message error: get template context: failed to get obj redis-comp with
        gvk source.toolkit.fluxcd.io/v1beta1, Kind=HelmRepository : helmrepositories.source.toolkit.fluxcd.io
        "redis-comp" not found'

**To Reproduce**

1.On cluster A, apply the YAML files of Application/Component/Policy/Workflow:
![图片](https://user-images.githubusercontent.com/22470950/141724412-463ccf67-4398-4dfa-b62f-fa1545ee1e3f.png)

raw yaml is:
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-delivering-chart
spec:
  components:
    - name: redis-comp
      type: helm
      properties:
        chart: redis-cluster
        version: 6.2.7
        url: https://charts.bitnami.com/bitnami
        repoType: helm

  policies:
    - name: example-multi-env-policy
      type: env-binding
      properties:
        envs:
          - name: staging
            placement: 
              clusterSelector:
                name: k3s
  workflow:
    steps:
      - name: deploy-staging
        type: deploy2env
        properties:
          policy: example-multi-env-policy
          env: staging

2. kubectl -n vela-demo apply -f "the above app file"

3. See error
message: 'step app: step apply: step 0: run step(provider=oam,do=component-apply):
        CollectHealthStatus: app=app-delivering-chart, comp=redis-comp, evaluate workload
        status message error: get template context: failed to get obj redis-comp with
        gvk source.toolkit.fluxcd.io/v1beta1, Kind=HelmRepository : helmrepositories.source.toolkit.fluxcd.io
        "redis-comp" not found'

**Expected behavior**
app-delivering-chart should be deployed successfully on cluster k3s

**Screenshots**

**KubeVela Version**
Version: refs/tags/v1.1.7
GitRevision: git-d083039
GolangVersion: go1.16.9

**Cluster information**
k3s Kubernetes Version: k3s version v1.21.2+k3s1(5a67e8dc)
clusterA Kubernetes Version: k3s version v1.20.6+k3s1(8d043282)

**Additional context**

**Comment by zxbyoyoyo** [comment]
you need to install fluxcd in the sub-cluster

**Comment by yeicandoit** [comment]
@zxbyoyoyo Thanks, I will try it

**Comment by yeicandoit** [comment]
@zxbyoyoyo 
In sub-cluster,  Could I install kubevela and enable fluxcd by command "vela addon enable fluxcd" ? 
I used this method, still met this error:
message: 'step app: step apply: step 0: run step(provider=oam,do=component-apply):
CollectHealthStatus: app=app-delivering-chart, comp=redis-comp, evaluate workload
status message error: get template context: failed to get obj redis-comp with
gvk source.toolkit.fluxcd.io/v1beta1, Kind=HelmRepository : helmrepositories.source.toolkit.fluxcd.io
"redis-comp" not found'

Should I install fluxcd by a helm chart in sub-cluster? 
https://github.com/fluxcd/charts

**Comment by chivalryq** [comment]
It's a planed feature that enable addon in sub-cluster. Please track this issue #2562 

Thanks for your concern @yeicandoit @zxbyoyoyo

**Comment by yeicandoit** [comment]
@chivalryq Does it mean that  when issue #2562 is resolved, we will be able to deploy an helm application on sub-cluster？  But now we could not do it

**Comment by yeicandoit** [comment]
I will try to deploy helm app in sub-cluster when kubevela v1.2.0 is released.

**Comment by wonderflow** [comment]
@wangyikewxgm  is fixing on it, we'll close this issue until it fixed. Thanks

**Comment by wangyikewxgm** [comment]
> > > @chivalryq Does it mean that when issue #2562 is resolved, we will be able to deploy an helm application on sub-cluster？ But now we could not do it
> > 
> > 
> > You can fix this error by install fluxcd in your sub-cluster manually by helm. When #2562 is fixed this operation can be replace by `vela addon enable fluxcd --cluster worker`
> 
> I did not find fluxcd helm, but I installed fluxcd in sub-cluster by this method: install kubevela firstly, used command "vela addon enable fluxcd" to install fluxcd. But I still met the above error when I deployed app to cluster k3s:
> 
> message: 'step app: step apply: step 0: run step(provider=oam,do=component-apply): CollectHealthStatus: app=app-delivering-chart, comp=redis-comp, evaluate workload status message error: get template context: failed to get obj redis-comp with gvk source.toolkit.fluxcd.io/v1beta1, Kind=HelmRepository : helmrepositories.source.toolkit.fluxcd.io "redis-comp" not found'

Dose the hub-cluster installed fluxcd addon

**Comment by yeicandoit** [comment]
>  the hub-cluster installed fluxcd

Yes

**Comment by yeicandoit** [comment]
is this issue fixed @wangyikewxgm?

**Comment by chivalryq** [comment]
We have support addon to installed to specified cluster, see https://kubevela.io/docs/platform-engineers/addon/addon-cue#features. So helm type component can be deploy on remote clusters.
Closing
