### ISSUE TITLE
[Feature] synchronize the application in cluster to db

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#2784]
## Feature description
KubeVela introduces the API server + DB module to help users versioning management application configuration and distribution.
The API module assembles the Application CR during the publishing process and publishes them to the cluster. The application configuration will be based on the data stored in the DB.

Two scenarios are produced here:

1.  How to connect existing applications in the cluster to the API server for management on the UI?
2. How to notify the developer in the UI if the user changes the application configuration in the cluster.

First of all, we need to keep the model consistent in both DB and CR forms, Of course, DB objects may iterate faster in practice, but they need to support interconversion with CR objects. If users are using KubeVela UI, the DB configuration should be their baseline configuration. Configuration changes discovered from the cluster should be part of a differentiated configuration for different environments.

**Comment by wonderflow** [comment]
implemented in 1.5
