### ISSUE TITLE
Create all-in-one image

### ISSUE THREAD

**Issue by hongchaodeng** [kubevela/kubevela#2802]
Put Controllers, APIServer, Frontend into one image to simplify packaging and deployment.

**Comment by barnettZQG** [comment]
It should also include k8s or k3s.

**Comment by chivalryq** [comment]
I'm working on this. Have set this as Graduation Project.

**Comment by wonderflow** [comment]
this has come true https://github.com/kubevela/velad

Thanks @chivalryq @hongchaodeng
