### ISSUE TITLE
Helm 用户迁移至 Kubevela 的场景需求

### ISSUE THREAD

**Issue by bigdimple** [kubevela/kubevela#2823]
#### CI部分

所有项目本身自带Dockerfile文件以及启动脚本，均使用gitlab-ci.yml来自动构建镜像。

#### CD部分

使用jenkins的pipeline文件作为通用的发布策略。

pipeline项目结构

k8s.groovy                                      --jenkinsfile，作为主要pipeline发布流程控制文件

helm/Chart.yaml                             --Heml仓库cahrt文件
-----/values.yaml                            --Heml仓库默认values文件，一般不使用
-----/templates/deploy.yaml         --默认模板deployment类型资源文件，所有生成语法都在这里面完成。
---------------/svc.yaml              --默认模板service类型资源文件，所有生成语法都在这里面完成。
---------------/ingress.yaml        --默认模板ingress类型资源文件，所有生成语法都在这里面完成。
---------------/pv.yaml                 --默认模板pv,pvc类型资源文件，所有生成语法都在这里面完成。

apps/app1/staging.yaml                 --app1应用在测试环境的values文件
----------/prod.yaml                      --app2应用在生产环境的values文件
----------/gray.yaml                      --app2应用在灰度环境的values文件
----/app2/staging.yaml                --往下以此类推
----------/prod.yaml
----------/gray.yaml
----------/staging-1.yaml                --app1应用在staging-1环境的values文件。

关于staging-1.yaml这里说明一下，有个继承关系，默认所有staging用同一个staging.yaml，但是会有单环境，单应用的需求，所以如果配置这一个，则该环境默认读取staging-1.yaml，优先级大于staging.yaml

目前想使用kubebela接管目前使用的helm一整套发布流程，所以开此Issue，作为记录，逐步展示迁移过程。

**Comment by wonderflow** [comment]
另一个类似的需求：


背景如下：
我们有一些helm charts的组件，存放于我们的harbor仓库中。这些组件可能是一个redis\mysql\apisix等等

目前我们针对不同环境的组件是以目录来区分的
例如可能是 如下的目录结构
    redis:
        test:
           values.yaml
        dev:
           values.yaml
        prod:
           values.yaml

这些配置都存在于gitlab中。
我们希望构建一个gitops的流程，组件的变更经过团队内部review后commit就可以自动发布到特定环境。

基于以上背景，基于kubevela的话，貌似会是如下的一个流程

目前kubevela是支持用helm charts作为一个Application的，因此我们的组件目录可能会变成
    redis:
        test:
           app.yaml
        dev:
           app.yaml
        prod:
           app.yaml

app.yaml 内容就是application，并且使用helm类型的components，

以上这个可能是一个专门中间件的配置仓库。

然后为了带出gitops流程，貌似还需要多一个仓库用于存放驱动gitops的配置

目录可能如下:
    redis:
       gitops.yaml

gitops.yaml中的内容可能就是application,并且使用kustomize类型的components，监听上面某一个仓库的某一个目录的变更

不知道我的理解对不对

**Comment by barnettZQG** [comment]
@bigdimple 你们的场景中，同一个应用在不同环境部署是否有先后关系，然后差异性一般有多大？
