### ISSUE TITLE
Fluxcd addon does not work in a k8s cluster whose cluster local domain is specified with the different different from "cluster.local"

### ISSUE THREAD

**Issue by luckyfengyong** [kubevela/kubevela#2882]
**Describe the bug**
In a cluster whose cluster local domain is specified with the different different from "cluster.local", fluxcd failed to work with following error. The url of source controller is hardcoded as `source-controller.flux-system.svc.cluster.local.` in https://github.com/oam-dev/kubevela/blob/master/vela-templates/addons/fluxcd/resource/deployment/source-controller.yaml#L32

```
{"level":"error","ts":"2021-12-06T05:54:56.973Z","logger":"controller.kustomization","msg":"Reconciliation failed after 3m35.368999313s, next try in 1m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"app-gitops","namespace":"default","revision":"release/aa5ee9615ff55f6d41bc38da384bc4885bd5a426","error":"failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/default/app-gitops/aa5ee9615ff55f6d41bc38da384bc4885bd5a426.tar.gz giving up after 10 attempt(s): Get \"http://source-controller.flux-system.svc.cluster.local./gitrepository/default/app-gitops/aa5ee9615ff55f6d41bc38da384bc4885bd5a426.tar.gz\": dial tcp: lookup source-controller.flux-system.svc.cluster.local. on 10.96.0.10:53: no such host"}
```

**To Reproduce**
Follow the instruction of gitops demo in a k8s cluster with cluster local domain specified with a different name

**KubeVela Version**
built from master branch

**Comment by wonderflow** [comment]
Thanks, supported now in fluxcd addon https://github.com/kubevela/catalog/blob/master/addons/fluxcd/resources/deployment/source-controller.yaml#L31
