### ISSUE TITLE
[Feature] achieve a simpler installation experience

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#2906]
Resources such as binaries, images, chart packages, etc. downloaded by our current installation process are greatly hindered due to well-known reasons. We need to help users solve obstacles. There are things we can do as follows:

- [x] Discover and install vela CLI from the OSS, which is accelerating globally.
- [x] The vela CLI support install and upgrade the vela core and does not rely on the helm binary.
 >  Currently relying on helm installation, but the subsequent use process no longer needs the helm.

**Comment by wonderflow** [comment]
supported from v1.3
