### ISSUE TITLE
trait rollout not work with muilt cluster deploy

### ISSUE THREAD

**Issue by fxl0206** [kubevela/kubevela#2913]
#can't work in prod-cls cluster
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: book-info
  namespace: demo
spec:
  components:
    - name: reviews
      type: webservice
      properties:
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        port: 9080
        volumes:
          - name: wlp-output
            type: emptyDir
            mountPath: /opt/ibm/wlp/output
          - name: tmp
            type: emptyDir
            mountPath: /tmp
      traits:
        - type: canary-traffic
          properties:
            port:
              - 9080
        - type: labels
          properties:
            sidecar.istio.io/inject: "true"
        - type: rollout
          properties:
            targetSize: 2
            # This means to rollout two more replicas in two batches.
            rolloutBatches:
              - replicas: 2

    - name: productpage
      type: webservice
      properties:
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        port: 9080
      traits:
        - type: expose
          properties:
            port:
              - 9080
        - type: labels
          properties:
            sidecar.istio.io/inject: "true"
        - type: istio-gateway
          properties:
            hosts:
              - "*"
            gateway: ingressgateway
            match:
              - exact: /productpage
              - prefix: /static
              - exact: /login
              - prefix: /api/v1/products
            port: 9080

    - name: ratings
      type: webservice
      properties:
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
        port: 9080

      traits:
        - type: expose
          properties:
            port:
              - 9080
        - type: labels
          properties:
            sidecar.istio.io/inject: "true"

    - name: details
      type: webservice
      properties:
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        port: 9080

      traits:
        - type: expose
          properties:
            port:
              - 9080
        - type: labels
          properties:
            sidecar.istio.io/inject: "true"
  policies:
    - name: multi-env-policy
      type: env-binding
      properties:
        envs:
          - name: prod
            placement: # 选择要部署的集群
              clusterSelector:
                name: prod-cls
  workflow:
    steps:
      - name: deploy-prod
        type: deploy2env
        properties:
          policy: multi-env-policy
          env: prod

**Comment by wangyikewxgm** [comment]
this istio rollout demo has been fixed by https://github.com/kubevela/kubevela/pull/3839, Closing  and feel free if some find out thei issue still exist.
