### ISSUE TITLE
Support rollout trait for Helm component

### ISSUE THREAD

**Issue by dongwenjuan** [kubevela/kubevela#2918]
**Is your feature request related to a problem? Please describe.**
As our applications are all helm chart, we need to do rollout for app, but the rollout trait can't used for helm component currently.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dongwenjuan** [comment]
@wonderflow @wangyikewxgm

**Comment by wonderflow** [comment]
hi, it's already supported now https://kubevela.net/docs/tutorials/helm-rollout

Sorry for the late response, it's supported in 1.5 which is relased half a year ago.
