### ISSUE TITLE
[Feature] Conditional addon installation

### ISSUE THREAD

**Issue by yue9944882** [kubevela/kubevela#3001]
generally i hope to have an addon to install some components optionally by setting properties/parameters e.g. `foo.enabled`. or take our `ocm-cluster-manager` addon as an example, the default setup of the addon will not make any effective changes to the vela control plane --- it just installs the ocm control plane as a shortcut. by setting the properties users will be able to opt-in to cluster-gateway-addon-manager that helps vela admin to sustainably automate the cluster-gateway via OCM, which will restart the cluster-gateway instances for a few seconds so ideally we should also clearly document the usage/warnings about these parameters. furthermore, am expecting the following properties for `ocm-cluster-manager`:

- `installClusterGatewayAddonManager`: Installing an addon manager that adopts/automates the cluster-gateway for kubevela.
- `enableAutoClusterDiscovery`: If true, the managed clusters in OCM will be dynamically sync'd to cluster-gateway. 
- `enableKonnectivtyTunnel`: If true, the cluster-gateway will be upgraded to support transmitting requests over the konnectivity proxy that breaches the firewall/VPC.

currently the `parameter.cue` supports templating the content within a resource however it can't control whether a resource should be completely omitted or not. so am looking for the solutions to render such optional components for vela addons.

**Comment by wonderflow** [comment]
suported in v1.5 refer to the doc https://github.com/kubevela/kubevela.io/pull/907
