### ISSUE TITLE
[Feature] Disable addon need check if the addon have been used by other applications.

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#3097]
**Is your feature request related to a problem? Please describe.**

Currently we disable an installed addon doesn't do any check, but this is dangerous that will cause many problems. We should do some check such as check `x-defs` have been used by other apps.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
does this issue resolved? ping @wangyikewxgm

**Comment by wangyikewxgm** [comment]
> does this issue resolved? ping @wangyikewxgm

Have been fixed by #3457. Closing.
