### ISSUE TITLE
[Bug]  Helm Chart 方式交付部署某些chart失败

### ISSUE THREAD

**Issue by caiwenhao** [kubevela/kubevela#3127]
```
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm install my-release grafana/grafana
```

Normal  error  18s  helm-controller  reconciliation failed: Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "grafana" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "default": current value is "grafana"
  Normal  error  3s   helm-controller  reconciliation failed: install retries exhausted

**Comment by wonderflow** [comment]
What's  this issue related with kubevela?

**Comment by wonderflow** [comment]
maybe this is a issue of this helm chart. closing
