### ISSUE TITLE
[Feature] return http response status in pkg/builtin/http/http.go HTTPCmd.Run

### ISSUE THREAD

**Issue by ranger-huang** [kubevela/kubevela#3157]
**Describe the solution you'd like**

希望利用 pkg/stdlib/op.cue中 的 #HTTPGet #HTTPPost 等http操作符，实现 业务服务的健康检查 的workflowStep Definition.

发现在 [./pkg/builtin/http/http.go#L130](https://github.com/oam-dev/kubevela/blob/2da60419fcf84b62149c61018cb91ba469520a63/pkg/builtin/http/http.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L130) 的实现中，返回的 response 数据中缺少状态/状态码，对于健康检查的判断，在cue模版中不是很方便。 

建议在返回值添加 status / status_code 的信息。

```golang
// Run exec the actual http logic, and res represent the result of http task
func (c *HTTPCmd) Run(meta *registry.Meta) (res interface{}, err error) {
...
	// parse response body and headers
	return map[string]interface{}{   // #L130
		"body":        string(b),
		"header":      resp.Header,
		"trailer":     resp.Trailer,
		"status":      resp.Status,
		"status_code": string(resp.StatusCode),
	}, err
}
```

**Comment by wonderflow** [comment]
good idea, would you like to contribute this feature?
