### ISSUE TITLE
When the dependencies of a local addon are not enabled, an error occurred

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#3182]
**Describe the bug**

When the dependencies of a local addon are not enabled, an error occurred.

```
➜  catalog git:(generate-terraform-addon) ✗ vela addon enable ./addons/terraform-tencent-REVIEW TENCENTCLOUD_SECRET_ID=xxx TENCENTCLOUD_SECRET_KEY=yyy TENCENTCLOUD_REGION=zzz
Error: fail to get addon meta: registry don't have enough info to build a reader
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wangyikewxgm** [comment]
IMO this issue have been fixed. Closing，feel free if the issue still exist.
