### ISSUE TITLE
kubevela panic: runtime error: invalid memory address when installing

### ISSUE THREAD

**Issue by jguionnet** [kubevela/kubevela#3186]
**Describe the bug**

kubevela panic: runtime error: invalid memory address 

kubevela-vela-core-574b6fbd7c-sc6bv kubevela I0204 21:35:20.954613       1 capability.go:599] "Successfully update Capability Schema in ConfigMap" configMap="vela-system/component-schema-aws-subnet-v1"
kubevela-vela-core-574b6fbd7c-sc6bv kubevela panic: runtime error: invalid memory address or nil pointer dereference
kubevela-vela-core-574b6fbd7c-sc6bv kubevela [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x20407ce]
kubevela-vela-core-574b6fbd7c-sc6bv kubevela
kubevela-vela-core-574b6fbd7c-sc6bv kubevela goroutine 790 [running]:

**To Reproduce**
With VELA_VERSION = 1.2.2

	@echo
	@echo "Install Kubevela..."
	@kubectl apply -f resources/namespace.yaml
	@helm repo add kubevela https://charts.kubevela.net/core
	@helm repo update
	@helm upgrade --install --namespace vela-system kubevela kubevela/vela-core --version $(VELA_VERSION)  --set multicluster.enabled=true --wait
 
**KubeVela Version**
1.2.2

**Cluster information**
 K8s Rev: v1.20.11-eks-f17b81

**Additional context**
Same steps works well with VELA_VERSION=1.2.1

**Comment by wonderflow** [comment]
Can you help provide more logs? It should have some code line

**Comment by zzxwill** [comment]
@jguionnet Did you see any logs like those in https://github.com/oam-dev/kubevela/issues/3191? Can you try `kubectl delete componentdefinition aws-subnet -n vela-system` and see whether it works?

**Comment by wonderflow** [comment]
closing as we have release v1.3.x, please have a try. feel free to reopen this issue if there's still any problem.
