### ISSUE TITLE
Failed to install vela-core in user-defined namesapce: kubevela using helm

### ISSUE THREAD

**Issue by lshmouse** [kubevela/kubevela#3220]
**Describe the bug**

Failed to install vela-core in user-defined namesapce: kubevela using helm.

Is vela-core only be installed in namespaces "vela-system"?

**To Reproduce**

1, helm upgrade -i --create-namespace kubevela kubevela/vela-core --namespace kubevela 

```
Release "kubevela" does not exist. Installing it now.
Error: namespaces "vela-system" not found
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

helm chart: vela-core-1.2.2

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
@lshmouse Installing to custom namespaces is currently not recommended.

**Comment by barnettZQG** [comment]
https://github.com/oam-dev/kubevela/pull/3163 This PR may be fixed this issue.

**Comment by wonderflow** [comment]
You can try the new release v1.2.3 that includes the #3163

**Comment by wonderflow** [comment]
closing, feel free to reopen it if you still encounter the same issue in the new version.
