### ISSUE TITLE
[Feature] Generate documentation for ComponentDefinition By local yaml files

### ISSUE THREAD

**Issue by Nicola115** [kubevela/kubevela#3251]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Vela now supports generating documentation for ComponentDefinition from the running application in vela-system namespace. For example, using following command to generate docs for alibaba-eip.  `vela def doc-gen alibaba-eip -n vela-system`  
  
Can vela supports generating documentation for ComponentDefinition directly from local yaml files such as `vela def doc-gen <COMPONENT_NAME> --local <DEFINITION.yaml>`

**Describe alternatives you've considered**

**Additional context**

**Comment by zzxwill** [comment]
It's implemented by @Nicola115 .
