### ISSUE TITLE
[Feature] addon cli support generate a basic skeleton 

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#3262]
**Is your feature request related to a problem? Please describe.**

vela addon should  help developer to make an addon more easily. I proposal add a command like  `vela addon init ./` will generate such as  `template.yaml ` `readme.md` files  in a dir.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
supported in v1.5.0
