### ISSUE TITLE
Can't deploy app for multi-clusters using OCM

### ISSUE THREAD

**Issue by dongwenjuan** [kubevela/kubevela#3287]
**Describe the bug**
Can't deploy app for multi-clusters using OCM

**To Reproduce**

1. use `vela cluster join ha3.kubeconfig --name cluster3 --engine ocm --in-cluster-boostrap=false ` to add managescluster

2. query managed cluster
`# vela cluster list`
CLUSTER         TYPE                            ENDPOINT
cluster3        OCM ManagedServiceAccount       - 

`# kubectl get mcl`
NAME       HUB ACCEPTED   MANAGED CLUSTER URLS        JOINED   AVAILABLE   AGE
cluster3   true            https://control-plane.minikube.internal:8443   True     True        25h

In the managedcluster resource, the "MANAGED CLUSTER URLS" is the server address of hub cluster, NOT the managed cluster address.
It's a bug in the cli code:  https://github.com/oam-dev/kubevela/blob/master/references/cli/cluster.go#L331

3.  Add the flag `--ocm-integration=true` to cluster-gateway deployment and restart the pods.
Run the command，no clustergateways resources can be queried.
`# kubectl get clustergateways
NAME       PROVIDER   CREDENTIAL-TYPE       ENDPOINT-TYPE`

4. Deploy an app using env-binding, the errlog for the cluster-gateway pods: 
`# kubectl -n vela-system logs -f  kubevela-cluster-gateway-7d9f48545f-86p6m`
I0216 08:21:42.961667       1 plugins.go:158] Loaded 2 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,MutatingAdmissionWebhook.
I0216 08:21:42.961758       1 plugins.go:161] Loaded 1 validating admission controller(s) successfully in the following order: ValidatingAdmissionWebhook.
I0216 08:21:43.167816       1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0216 08:21:43.167821       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0216 08:21:43.167866       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0216 08:21:43.167855       1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0216 08:21:43.167873       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0216 08:21:43.167911       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0216 08:21:43.168338       1 dynamic_serving_content.go:129] "Starting controller" name="serving-cert::/etc/k8s-cluster-gateway-certs/apiserver.crt::/etc/k8s-cluster-gateway-certs/apiserver.key"
I0216 08:21:43.261047       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0216 08:21:43.261057       1 secure_serving.go:266] Serving securely on [::]:9443
I0216 08:21:43.361681       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController
I0216 08:21:43.361720       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0216 08:21:43.361683       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0217 01:19:42.860888       1 clustergateway_types_secret.go:139] Master loopback client: https://10.96.0.1:443
W0218 01:50:53.198288       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:50:53.198343       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:50:53.326241       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:50:53.326291       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:50:53.734823       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:50:53.734874       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:50:54.388787       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:50:54.388847       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:50:55.390346       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:50:55.390397       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:50:56.496495       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:50:56.496545       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:50:57.081791       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:50:57.081839       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:51:00.303640       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:51:00.303691       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:51:06.306186       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:51:06.306250       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:51:18.393535       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found
E0218 01:51:18.393585       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no such cluster cluster3"}: no such cluster cluster3
W0218 01:51:43.388320       1 clustergateway_types_secret.go:43] Failed getting secret "vela-system"/"cluster3": secrets "cluster3" not found

Is there anything I missed to config? 

**Expected behavior**

**Screenshots**

**KubeVela Version**
# vela version
Version: v1.2.3
GitRevision: git-fbef61d
GolangVersion: go1.17.6

**Cluster information**
# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by Somefive** [comment]
Currently, the combination of OCM and KubeVela might have some potential problems. The capability provided in KubeVela now relies on integrating OCM manually which makes it relatively hard to directly use OCM in KubeVela. We intend to fix this problem soon (possibly in 1.3). Could you introduce your scenario of using OCM in detail so that we can better fit you use case?

**Comment by dongwenjuan** [comment]
We don't have special scenarios, just want to deploy app in multi-clusters. The build-in multi-cluster function doesn't have the scheduler policy to config, so we try to use OCM for research.

**Comment by Somefive** [comment]
@dongwenjuan We are planning to have a scheduler policy recently. Could you give more details on your demands for the scheduler? Like placing pods of a deployment across child clusters?

**Comment by dongwenjuan** [comment]
Hi Somefive，
    Just like other multi-clusters tools as KubeFed or Karmada scheduler policy: ReplicaScheduling、clusterAffinity、clusterTolerations、spreadConstraints、 resourceSelectors and so on.

**Comment by Somefive** [comment]
> Hi Somefive， Just like other multi-clusters tools as KubeFed or Karmada scheduler policy: ReplicaScheduling、clusterAffinity、clusterTolerations、spreadConstraints、 resourceSelectors and so on.

I see. ClusterAffinitiy & ResourceSelectors are WIP. ReplicaScheduling is planning and will be developed after the previous two. ClusterTolerations and SpreadContraints are in the proposing stage.

**Comment by dongwenjuan** [comment]
OK，got it. Thanks for your reply. Looking forword to see these functions online~

**Comment by rtrive** [comment]
@Somefive what do you mean "relatively hard to directly use OCM in KubeVela"? Does it mean that is not possible at all or are there other ways to make it work?
My use case it to put deployment on child clusters

**Comment by Somefive** [comment]
> @Somefive what do you mean "relatively hard to directly use OCM in KubeVela"? Does it mean that is not possible at all or are there other ways to make it work? My use case it to put deployment on child clusters

Putting deployment on child clusters in KubeVela do not necessarily need OCM installed, if you child clusters are connectable from the hub cluster. See https://kubevela.io/docs/next/case-studies/multi-cluster. 

If you mean you only have connections from child clusters to hub cluster but do not have the reverse way, you need to install OCM addon. See https://github.com/wonderflow/ocm-kubevela-demo for more details.

**Comment by rtrive** [comment]
I'm trying to experiment with the example that you send me (thanks a lot) but unfortunately, the error that I got is [this](https://github.com/wonderflow/ocm-kubevela-demo/issues/1).
I would like to use OCM since it's more secure IMHO to use it in a multicluster environment.

**Comment by wonderflow** [comment]
Hi @rtrive  We have fixed this demo, would you like to have a try with the doc: https://github.com/kubevela/samples/tree/master/12.Open_Cluster_Management_Demo

**Comment by wonderflow** [comment]
closing, feel free to reopen it if you still have this issue.
