### ISSUE TITLE
An offline cluster cannot be deleted

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#3328]
**Describe the bug**

**To Reproduce**

1. Join a new cluster.
2. Create an application and deploy it to this cluster.
3. Cluster arrears or other reasons go offline.
4. The application can not be deleted, because the cluster is offline.
5. The cluster can not be detached, because there are some applications.
6. The deadlock...

**KubeVela Version**

1.2.X

**Comment by Somefive** [comment]
This is currently a feature. Offline clusters could return back later. Therefore we could use `vela delete --force` command to solve this problem. There should be a more detailed mechanism to handle the garbage collection of resources in ResourceTracker, for example skip part of them.

**Comment by wonderflow** [comment]
the application can be deleted by `vela delete --force`

**Comment by barnettZQG** [comment]
> the application can be deleted by `vela delete --force`

We need to support this feature in VelaUX.

**Comment by barnettZQG** [comment]
@Somefive Another way to do this is to remove the offline cluster from the application configuration and publish it again.

**Comment by Somefive** [comment]
> > the application can be deleted by `vela delete --force`
> 
> We need to support this feature in VelaUX.

Not agree to that. `vela delete --force` is a dangerous action and is not recommended. Users need to really know what they are doing and the side effect for running this command, like resource leak. For VelaUX users, they usually cannot ensure that, then this super button can easily destroy the resource management.

Instead, I think on VelaUX, we should provide a comprehensive view for all the managed resources like ArgoCD. Then when deletion of application is blocked, a redirect should be given to user and let user to determine how to handle each blocked resources.

**Comment by Somefive** [comment]
> @Somefive Another way to do this is to remove the offline cluster from the application configuration and publish it again.

The offline cluster could be used by lots of applications, and this action could potentially cause a huge number of application restarts. This behavior is also dangerous and could lead to unpredicted performance issues. We should consider the solution carefully.

**Comment by Somefive** [comment]
In general, I agree this problem is crucial. In CLI, we previously work on `vela delete --force` to give a solution, which I believe, is not a final elegant solution. The best potential solution currently I come up with is the fine-grained resource control on top of ResourceTracker, which needs some time to implement but is not a high priority target by now. If other light elegant solution is proposed, we can work on it faster.

**Comment by Somefive** [comment]
We now removed the in-use check when detaching clusters. And we have `vela delete -i` to manually remove resources in application.
