### ISSUE TITLE
[Feature] 希望可以提供便捷的APIserver 用例和文档

### ISSUE THREAD

**Issue by workman-Lu** [kubevela/kubevela#3338]
目前已有文档
https://github.com/oam-dev/kubevela/blob/master/design/vela-core/restful-interface.md

  首先，VelaUX是一个很好的前端实现思路。但是它和一系列低代码一样，束缚了我们对应用管理的思维和其他系统整合的能力。

  VelaCore是一个很好的控制器。所以我们考虑接入apiserver打通devops流程而不使用velaUX作为前端，目前的简易的restful文档带来比较大的学习成本，我认为这可能跟大家都是终端用户，以体验为主有关系。作为一个平台引擎，希望能提供稳定，兼容，开放的api interface。这会带来更大的价值。

  目前只对前端操作后端特定资源有大致了解，不敢确认直接使用API添加资源是否会有依赖关系和多个api操作合并的情况。目前这方面的文档的缺失，使vela管理开发需要先看一遍apiserver原理的情况。

**Comment by barnettZQG** [comment]
@workman-Lu 
https://github.com/oam-dev/kubevela/blob/master/docs/apidoc/swagger.json 这里是目前 Vela API 的 swagger 文档，目前 API 具有一定的业务含义，比如包含了现在底层 CRD 中还不存在的概念：环境、部署、组件分离管理等。如果你只需要操作核心对象Application，你可以直接通过 Kube-api 集成即可。如果你需要类似 VelaUX 中定义的业务概念，你可以对接 Vela API。

对于 VelaUX ，目前它还处于非常早期的阶段。我们从设计上尽可能实现它的前端呈现开放性，例如目前实现的输入参数的完全动态化。后期会逐步实现的数据可视化开放性。 关于 “束缚了我们对应用管理的思维和其他系统整合的能力” 这个点可否提供更多的说明信息？

**Comment by workman-Lu** [comment]
> 

velaUX是面向终端用户的，这意味着中大型团队使用会面临着一些复杂的需求问题。如果ux完善之后我们看起来它像是paas的解决方案，但是打通到saas依然存在信息孤岛的问题。这意味着我们从使用之初就考虑apiserver直接调用，但是目前使用上velacore的完成能力需要依赖app env env-bind workflow。例如我无法不绑定workflow发布到我想发布的地址。或者通过OAM applications 直接渲染出发布资源（iaas资源绝对安全考虑）。这些原子的能力。类似workflow这类更多是为了解决前端发布的后端集成方案。目前是耦合在velacore这个发布里面，这增加了维护成本和系统间信息沟通成本。

**Comment by workman-Lu** [comment]
因为对于应用来说，app traits 是必须的 triger是可选的，workflow也是非必要的一部分。
应用生命周期管理和发布系统应该是分开的两个领域

**Comment by wonderflow** [comment]
Please check if this docs match your needs https://kubevela.stoplight.io/docs/kubevela/b3A6NDI5NzQxMzM-detail-definition
