### ISSUE TITLE
The workload is not defined when the component is created and the final expectation is inconsistent

### ISSUE THREAD

**Issue by wxuedong** [kubevela/kubevela#3343]
version:
Version: 1.1.6
GitRevision: git-844f479f
GolangVersion: go1.17.2

Yaml：
```
stateless: {
    annotations: {}
    description: ""
    labels: {}
    type: "component"
}

template: {
    output: {
        spec: {
            selector: matchLabels: "app.oam.dev/component": "name"
            template: {
                metadata: labels: "app.oam.dev/component": "name"
                spec: containers: [{
                    name:  "name"
                    image: "image"
                }]
            }
        }
        apiVersion: "argoproj.io/v1alpha1"
        kind:       "Rollout"
    }
    outputs: {}
    parameters: {}
}
```

`attributes: workload: definition`  field information is not declared ，the final result is `deployments.apps` 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/15843627/156133530-f74029ce-80a4-45f9-bec8-e3570db510b2.png">

I think this setting other default values is not in line with declarative design

**Comment by wonderflow** [comment]
You can fix this issue by adding the field `attributes: workload: definition`

```
stateless: {
    annotations: {}
    description: ""
    labels: {}
    type: "component"
    attributes: workload: definition: {
        apiVersion: "argoproj.io/v1alpha1"
        kind:       "Rollout"
    }
}

template: {
    output: {
        spec: {
            selector: matchLabels: "app.oam.dev/component": "name"
            template: {
                metadata: labels: "app.oam.dev/component": "name"
                spec: containers: [{
                    name:  "name"
                    image: "image"
                }]
            }
        }
        apiVersion: "argoproj.io/v1alpha1"
        kind:       "Rollout"
    }
    outputs: {}
    parameters: {}
}
```


Yes, it's also possble to infer from the data in `template.output.apiVersion` and `template.output.kind `.

Welcome to contribute this fix if you'd like to. Thanks.

**Comment by wonderflow** [comment]
Closing as the `spec.workload` is a required value now.

> Error: failed to create new definition in kubernetes: ComponentDefinition.core.oam.dev "argo" is invalid: spec.workload: Required value
