### ISSUE TITLE
[Feature]Addon yaml files discovery logic improvement

### ISSUE THREAD

**Issue by cezhang** [kubevela/kubevela#3352]
**Is your feature request related to a problem? Please describe.**

With developing a addon on my Macbook with IDE, I very often came across an error "Error: render addon application fail: yaml: control characters are not allowed". It's  actually not the problem about  yaml file, but it display a very misleading message.
I track down the code and found 
```
func readDefFile(a *UIData, reader AsyncReader, readPath string) error {
	b, err := reader.ReadFile(readPath)
	if err != nil {
		return err
	}
	filename := path.Base(readPath)
	file := ElementFile{Data: b, Name: path.Base(readPath)}
	switch filepath.Ext(filename) {
	case ".cue":
		a.CUEDefinitions = append(a.CUEDefinitions, file)
	default:
		a.Definitions = append(a.Definitions, file)
	}
	return nil
}
```
in addon.go file. 

I think the default case is inappropriate here. 

In my case,  creating and moving files around inside the "resources" folder, the mac will generate a hidden file  .DS_Store and will no display in IDEA, while enabling the addon, misleading error shows up.
This  very costs me a lot time to troubleshoot the problem. Also that will be a problem for other filesystem doing something operation like that, OR you accidentally put other format yaml in "resources" folder.

**Describe the solution you'd like**

Specify the file format 
case ".yaml" or ".yml": ....

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyikewxgm** [comment]
Thanks for reporting! I think  a small fix can solve this problem. Would you mind make a pr to fix this bug?  : )@cezhang

**Comment by cezhang** [comment]
Sure @wangyikewxgm
