### ISSUE TITLE
[Feature] Built-in VelaQL query capability to Vela-Cli

### ISSUE THREAD

**Issue by yangsoon** [kubevela/kubevela#3361]
**Is your feature request related to a problem? Please describe.**

### BackGround

VelaQL(Vela Query Language) is a resource query language for KubeVela, used to query application-level resource status. more details refer to [doc](https://kubevela.io/docs/platform-engineers/system-operation/velaql).

The purpose of VelaQL is to help developer better query status of resources created by Application. or use the extensible interface provided by velaQL to customize query resource information to improve the observability of Application.

### Problem

But now the use of VelaQL needs to rely on the apiserver in the velaux addon, and query the resource status needs to request a specific api, like:

```
curl http://127.0.0.1:8000/api/v1/query?velaql=component-pod-view{appName="test-app"}
```

This method is suitable for paas platforms like VelaUx, but it's unfriendly to developers and SRE. 

### Imporve

In order to improve the experience of using VelaQL, we need to build the query capability of VelaQL into vela-cli. developer can use command like `vela ql` , and input the VelaQL.(`vela ql` is an interactive command, The user can input the VelaQL repeatedly.)

**Describe the solution you'd like**

### Built into vela-cli

We should add a new vela command `vela ql`. In fact, the `vela status` command has already used the capabilities of VelaQL, so we can refer to the [code](https://github.com/oam-dev/kubevela/blob/1cb4426e4bd2c44aae91022940a3623c372ca7ff/references/cli/velaql.go#L31
).

### Friendly interactive experience

You must have used `ipython`, `ipython` friendly interactive experience can help us write python code better. [https://github.com/c-bata/go-prompt](https://github.com/c-bata/go-prompt) can help you use the golang to provide users with an ipython-like interactive experience. 

> you can also refer to [https://github.com/c-bata/kube-prompt](https://github.com/c-bata/kube-prompt)

![gif](https://github.com/c-bata/assets/raw/master/go-prompt/kube-prompt.gif)

#### Syntax completion
Views and query conditions are the core components of VelaQL, To be able to provide friendly syntax completion on the command line, you can refer to the `vela show` command.

#### Pretty print
The query data should be printed pretty, we can use [https://github.com/olekukonko/tablewriter](https://github.com/olekukonko/tablewriter)

**Describe alternatives you've considered**

### 

**Additional context**

**Comment by andream7** [comment]
#3511
