### ISSUE TITLE
[Feature] Extend persistent resource selector

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#3395]
**Is your feature request related to a problem? Please describe.**

Current persistent resource only support resources managed by traits, we should extend the selector to component name and resource type.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Somefive** [comment]
#3424 extends the selector to support component type. Further rules can be added such as filtering by resource kind / component name / resource name. Let's make it a "first good issue".

**Comment by Somefive** [comment]
#3539 extends the selector to support component name.

**Comment by Freedisch** [comment]
Hello @Somefive What's the current state of this issue? Since there is already a merged PR  related to this issue.

**Comment by Somefive** [comment]
This issue has been solved with a wide range of selectors now.
