### ISSUE TITLE
Helm 组件不支持阿里云容器镜像仓库的charts吗？

### ISSUE THREAD

**Issue by clcc2019** [kubevela/kubevela#3421]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/46099295/157796710-5a57a6db-3220-4ebd-8684-efaac38d77d2.png">
<img width="395" alt="image" src="https://user-images.githubusercontent.com/46099295/157796818-503ca0d8-9ab6-44f9-9d95-d42e83b82587.png">

**Comment by FogDong** [comment]
这个应该是私有镜像，需要秘钥凭证 /cc @wangyikewxgm

**Comment by clcc2019** [comment]
> 这个应该是私有镜像，需要秘钥凭证 /cc @wangyikewxgm

有secretRef呢

**Comment by wangyikewxgm** [comment]
@clcc2019 现在暂时还不支持 OCI 的 repo

**Comment by wonderflow** [comment]
ping @wangyikewxgm , have we supported this feature?

**Comment by wangyikewxgm** [comment]
You can try this feature by use argocd addon: https://github.com/kubevela/catalog/tree/master/experimental/addons/argocd

**Comment by wangyikewxgm** [comment]
Good news is the fluxcd have support OCI registry . We can wait until this commit be released.https://github.com/fluxcd/source-controller/pull/690
