### ISSUE TITLE
Cannot use `dependsOn` in `components` when `deploy2env` exists

### ISSUE THREAD

**Issue by huanggze** [kubevela/kubevela#3510]
**Describe the bug**

Cannot use `dependsOn` in `components` when `deploy2env` exists

**To Reproduce**

I am following the How-to Guides [Cloud Resources - Provision a Database and Import a SQL File for initialization](https://kubevela.io/docs/end-user/components/cloud-services/provision-and-initiate-database#!), and intentionally add `dependsOn` within the `web` component like below:

```cue
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: favorite-links
spec:
  components:
    - name: web
      type: webservice
      properties:
        image: oamdev/nodejs-mysql-links:v0.0.1
        port: 4000
      #################
      # MY CHANGE HERE #
      #################
      dependsOn:
      - db
      traits:
# ...
```

Then I apply this YAML, but get error below:

```bash
$ vela status favorite-links

About:

  Name:      	favorite-links
  Namespace: 	default
  Created at:	2022-03-25 14:25:38 +0800 CST
  Status:    	runningWorkflow

Workflow:

  mode: StepByStep
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id:ul2if3351w
    name:deploy
    type:deploy2env
    phase:failed
    message:step app: step apply: step outputs: _|_ // field "dependsOn" not allowed in closed struct
: app.apply.outputs: field "dependsOn" not allowed in closed struct

Services:
```

**Expected behavior**

No error, `dependsOn` should not be denied.

**Screenshots**

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/22350668/160079115-62695f89-540e-476c-ab62-e3775c7b95d3.png">

**KubeVela Version**

CLI Version: v1.2.4
Core Version: 1.2.4
GitRevision: git-f6032f3
GolangVersion: go1.17.7

**Cluster information**

v1.22.3

**Additional context**

**Comment by huanggze** [comment]
Seems duplicate with #3441

**Comment by Somefive** [comment]
The reason for not supporting `dependsOn` is #3394.

**Comment by huanggze** [comment]
> The reason for not supporting `dependsOn` in `deploy2env` is #3394.

Thanks for your reply. but I wonder if there is a way to apply components in order?

**Comment by Somefive** [comment]
> > The reason for not supporting `dependsOn` in `deploy2env` is #3394.
> 
> Thanks for your reply. but I wonder if there is a way to apply components in order?

Yes. You can use `apply-component` in WorkflowStep to manually controller the order for components to deploy. If combined with env-binding, the default order is the order of components declared in the application spec.

**Comment by huanggze** [comment]
Thanks for clarification!

**Comment by Somefive** [comment]
Let's make this issue open until we support this feature.

**Comment by fourierr** [comment]
> > > The reason for not supporting `dependsOn` in `deploy2env` is #3394.
> > 
> > 
> > Thanks for your reply. but I wonder if there is a way to apply components in order?
> 
> Yes. You can use `apply-component` in WorkflowStep to manually controller the order for components to deploy. If combined with env-binding, the default order is the order of components declared in the application spec.
If i use `apply-component` , how can i assign namespace to component?

**Comment by wonderflow** [comment]
It's supported in https://github.com/kubevela/kubevela/pull/3750 , you can use `deploy` workflowstep for this. I'm closing this.
