### ISSUE TITLE
[Feature] Sort variables and outputs for a cloud resource specification

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#3536]
The properties and outputs should be in alphabetical order, which will help users to look for the usages.

Or all specifications will be modified even one or a few cloud resources is modified like https://github.com/oam-dev/kubevela.io/pull/553/files.

**Comment by Nicola115** [comment]
I've write a tool for sorting providerName and resourceName in the cloud-resources-list.md: https://github.com/Nicola115/try-kubevela-tools/blob/master/sort-form-doc/main.go

But I'm not sure if that's what you want. And if so, where to add the sorting tool in kubevela repo?

**Comment by zzxwill** [comment]
@Nicola115 Good job! Thanks.
