### ISSUE TITLE
[Feature]A vela command line is wanted for converting container app to kubevela app

### ISSUE THREAD

**Issue by fourierr** [kubevela/kubevela#3552]
## Request description

In the process of enterprise practice, there are large mount container apps needed to convert kubevela apps.Therefore,
we need a feature for converting container app to kubevela app easily and conveniently.

### Step 1. There is a vela command line as follows

```shell script
vela convert [{comp=comp_c,cluster=cluster_a, ns=ns_a, deployName=deploy_a}, {comp=comp_c,cluster=cluster_b, ns=ns_b, deployName=deploy_b}] -n app_c
```

In this case, the first deployment `deploy_a` in `ns_a.cluster_a` and second deployment `deploy_b` in `ns_b.cluster_b`
will be aggregate a kubevela application `app_c` include `comp_c`.

### Step 2. Find the related resource

- Firstly, we find each deployment via cluster and namespace
- Secondly, range the deployment, find the related resource via `spec.template.spec.volumes[*].`
  ,`spec.template.spec.containers[*].env[*].valueFrom` etc
-

### Step 3. Generate KubeVela Application

- Firstly, based on the related resources, determine the Component and Trait, just like `webservice` or `work`
- Secondly, ensuring the Policy and WorkflowStep. `deploy/topology/override`
- thirdly, assemble application to get the complete KubeVela application

### Step 4. Validate the application

There is a strict format check to ensure that the application format is proper, just like `vela dry run`. In the
meantime it's inevitable to lose some special condition, and we can avoid deploy error via validation.

### Step 5. Write deployment plan back to db

Write Deployment plan back to db via validated application

### Step 6. Deploy app

Deploy application via ctrl client

## Additional context
There are several principles:
- The convert of container app should not cause restart pod.

Please review it, and we will do this feature in April.

**Comment by Somefive** [comment]
So the scenario is like
1. There are deployments already running in clusters.
2. You want to add an application on top of them to help manage them like upgrade or recycle.

The idea is good. The proposed command `vela convert` is a bit confusing. It might be better to use some other more elegant name. /cc @wonderflow 

Besides, the 6 steps could be split into different parts. For example, step 1~3 can be achieved by a simple command and generate a KubeVela Application yaml. Step 4 can be done by different ways, like validating through vela CLI / webhook. Step 5 is another topic for controller to maintain data. Step 6 can achieved by `vela up` command.

**Comment by wonderflow** [comment]
@fourierr what is the purpose of adopting the deployment? Will the user or third-party system manage the deployment directly after this convert?

There can be different Implementation for different purposes, there're two possible scenarios:

1. adopt the deployment as KubeVela application and after that using application to manage the whole lifecycle.
2. adopt the deployment but still allow deployment be managed by 3rd-party systems, just want to leverage the trait or workflow capability of KubeVela Application.

We have both plans to realize the scenarios, but we can narrow the case in this issue.

Assume we're discussing the first case, the user experience could like the flow you described here excepting:

1. the command like could be like:
```
vela adopt deployment --cluster=cluster_a --namespace ns_a --name=deploy_a --comp=comp_c --combine-with=path/to/local-app.yaml
```

- use `adopt` instead of `convert`
- one component can only adopt one resources
- give extension interface for more than deployment kind
- the command line should be easy enough, or there can be other ways
    * interactive way of this command line, user can just input `vela adopt` then there will prompt the hint about what's expected or choices.
    * use a adopt.yaml file to describe the adoption resources
- the affect of the command cli is out put an application yaml file or print the application into stdout, it won't deploy the application 

2. the related resources should also be adopted into the component as component or trait.

**Comment by fourierr** [comment]
> @fourierr what is the purpose of adopting the deployment? Will the user or third-party system manage the deployment directly after this convert?
> 
> There can be different Implementation for different purposes, there're two possible scenarios:
> 
> 1. adopt the deployment as KubeVela application and after that using application to manage the whole lifecycle.
> 2. adopt the deployment but still allow deployment be managed by 3rd-party systems, just want to leverage the trait or workflow capability of KubeVela Application.
> 
> We have both plans to realize the scenarios, but we can narrow the case in this issue.
> 
> Assume we're discussing the first case, the user experience could like the flow you described here excepting:
> 
> 1. the command like could be like:
> 
> ```
> vela adopt deployment --cluster=cluster_a --namespace ns_a --name=deploy_a --comp=comp_c --combine-with=path/to/local-app.yaml
> ```
> 
> * use `adopt` instead of `convert`
> * one component can only adopt one resources
> * give extension interface for more than deployment kind
> * the command line should be easy enough, or there can be other ways
>   
>   * interactive way of this command line, user can just input `vela adopt` then there will prompt the hint about what's expected or choices.
>   * use a adopt.yaml file to describe the adoption resources
> * the affect of the command cli is out put an application yaml file or print the application into stdout, it won't deploy the application
> 
> 2. the related resources should also be adopted into the component as component or trait.

In most case, the container app was deployed in two or three cluster for high availability, so we want to adopt two deployment in different cluster(have same spec just cluster is different) to one component.

**Comment by wonderflow** [comment]
I'm planning to make it a feature of vela in v1.6. Not only deployment, but also for all Kubernetes CRD with [resource topology](https://kubevela.net/docs/reference/topology-rule) defined.

**Comment by fourierr** [comment]
> I'm planning to make it a feature of vela in v1.6. Not only deployment, but also for all Kubernetes CRD with [resource topology](https://kubevela.net/docs/reference/topology-rule) defined.
For all Kubernetes CRD is difficult but worthwhile.
