### ISSUE TITLE
velaux对trait的前端支持不完整

### ISSUE THREAD

**Issue by reckless-huang** [kubevela/kubevela#3578]
**Describe the bug**

我尝试在velaux中为应用新增一个运维特征，但是好像不是所有的trait都有参数支持
![image](https://user-images.githubusercontent.com/53162954/161368302-840ffe9a-7106-4e13-a315-274efe0fdb7e.png)
![image](https://user-images.githubusercontent.com/53162954/161368307-a68c03f8-f7e0-44bd-bced-b3d3dc422788.png)

**To Reproduce**

新增组件----》新增运维特征

**KubeVela Version**

![image](https://user-images.githubusercontent.com/53162954/161368327-d091be7b-fc07-4516-80aa-4443fdec0b5c.png)

**Cluster information**
![image](https://user-images.githubusercontent.com/53162954/161368338-8d49f28a-f337-49c6-9a4c-5d4eeb79f08f.png)

**Comment by barnettZQG** [comment]
This issue is fixed by kubevela/velaux#545
