### ISSUE TITLE
[Feature] Replace Dex logo with KubeVela logo

### ISSUE THREAD

**Issue by FogDong** [kubevela/kubevela#3583]
**Is your feature request related to a problem? Please describe.**

In KubeVela 1.3, we can use dex for login like below:
![image](https://user-images.githubusercontent.com/15977536/161376631-231eabae-2382-4e04-8af2-ce1f0da102aa.png)

It's better if we can replace dex logo with KubeVela logo. In order to do this, we need to change the source code in [dex](https://github.com/dexidp/dex).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
link to kubevela logo:
* https://github.com/oam-dev/kubevela.io/blob/main/static/img/logo.svg
* https://github.com/oam-dev/kubevela.io/blob/main/static/img/logo.jpg

**Comment by charlie0129** [comment]
Any advice on where the edited source code of dex will go?

**Comment by FogDong** [comment]
> Any advice on where the edited source code of dex will go?

Hi, you can take a look at [here](https://github.com/dexidp/dex/blob/master/web/themes/light/logo.png)

BTW, I think we should fork dex for this issue. /cc @wonderflow

**Comment by charlie0129** [comment]
Well, is editing the source code of `dex` a must? If it is, we might also need a fork, helm chart, changes to the dex addon , etc.

One question, why is editing configuration entry not considered:

```yaml
frontend:
  logoURL: https://kubevela.net/img/logo.svg # or any other logo
```

**Comment by wonderflow** [comment]
```
frontend:
  logoURL: https://kubevela.net/img/logo.svg # or any other logo
```

If this works, we should use this configuration instead of fork the dex repo.

**Comment by charlie0129** [comment]
An example with KubeVela logo using the above configuration looks like this:

![Screen Shot 2022-05-05 at 1 42 47 PM](https://user-images.githubusercontent.com/55270174/166868625-d3bb5e16-9e3e-4153-85a6-10f4a9d69a5f.png)

**Comment by wonderflow** [comment]
@charlie0129  Great, that's what we expected. Please send a PR. BTW, is that possible to replace the icon.

![image](https://user-images.githubusercontent.com/2173670/166873856-50243029-ddb5-4547-b3fe-df749182a7f3.png)

**Comment by charlie0129** [comment]
AFAIK, changing favicon is not possible without changing web static files in dex. Configuration file alone is not enough.

Will investigate.
