### ISSUE TITLE
v1.3.0 no addon info

### ISSUE THREAD

**Issue by clcc2019** [kubevela/kubevela#3585]
![image](https://user-images.githubusercontent.com/46099295/161422500-2207f8a8-1c8c-41e5-ac5f-50d8bc21c431.png)

**Comment by wonderflow** [comment]
Have you upgrade the vela-core to v1.3.0? It seems the server lost the configuration of addon, you can apply this configmap and try again:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-addon-registry
  namespace: vela-system
data:
  registries: '{
  "KubeVela":{
    "name": "KubeVela",
    "helm": {
      "url": "https://addons.kubevela.net"
    }
  }
}'

```

**Comment by barnettZQG** [comment]
@clcc2019 Are there any more updates?

**Comment by wonderflow** [comment]
I'm closing this issue as there's no more info, feel free to reopen it if you still occur this issue in v1.3.3
