### ISSUE TITLE
Problem of converting batch applications

### ISSUE THREAD

**Issue by reckless-huang** [kubevela/kubevela#3606]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/53162954/162392660-2c23600d-5a93-44a3-9c94-9c6fd0cd94cf.png)
如图我想使用velacore通过api调用完成这类转换过程，但是velacore提供的create函数和我直接写一份yaml提交并无区别，大多数的参数都是map[string]interface{},我需要先使用vela def get configmap查看对应trait的cue定义
![image](https://user-images.githubusercontent.com/53162954/162392881-08e1b90f-2ae6-4559-8513-e2e48313fea6.png)
然后我才能知道如何填充map[string]interface{},这个过程我需要重复多次，因为在之前的k8s原生对象中有多个trait（configmap, label等）,这样看就已经背离我最开始的期望了

**Describe the solution you'd like**，
有没有一种方法可以从cue中生成对应的go struct，这样我们只要导入对应的struct，就可以获取到具体的参数，而不是都是interface{}
如下：
```
properties: {
 name: string
age?: int
} 
转换为 
type WebServiceProperties struct {
  Name string `required`
 Age int 
}
```

**Describe alternatives you've considered**
对于现在而言，我已经在考虑模板语法，去复制多个yaml了

**Additional context**
vela的确有很强的功能，但是我们是不是应该先保障到最核心的功能，比如cue的渲染能力和app这样一个核心对象，我觉得在转换资源上我应该不是第一个遇到该问题的，社区有好的建议我们也可以一起讨论

**Comment by Ghostbaby** [comment]
目前我们的做法是使用 proto 定义 cue 模版的 parameter ，可以分别生成 go struct 和 cue struct。

**Comment by reckless-huang** [comment]
> 目前我们的做法是使用 proto 定义 cue 模版的 parameter ，可以分别生成 go struct 和 cue struct。

这个方便提供一个示例么

**Comment by wonderflow** [comment]
> 目前我们的做法是使用 proto 定义 cue 模版的 parameter ，可以分别生成 go struct 和 cue struct。

Great, can you also provide some example into vela?

**Comment by chivalryq** [comment]
I wrote a demo, but this haven't been widely tested. Please check https://github.com/chivalryq/def-generator

We can make it a sub-command in `vela def`

**Comment by zzxwill** [comment]
> I wrote a demo, but this haven't been widely tested. Please check https://github.com/chivalryq/def-generator
> 
> We can make it a sub-command in `vela def`

Great! This tool will help a lot for the core team when resembling complicated workflows and policies, and for the community.

**Comment by wonderflow** [comment]
@chivalryq I will keep this issue open as we can really use the API as  SDK in this case.

**Comment by chivalryq** [comment]
Update on this topic:
We are developing a SDK: https://github.com/chivalryq/vela-go-sdk
Releated issue: https://github.com/kubevela/kubevela/issues/5365

**Comment by Somefive** [comment]
Close as potential solution mentioned above. Feel free to reopen this issue.
