### ISSUE TITLE
[Feature] Support basic-auth or reuse chartmuseum as  addon registry 

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#3618]
**Is your feature request related to a problem? Please describe.**

Origin from https://github.com/oam-dev/kubevela/pull/3595#discussion_r845755238

We have support many types addon registry such as git. OSS and helm repo. Helm repo can be used as a versioned registry.
We should support private helm repo  which setup with basic-auth(need set http username and password)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by StevenLeiZhang** [comment]
as metioned in https://github.com/oam-dev/kubevela/pull/3595#discussion_r845814620

Is https://addons.kubevela.net    one  chartmuseum? I download velaux addon and try to upload to my Harbor.

```
➜  addons helm cm-push velaux-v1.3.0.tgz tpaas-oam --force
Error: Chart.yaml file is missing
```

Helm cli reject it

**Comment by wonderflow** [comment]
yes, we should make it compatible.

**Comment by StevenLeiZhang** [comment]
> yes, we should make it compatible.

@wangyikewxgm  @wonderflow 

solution:
1. untar "velaux-v1.3.0.tgz"
2. add one Chart.yaml file as below
```
apiVersion: v1
appVersion: v1.3.0
description: A addon for velaux
home: https://kubevela.io
icon: https://kubevela.io/img/logo.svg
name: velaux
type: library
version: v1.3.0
```
3. repackage
```
helm package velaux
```
it will create one new "velaux-v1.3.0.tgz"
4.push 
```
➜  addons helm cm-push velaux-v1.3.0.tgz reg-oam
Pushing velaux-v1.3.0.tgz to tpaas-oam...
Done.
```

It works now!! The new "velaux-v1.3.0.tgz" is uploaded to Harbor successfully.

Investigation:
Please refer to https://github.com/helm/helm/blob/49819b4ef782e80b0c7f78c30bd76b51ebb56dc8/pkg/chart/loader/load.go#L158
Chart.yaml is mandatory for Helm Chart.


Discussion:
 Do you think it is reasonable to add one Chart.yaml for vela addon, in order to be compatible?

**Comment by wonderflow** [comment]
> Do you think it is reasonable to add one Chart.yaml for vela addon, in order to be compatible?

Yes, and I think this file should be automatically generated from metadata.yaml in addon.

**Comment by wonderflow** [comment]
refer to https://github.com/kubevela/kubevela/issues/3262 as the left thing.

**Comment by wangyikewxgm** [comment]
> > > Do you think it is reasonable to add one Chart.yaml for vela addon, in order to be compatible?
> > 
> > 
> > Yes, and I think this file should be automatically generated from metadata.yaml in addon.
> 
> My proposal: Add more convenient way of addon, which is similar to Helm For example: `vela addon init` to init one addon template `vela addon package` to package addon folder and generate Chart.yaml by metadata.yaml automatically. `vela addon push` to push addon package to registry

Yes, definitely right . Your proposal are also my planning things to do. The `vela addon package` command can generate the `Chart.yaml ` file from metadata.yaml. Do you have interest to implement this feature? We can discuss some details ：）
