### ISSUE TITLE
[Feature] Support force deletion of a Terraform typed application

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#3676]
Sometimes when the error is in the tf or in wrong parameters we give, the only way to delete the resources is to remove finalizers and do it for each one of the kubevela resources like configuration, jobs etc. Perhaps having a -f  flag to force delete would be very helpful

**Comment by quintonm** [comment]
This could also happen with crossplane components as well.

**Comment by zzxwill** [comment]
@quintonm Will it be okay with you if some of the cloud resources got orpahaed?

**Comment by quintonm** [comment]
Yes, that would be okay. We would have the same issue by removing the finalizers.

**Comment by wonderflow** [comment]
are we already supported this feature? ping @chivalryq

**Comment by chivalryq** [comment]
Yes this has been supported. Released in Terraform-controller v0.7.10
