### ISSUE TITLE
[Feature] better upgrade experience for lengthy CMs and CRDs

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#3679]
Lengthy config maps & CRDs causing issues during the upgrades (kubectl apply is not working, we have to delete and recreate the resource).

Comments from @wonderflow:
I know the annotation will record the whole yaml when deployed by vela. It can be reduced. For other issues, we should check it case by case.

**Comment by wonderflow** [comment]
We should remove the following annotation for some resources such as configmap or CRDs

```
 app.oam.dev/last-applied-configuration
```

This label is added at https://github.com/kubevela/kubevela/blob/master/pkg/utils/apply/apply.go#L174

We can add some filter for the target object.

**Comment by zzxwill** [comment]
@quintonm Will it help with the upgrade issue?

**Comment by wonderflow** [comment]
The annotation of configmap and secret is removed, https://github.com/kubevela/kubevela/pull/3939
