### ISSUE TITLE
[Feature] Upgrade CRDs of an add-on

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#3692]
**Is your feature request related to a problem? Please describe.**

KubeVela add-on `terraform` has upgraded from v1beta1 to v1beta2. The CRDs of terraform aren't upgraded by upgrading it using `vela addon upgrade terraform`.

**Describe the solution you'd like**

Provide an option to upgrade the CRDs like 

```
vela addon upgrade terraform --upgrade-crds
```

By using the flag `--upgrade-crds`, vela cli will retrieve all CRDs from the chart and apply them to the cluster.

**Describe alternatives you've considered**

**Additional context**

The proposal can be an alternative and user-friendly way to bypass the helm upgrade issue https://github.com/helm/helm/issues/7735 and follow the best practice like Isitio https://istio.io/latest/docs/setup/upgrade/helm/#canary-upgrade-recommended.

**Comment by zzxwill** [comment]
Related to https://github.com/oam-dev/kubevela/issues/3566.

**Comment by wangyikewxgm** [comment]
In fact, if you just want update crd when upgrade helm chart you just can move the CRD from dir `crds` to dir `templates`. In this way helm will treat them as norm resources.

**Comment by wangyikewxgm** [comment]
Currently, there are two approaches to defining CRD resources in an addon:

1. Defining them in the k8s-objects components: These resources are automatically updated when the addon is upgraded, requiring no additional effort.

2. Including them in a helm component chart and declaring them in the helm component: In this case, FluxCD supports a parameter to update CRDs. We can consider adding this parameter to each helm component addon, allowing users to choose whether to update the CRD

**Comment by zhaohuiweixiao** [comment]
I think the second approach is more elegant. Currently, half of the official addons are implemented using helm components. With the second approach, we can implement crd updates with minimal cost.

And, I'm interested in taking it.

> Currently, there are two approaches to defining CRD resources in an addon:
> 
> 1. Defining them in the k8s-objects components: These resources are automatically updated when the addon is upgraded, requiring no additional effort.
> 2. Including them in a helm component chart and declaring them in the helm component: In this case, FluxCD supports a parameter to update CRDs. We can consider adding this parameter to each helm component addon, allowing users to choose whether to update the CRD
