### ISSUE TITLE
wrong resource apiVersion blocks the resourcetracker gc

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#3698]
Here is my case:
when deploy the ingress (networking.k8s.io/v1beta1) on cluster, but the cluster cannot support the apiVersion.
Events:
 Warning  FailedGC  10m (x24 over 66m)  Application  failed to sweep resourcetrackers to be deleted: failed to get resource networking.k8s.io/v1beta1/Ingress//vela-system/kubevela-io: no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

kubectl get application -A
NAMESPACE     NAME                COMPONENT               TYPE          PHASE      HEALTHY   STATUS      AGE
default       kubevela-io         kubevela-io             webservice    running    true      Ready:1/1   4d6h
vela-system   addon-fluxcd        flux-system-namespace   raw           running    true                  47h
vela-system   addon-kubevela-io   kubevela-io-resources   k8s-objects   deleting                         97m

SO there may be some check items for gc, and allow force-gc.

**Comment by barnettZQG** [comment]
For this case, we should ignore this error during GC.
