### ISSUE TITLE
vela对helm的支持依赖fluxcd或argocd，对用户来说太重了，vela本身可以集成helm controller嘛

### ISSUE THREAD

**Issue by FelixStarship** [kubevela/kubevela#3745]
vela对helm的支持依赖fluxcd或argocd，对用户来说太重了，vela本身可以集成helm controller嘛

**Comment by FelixStarship** [comment]
类似k3s集成的https://github.com/k3s-io/helm-controller

**Comment by StevenLeiZhang** [comment]
应该不会的。个人认为跟vela的设计理念不符合。vela目前的理念是 微内核+插件扩展，按照这个理念的话，helm应该是通过插件机制来支持的。

**Comment by barnettZQG** [comment]
> 在vela里使用helm，其实可以仅安装fluxcd下的helm-controller。然后，要是集成也同样是以addon方式来集成，在一定程度上也可以抽象的更简单。

这种方式我比较认同。

**Comment by wonderflow** [comment]
> 在vela里使用helm，其实可以仅安装fluxcd下的helm-controller。然后，要是集成也同样是以addon方式来集成，在一定程度上也可以抽象的更简单。

ping @wangyikewxgm , we should add one more dependency type "definition", so the helm based addons won't depend on fluxcd, instead, they depend on the component-definition named "helm". After that, we can have addons such as "fluxcd", "argocd" or "helm-controller" in this issue.

**Comment by wangyikewxgm** [comment]
@FelixStarship  看了一下这个项目 https://github.com/k3s-io/helm-controller， 其实你完全可以把这个制作成一个 Addon 集成进 kubevela，只需要定义一个 helm 的 component definition ，在定义app 使用这个类型的 component ，就可以免除依赖fluxcd或者argocd的addon。至于解除其他的 addon 对于 fluxcd 的依赖，我们可以在 addon 的 dependency 机制里，引入依赖某个definition的选项。

**Comment by StevenLeiZhang** [comment]
> > 在vela里使用helm，其实可以仅安装fluxcd下的helm-controller。然后，要是集成也同样是以addon方式来集成，在一定程度上也可以抽象的更简单。
> 
> ping @wangyikewxgm , we should add one more dependency type "definition", so the helm based addons won't depend on fluxcd, instead, they depend on the component-definition named "helm". After that, we can have addons such as "fluxcd", "argocd" or "helm-controller" in this issue.

In my opinion, this is one issue about encapsulation granularity.  If we choose less granularity , it will lead to lots of tiny addons. 
So my proposal is that add parameter for FluxCD addon to enable/disable its components by user. If user only need helm, he could only enable Helm-controller.

**Comment by cezhang** [comment]
> > > 在vela里使用helm，其实可以仅安装fluxcd下的helm-controller。然后，要是集成也同样是以addon方式来集成，在一定程度上也可以抽象的更简单。
> > 
> > 
> > ping @wangyikewxgm , we should add one more dependency type "definition", so the helm based addons won't depend on fluxcd, instead, they depend on the component-definition named "helm". After that, we can have addons such as "fluxcd", "argocd" or "helm-controller" in this issue.
> 
> In my opinion, this is one issue about encapsulation granularity. If we choose less granularity , it will lead to lots of tiny addons. So my proposal is that add parameter for FluxCD addon to enable/disable its components by user. If user only need helm, he just only enable Helm-controller.

I agree on your point of encapsulation granularity. Yes, the addon usually ships more functionality than what we needed while enabling the addon. But to some extend, this can not be avoided. As I  know, the fluxcd and argocd addon already  bring minimal burden for support helm. You can not easily ignore the "gitops" feature(pullInterval)  for example, when enable fluxcd to support helm, beacause this is how fluxcd works,  also as argocd. They work differently to support helm.  As @barnettZQG , abstraction is here in vela, vela adopts others, not try to modify them.

**Comment by wangyikewxgm** [comment]
As for fluxcd addon, I propose a  feature of dynamic enable a part of addon by parameter.For example `vela addon enable fluxcd onlyHelm=true` would only enable helm controller and source controller. Please note that parameter should be work with addon's resource sand definitions.

**Comment by wangyikewxgm** [comment]
Have submited a proposal https://github.com/kubevela/kubevela/issues/3822 to reduce the number of components of fluxcd addon by dynamic ignore parts of files by parameter. Please give some advice @StevenLeiZhang @cezhang

**Comment by oeular** [comment]
For the flexibility of the fluxcd addon for different scenarios, somethings want to be:
- when helm-controller is needed, only the related resources are needed to install, and at the most can be install with specified ns
- At the most, all controllers in fluxcd addon can be installed on their own according to the different scenarios

**Comment by wonderflow** [comment]
It's now supported in v1.5. 

```
vela addon enable fluxcd onlyHelmComponents=true
```

You can define addon with CUE and it's supported for defining parameter to decide parts of the controllers were installed.
