### ISSUE TITLE
Found 1 errors. [(download index file from https://addons.kubevela.net failure Get "https://addons.kubevela.net/index.yaml": x509: certificate is not valid for any names, but wanted to match addons.kubevela.net)]

### ISSUE THREAD

**Issue by xunfeng1980** [kubevela/kubevela#3782]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/8380489/165718650-d01f8d0b-361c-4a50-a26b-1ab794354fca.png)

**KubeVela Version**

1.3.2

**Cluster information**

- Kubernetes Version [1.22.3]

**Additional context**

**Comment by barnettZQG** [comment]
@xunfeng1980 could you check your network, such as:
```
curl https://addons.kubevela.net/index.yaml
```

**Comment by StevenLeiZhang** [comment]
Can your k8s access public internet?

**Comment by xunfeng1980** [comment]
多谢，找到问题了，公司解析的问题，把所有域名都解析到内网去了，导致证书不对，多谢。
