### ISSUE TITLE
The new addon can not shown in the Addons page

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#3795]
**Describe the bug**

The new addon can not be shown on the Addons page, this is a cache bug.

pkg/addon/cache.go#L89

**To Reproduce**

1. create a new addon in the addon registry.
2. View the addon page.

**KubeVela Version**

1.3.2

**Comment by StevenLeiZhang** [comment]
https://github.com/kubevela/kubevela/blob/99bb76a3fd2cf5467aa900e8ff4aa21e8d004440/pkg/addon/cache.go#L68
It seems that need wait 10 minutes for update

**Comment by wangyikewxgm** [comment]
Do we need to set sync interval smaller?

**Comment by wonderflow** [comment]
* for the new helm type addon registry, the sync duration could be in less than 10s.
* for the old type, please keep 10min.

**Comment by StevenLeiZhang** [comment]
Investigation:
It is caused by https://github.com/kubevela/kubevela/blob/7bfcd6acc52192d8cdb9ffa075b1b1d4e90b0d00/pkg/addon/cache.go#L89

It does not retrieve cached data from versionedRegistry cache

**Comment by StevenLeiZhang** [comment]
> * for the new helm type addon registry, the sync duration could be in less than 10s.
> * for the old type, please keep 10min.

I think 10min is ok for production scenario.
Only dev scenario needs less duration, because you are both platform admin, who push addon , and platform user, who use the addon.
