### ISSUE TITLE
[Feature] Add short name for application CRD 

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3797]
**Is your feature request related to a problem? Please describe.**

the core CRD (`applications.core.oam.dev`) of KubeVela has a short name  `app` or `application`, it will conflict with most of other open source projects, e.g. argocd.

**Describe the solution you'd like**

add a new short name for it, we can call it `velaapp` 

we just need to add a short name here: https://github.com/kubevela/kubevela/blob/master/apis/core.oam.dev/v1beta1/application_types.go#L85

```
// +kubebuilder:resource:categories={oam},shortName=app,velaapp
```

And run 

```
make reviewable
```

The command will automatically generate the CRD resources.

**Describe alternatives you've considered**

**Additional context**

This require al least manuel tests。

**Comment by fourierr** [comment]
It seems easy and i will do it.

**Comment by JarHMJ** [comment]
@wonderflow hi，I want to do this job.

**Comment by Somefive** [comment]
@JarHMJ Great!
