### ISSUE TITLE
'view query failed' on 1.3.1-8e8cd84 (same issue on updated version v1.3.3)

### ISSUE THREAD

**Issue by cloorc** [kubevela/kubevela#3799]
**Describe the bug**
1. Both container log/instances pod log will show the error: view query failed

**To Reproduce**
1. Install v1.3.1 on an existing Kubernetes cluster(1.20.2)
2. Enable velaux 1.3.1
3. Add a new application (wormhole, based on our private image)
4. Deploy to dev environment(namespace: develop)

**Expected behavior**
Can view the log about the specific Pod or Container.

**Screenshots**
![image](https://user-images.githubusercontent.com/13597105/166135725-e8951e00-6f79-488a-9b6c-b057e64e3733.png)

**KubeVela Version**
v1.3.1-8e8cd84 (Upgraded to v1.3.3 using Helm didn't solve the problem)

**Cluster information**
- Kubernetes version: v1.20.2

**Additional context**
1. velaux contains error: 
> 172.20.3.0 - - [01/May/2022:07:07:44 +0000] "GET /api/v1/query?velaql=collect-logs%7Bcluster%3Dlocal,+namespace%3Ddevelop,+pod%3Dwormhole-5d96dcb5df-9mgds,+container%3Dwormhole,+previous%3Dfalse,+timestamps%3Dtrue,+tailLines%3D3000%7D HTTP/1.1" 400 59 "https://privatedomain.io/applications/wormhole/envbinding/dev/instances" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36" "112.10.183.180"
2. apiserver contains log error:
> {"level":"error","ts":1651389062.5852134,"caller":"usecase/velaql.go:84","msg":"fail to query the view failed to query the view status.logs: from source","stacktrace":"github.com/oam-dev/kubevela/pkg/apiserver/rest/usecase.(*velaQLUsecaseImpl).QueryView\n\t/workspace/pkg/apiserver/rest/usecase/velaql.go:84\ngithub.com/oam-dev/kubevela/pkg/apiserver/rest/webservice.(*velaQLWebService).queryView\n\t/workspace/pkg/apiserver/rest/webservice/velaql.go:67\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:21\ngithub.com/oam-dev/kubevela/pkg/apiserver/rest/webservice.authCheckFilter\n\t/workspace/pkg/apiserver/rest/webservice/authentication.go:115\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/oam-dev/kubevela/pkg/apiserver/rest.(*restServer).requestLog\n\t/workspace/pkg/apiserver/rest/rest_server.go:230\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/emicklei/go-restful/v3.(*Container).OPTIONSFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/options_filter.go:15\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/emicklei/go-restful/v3.CrossOriginResourceSharing.Filter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/cors_filter.go:40\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/emicklei/go-restful/v3.(*Container).dispatch\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/container.go:282\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2047\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2425\ngithub.com/emicklei/go-restful/v3.(*Container).ServeHTTP\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/container.go:300\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2879\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1930"}

**Comment by barnettZQG** [comment]
@cloorc Can you view the logs on the Logs page?

**Comment by cloorc** [comment]
@barnettZQG Yes, please check this:

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13597105/166179720-fa1e0fdf-e69a-4dc4-96c5-2b174a1e3405.png">

**Comment by barnettZQG** [comment]
@cloorc thanks! This is a strange issue.

**Comment by cloorc** [comment]
> @cloorc thanks! This is a strange issue.

Could it be the RBAC rule issue? My applications were deployed in other namespace, such as `develop` or `test`. What should be the right `ClusterRole` for `kubevela`? I've only found a role named `kubevela-vela-core:leader-election-role`. Is it enough?

**Comment by wonderflow** [comment]
ping @barnettZQG , do we fix it in v1.5?

**Comment by barnettZQG** [comment]
@cloorc Please upgrade to v1.5.0 and retry.

**Comment by cloorc** [comment]
> @cloorc Please upgrade to v1.5.0 and retry.

Thanks! It works fine on v1.5.0.
