### ISSUE TITLE
[Feature] Should VelaUX admin initial password  be stored in the configmap

### ISSUE THREAD

**Issue by JarHMJ** [kubevela/kubevela#3803]
**Is your feature request related to a problem? Please describe.**

For some reason, the apiserver has been deleted and restarted, so the VelaUX admin initial password  cannot be found in the log.

**Describe the solution you'd like**

We should  store VelaUX admin initial password  in the configmap named "velaux-admin-password".

**Describe alternatives you've considered**

**Additional context**

**Comment by JarHMJ** [comment]
cc @barnettZQG @wonderflow @leejanee

**Comment by barnettZQG** [comment]
@JarHMJ The secret with name admin is exist in vela-system namespace.
