### ISSUE TITLE
The patchKey annotation of the strategy patch does not support multiple keys

### ISSUE THREAD

**Issue by Echo-Van** [kubevela/kubevela#3831]
When I define a trait, I want to use patchKey annotation to achieve the following effect:

- if a duplicated key is found, the patch data will be merge with the existing values;
- if no duplication found, the patch will append into the array list.

However, the value of envFrom is an array, and the key of each item are configMapRef.name or secretRef.name. I tried to do it using patchKey annotation, for example:

```
envfrom: {
  type: "trait"
  annotations: {}
  description: "ENV Ref"
  attributes: {
    podDisruptive: false
    appliesToWorkloads: ["*"]
  }
}
template: {

  patch: {
      spec: template: spec: {
          containers: [{
              // +patchKey=configMapRef.name
              // +patchKey=secretRef.name
              envFrom: [
                  {
                    configMapRef: {
                      name: parameter.cmname
                    }
                  },
                  {
                    secretRef: {
                      name: parameter.sename
                    }
                  }
              ]
          }]
      }
  }

  parameter: {
    sename: string
    cmname: string
  }
}
```

However, it does not take effect, the second patchKey will overwrite the first patchKey. If different Traits both patch the envFrom field, this will result in a key conflict.

**Comment by wonderflow** [comment]
It has been implemented in https://github.com/kubevela/kubevela/pull/3826
