### ISSUE TITLE
[Feature] run image scan CI for every pull request and fix CVEs in time

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3834]
**Is your feature request related to a problem? Please describe.**

Now we already have image scan in github action: https://github.com/kubevela/kubevela/blob/master/.github/workflows/codeql-analysis.yml#L9-L30

But it only run when PR is merged, this makes us don't catch CVEs in time.

**Describe the solution you'd like**

We should separate the image scan check out and run the check for every pull request like this:

https://github.com/oam-dev/docker-terraform/blob/master/.github/workflows/trivy-scan.yml#L7-L9

Along with this change, we should fix the CVEs found.

**Describe alternatives you've considered**

**Additional context**

**Comment by JarHMJ** [comment]
@wonderflow hi, I want to do this job.

**Comment by wonderflow** [comment]
> @wonderflow hi, I want to do this job.

great

**Comment by StevenLeiZhang** [comment]
patch 'RUN apk update && apk upgrade' to Dockfile, it will resolve most of CVE issues.
As you know, most of solutions of CVE issues is to upgrade OS libraries.
But, it will cost more time for image build

**Comment by wonderflow** [comment]
> 

Yeah, we have added the check for very pull request , it will remind us ASAP. Closing this issue.
