### ISSUE TITLE
[Bug]Failed to get trait list information

### ISSUE THREAD

**Issue by ZhongsJie96** [kubevela/kubevela#3841]
**Describe the bug**

Error parsing capability will appear when using `vela trait`
<img width="396" alt="image" src="https://user-images.githubusercontent.com/62382570/167453116-3b8ad42f-cb55-45e4-8a9f-dcb2b845bc62.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

```
CLI Version: 1.2.4
Core Version: 1.4.0-alpha.2
GitRevision: f6032f3de920a47d45c22146d374275a3676a815
GolangVersion: go1.17.6
```
**Additional context**

**Comment by barnettZQG** [comment]
Related issue: #3578

**Comment by wonderflow** [comment]
To fix this issue, we need to create x-definition yaml for these inner policies and traits. @ZhongsJie96

**Comment by ZhongsJie96** [comment]
> To fix this issue, we need to create x-definition yaml for these inner policies and traits. @ZhongsJie96

This bug may be caused by the definition of cue template

**Comment by ZhongsJie96** [comment]
> Related issue: #3578

Regarding issue #3578, since `json-merge-patch` is a relatively open trait, its parameters are empty and therefore cannot be edited temporarily. Is it possible to provide a general edit box for special processing, and `containers-image` cannot be displayed due to its complex parameter structure. I want to know how the front end takes parameter as the scheme.
