### ISSUE TITLE
DNS rebinding vulnerability found in etcd dependency

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3859]
| Package | Affected versions | Patched version | 
| -----| ---------------- | ------------ |
| go.etcd.io/etcd(Go) | < 3.4.0 | 3.4.0|

DNS rebinding vulnerability found in etcd 3.3.1 and earlier. An attacker can control his DNS records to direct to localhost, and trick the browser into sending requests to localhost (or any other address).

We need to upgrade the dependency.

**Comment by hzliangbin** [comment]
@wonderflow but latest version is [v3.3.27+incompatible](https://pkg.go.dev/go.etcd.io/etcd@v3.3.27+incompatible?tab=versions)

**Comment by wonderflow** [comment]
@hzliangbin  I  think `>3.3.1` is fine

**Comment by hzliangbin** [comment]
@wonderflow already fix by [commit](https://github.com/kubevela/kubevela/commit/967bc7786dece7f8c494220786ce6a5c84265dc6),  issue could be closed

**Comment by wonderflow** [comment]
@hzliangbin  Thanks
