### ISSUE TITLE
[Feature] vela addon status shows more detail info.

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#3860]
**Is your feature request related to a problem? Please describe.**

The command `addon status` showing info  is too simple which only shows the addon whether  has been enabled. We can show more detail info about this addon.

**Describe the solution you'd like**

These info must be showed.

1. The addon's readme witch tell user how to use this addon.
2. All available versions of this addon.
3. Dependency addon.
4. Available parameter of this addon.
5. If this addon is enabled show the setup parameter.

**Describe alternatives you've considered**

**Additional context**

**Comment by FogDong** [comment]
Similar issue: #3856

**Comment by wangyikewxgm** [comment]
> Similar issue: #3856

Not exactly. This proposal is want to show verbose info. The solution of #3836 should change the component type and add health check for it. let the mechanism of health check in application controller to tell the status of addon.

**Comment by StevenLeiZhang** [comment]
> 

Is these informations covered by "status" or we need another command, such as "view", "show", to print them?

**Comment by charlie0129** [comment]
Displaying the entire readme document in command line is probably hard to read.
Might just display addon description instead.

**Comment by StevenLeiZhang** [comment]
> Displaying the entire readme document in command line is probably hard to read. Might just display addon description instead.

I don't think description should be print by 'vela addon status', because it is not status. It should be print by 'vela addon show'

**Comment by charlie0129** [comment]
> I don't think description should be printed by 'vela addon status', because it is not status. It should be print by 'vela addon show'

Might also consider `vela addon info`, just like some widely used tools `brew info` or `apt info`.

And we can make `vela addon info` a synonym of `vela addon status`, which displays the same infomation.
