### ISSUE TITLE
[Feature] Add a "template" command to the vela cli

### ISSUE THREAD

**Issue by YourTechBud** [kubevela/kubevela#3865]
**Is your feature request related to a problem? Please describe.**
Its important to template out the k8s resources in the CI Pipeline to run tools like Datree for policy management. Currently there is a `vela dry-run` but it requires access to a k8s cluster (kube api server to be more precise). This isn't possible in most ci layers.

**Describe the solution you'd like**
A `vela template` command to spit out the k8s resources without requiring a kubeapi. We can provide it a directory containing all the trait and component definitions so it doesn't have to query kubernetes.

**Describe alternatives you've considered**
Dry run the resources and commit it in git alongside the application file. This isn't the best option.

**Additional context**

**Comment by wonderflow** [comment]
I think you can refactor the `vela dry-run` command , if the definition and other related things are provided, it can avoid access to K8s cluster.

**Comment by YourTechBud** [comment]
Let me try making the necessary modifications. Any help in directing me to the right file / function would be great

**Comment by wonderflow** [comment]
The basic code of vela dry-run is here: https://github.com/kubevela/kubevela/blob/master/references/cli/dryrun.go

The mechanism is read from K8s for Definition and other information, finally it will revoke the function same with the controller and do the rendering.

The work here is to avoid connect to K8s cluster, provide the basic information from local.
