### ISSUE TITLE
[Addon] integrate Pyroscope  for continueis profiling 

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3868]
**Is your feature request related to a problem? Please describe.**

Here's a demo about Pyroscope for continueis profiling:  https://www.infracloud.io/blogs/continuous-profiling-kubernetes-pyroscope/

The demo code: https://github.com/infracloudio/microservices-demo-dev

KubeVela didn't have such capability yet.

**Describe the solution you'd like**

We can make [pyroscope](https://github.com/pyroscope-io/pyroscope) as an [addon](https://github.com/kubevela/catalog/tree/master/addons). It can work as a trait for vela application and go through the demo automatically after the app deployed.

Besides the  `.net`, `python` and `Go` in the demo. We should provide language support for `Java` and `PHP`, that's can make it more popular.

**Describe alternatives you've considered**

**Additional context**

**Comment by oeular** [comment]
@wonderflow  Can the trait be used to vela components, such as velaux(especially apiserver), core and cluster-gw.
I think it can make vela better for system diagnose and observablility.

**Comment by wonderflow** [comment]
@oeular Of course, we should use it as dog food！

**Comment by oeular** [comment]
OK. we will work on this issue this month.

**Comment by fourierr** [comment]
+1，It's good way to diagnose the application

**Comment by fourierr** [comment]
supported by https://github.com/kubevela/catalog/pull/361
