### ISSUE TITLE
[Addon] rework for istio addon

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3870]
**Is your feature request related to a problem? Please describe.**

We used to have a canary-blue-green use case: https://kubevela.io/docs/case-studies/canary-blue-green/ .

After we have upgraded to new version of kubevela, this demo seems not working good and should be refactored for better usage.

**Describe the solution you'd like**

1. We need to re-work this addon, make the canary-blue-green demo work.
2. make istio as an official addon instead of experimental. https://github.com/kubevela/catalog/tree/master/experimental/addons/istio

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
It install as a helm chart, the helm capability is provided by fluxcd in kubevela. We can also change it to argocd, or deploy it in pure yaml without any dependency.

**Comment by kethavathsivanaik** [comment]
Will work on this, Need some suggestion.

**Comment by wonderflow** [comment]
> Will work on this, Need some suggestion.

Welcome! Ping @wangyikewxgm for more advice.

**Comment by wonderflow** [comment]
fixed by https://github.com/kubevela/catalog/pull/349
