### ISSUE TITLE
[Addon] integrate vegeta for Application benchmark report

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3872]
**Is your feature request related to a problem? Please describe.**

We can have some trait to do benchmark for vela application. Using the tools like: https://github.com/tsenart/vegeta

**Describe the solution you'd like**

1. build a K8s job for vegeta that can adopt app url as input and report the benchmark result.
2. create a vela addon about vegeta that including a trait or policy, or workflow step to run this benchmark and give the report.

**Describe alternatives you've considered**

**Additional context**

here's a blog of demo https://dev.to/ksingh7/the-most-elegant-way-to-performance-test-your-microservices-running-on-kubernetes-2mo2

**Comment by oeular** [comment]
It will extend the ability of the webservice or frontend service for user.

**Comment by oeular** [comment]
here is a demo：
apiVersion: batch/v1
kind: Job
metadata:
  name: vegeta
  namespace: vela-system
spec:
  parallelism: 10
  completions: 10
  backoffLimit: 0
  template:
    metadata:
      name: vegeta
    spec:
      containers:
      - name: vegeta
        image: quay.io/karansingh/vegeta-ubi
        command: ["/bin/sh","-c"]
        args: ["echo 'GET http://172.21.192.69:80' | vegeta attack -duration=60s -rate=0 -max-workers=64 | vegeta report ; sleep 600" ]
      restartPolicy: OnFailure

**Comment by oeular** [comment]
And the report is:
kubectl logs  vegeta--1-sv566  -n vela-system
Requests      [total, rate, throughput]         813, 13.52, 0.00
Duration      [total, attack, wait]             1m3s, 1m0s, 3.006s
Latencies     [min, mean, 50, 90, 95, 99, max]  1.061s, 4.799s, 3.006s, 8.016s, 9.018s, 20.987s, 30s
Bytes In      [total, mean]                     0, 0.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           0.00%
Status Codes  [code:count]                      0:813
Error Set:
Get "http://172.21.192.69:80": dial tcp 0.0.0.0:0->172.21.192.69:80: connect: no route to host
Get "http://172.21.192.69:80": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by oeular** [comment]
And the report is 
kubectl lgos   vegeta--1-k2klb  -n vela-system
E0527 11:10:05.609129   27262 run.go:120] "command failed" err="unknown command \"lgos\" for \"kubectl\"\n\nDid you mean this?\n\tlogs\n"
[root@yxl 5-25]# kubectl logs   vegeta--1-k2klb  -n vela-system
Requests      [total, rate, throughput]         1031645, 17193.84, 17193.63
Duration      [total, attack, wait]             1m0s, 1m0s, 732.324μs
Latencies     [min, mean, 50, 90, 95, 99, max]  69.751μs, 2.87ms, 2.409ms, 5.581ms, 6.819ms, 9.772ms, 28.846ms
Bytes In      [total, mean]                     634461675, 615.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           100.00%
Status Codes  [code:count]                      200:1031645
Error Set:

**Comment by oeular** [comment]
So maybe vegeta is just as a trait addon.

**Comment by wonderflow** [comment]
Yes, we can make it as a trait in the first step.

**Comment by fourierr** [comment]
https://github.com/kubevela/catalog/pull/359 supported
