### ISSUE TITLE
[Feature] create vela fig spec for CLI auto-completion

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3873]
**Is your feature request related to a problem? Please describe.**

Fig (https://fig.io/) adds IDE-style autocomplete to your existing terminal. We can create fig spec for vela CLI , so users using fig and vela can also enjoy this fast CLI experience.

**Describe the solution you'd like**

* Follow the guide to learn how to build customize spec  https://fig.io/docs/getting-started
* Send a PR to the main repo for vela spec, here're all examples: https://github.com/withfig/autocomplete/pulls
* show the demo for vela community here, add some docs

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
great @basuotian

**Comment by basuotian** [comment]
https://github.com/withfig/autocomplete/pull/1226

**Comment by wonderflow** [comment]
@basuotian  great!! 

Is there anything we need to do if the CLI is upgraded, can you help provide some developer guide for this.

**Comment by basuotian** [comment]
The autocomplete script need to be update if some subcommand or options of the CLI are changed.
I can provide a develper guide about how to maintain the autocomplete script, after the pr merged

**Comment by basuotian** [comment]
Thr pr has been merged, here is a demo
![vela-fig](https://user-images.githubusercontent.com/93654253/168975748-e3411b66-5c9c-4ede-8a85-882308032065.gif)

**Comment by wonderflow** [comment]
@basuotian wow, great, please add some docs about how to use and maintain it.

**Comment by basuotian** [comment]
## Installation
- Homebrew: brew install --cask fig
- DMG: Download from our website: [fig.io](https://fig.io/welcome)

## Maintain

- fork this git repo [withfig/autocomplete](https://github.com/withfig/autocomplete)
- Clone your forked repo
```
# Replace `YOUR_GITHUB_USERNAME` with your own github username
git clone https://github.com/YOUR_GITHUB_USERNAME/autocomplete.git fig-autocomplete
cd fig-autocomplete

# Add withfig/autocomplete as a remote
git remote add upstream https://github.com/withfig/autocomplete.git

# Install packages
npm install
```

- edit vela-cli spec in `src/vela.ts`, the spec is easy to understand 
- run dev mode to review your change, use `npm run dev`
- send a PR to the main repo

**Comment by wonderflow** [comment]
@basuotian Great, please add to our developer guide https://kubevela.net/docs/contributor/cli-ref-doc

![image](https://user-images.githubusercontent.com/2173670/184067801-fd927528-1904-4876-b987-71ba2d0ca044.png)
