### ISSUE TITLE
vela port-forward not working for webservice component

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3885]
**Describe the bug**

I have deployed an app like below:

```
$ kubectl get app nginx -o yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  components:
  - name: nginx
    type: webservice
    properties:
      image: nginx
      ports:
      - expose: true
        port: 80
        protocol: TCP
    traits:
    - properties:
        replicas: 1
      type: scaler
```

It has ports specified in component properties.

But the command `vela port-forward` report an error.

```
$ vela port-forward nginx
? You have 2 deployed resources in your app. Please choose one: Cluster: local | Namespace: default | Kind: Service | Name: nginx
Error: no port found in app or arguments
```

**To Reproduce**

Apply the yaml above and run 

```
vela port-forward nginx
```

**Expected behavior**

Hope there can be normal port-forward

**Screenshots**

**KubeVela Version**

latest version

**Additional context**

The reason is the port-forward use hard-code way to check the properties:

![image](https://user-images.githubusercontent.com/2173670/168251323-0f75f25e-5fca-435a-a583-676ee938a4bf.png)

But we have upgrade the fields from `port` to `ports` for `webservice` component.

We need to fix the incompatible in CLI .

**Comment by barnettZQG** [comment]
Correct usage:
```
$ vela port-forward nginx 8080:80 
```
There is no valid validation of the parameters
