### ISSUE TITLE
[Feature] Provide the ability to monitor all the components of vela

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#3887]
For now, all the components of the vela is deployed in ONE hub-cluster, so the hub-cluster is a must to provide more high SLA.
- The apiserver and the core controller are needed to monitored with some metrics, e.g: cpu, memoery, netIO, diskIO and QPS and etc
- The components of the hub-cluster are needed to monitored, e.g: etcd, k8s-apiserver, controller-manager, scheduler and kubelet
- And more, the core (maybe all) call-trace among the velaux, the apiserver, the core-controller and the cluster-gw is needed to monitor

**Comment by wonderflow** [comment]
@Somefive is working on part of this issue.

**Comment by wonderflow** [comment]
all metrics addons are available now in the catalog, please refer to https://github.com/kubevela/kubevela.io/pull/882. 

I'm going to close this issue, feel free to create a new one if there's new features request.
