### ISSUE TITLE
[Feature] Configmap not corrected mounted when deployment and configmap are updated together  

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#3888]
**Is your feature request related to a problem? Please describe.**

Though we have dependencies across different components, there are still resource problems along within one component.

For example, if we have one deployment as the main workload of a component, then we use ConfigMap as a trait to mount. If we update the deployment and the configmap at the same time, the configmap might be updated after deployment pod is created. In this case, the deployment pod will use the old configmap data.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by barnettZQG** [comment]
Whether we need to intelligently sort the resources delivered by the same component is an open question. However, we need to ensure the atomicity of application updates.

**Comment by ZhongsJie96** [comment]
I think this proposal is great, we also face that dependency order when using the same Secret.

**Comment by ZhongsJie96** [comment]
To solve this problem, is it possible to rebind a ConfigMap after the configuration content changes, which can fundamentally solve the problem of dependency order, but it will face the complexity of resource recovery in the implementation process.
