### ISSUE TITLE
[Addon] integrate Netlify as an addon

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3892]
**Is your feature request related to a problem? Please describe.**

Netlify is a SaaS platform that can serve website especially for frontend service, it provides free allowances that was pretty cool to be used for demo and test. We can create an addon which provides a netlify component type for frontend service.

**Describe the solution you'd like**

The general architecture could be like below:

![image](https://user-images.githubusercontent.com/2173670/168455000-eba4fefd-a305-432d-846a-04e505610c44.png)

1. We should build a container image which contains a deploy script for lauching netlify app. You can refer to [the netlify script by dagger](https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/netlify/deploy.sh).
2. [Define a component defintion](https://kubevela.io/docs/platform-engineers/cue/definition-edit) to launch a K8s job for running this container. 
3.  Register Netlify account and create your personal access token in netlify for test, it provides free allowances:

![image](https://user-images.githubusercontent.com/2173670/168455109-b6de6fcf-6e99-48c8-928c-03ff9f47d632.png)

4. Expose the information in vela status by using [velaql](https://kubevela.io/docs/platform-engineers/system-operation/velaql).
5. After this process working successfuly, [build an addon](https://kubevela.io/docs/platform-engineers/addon/intro) into [catalog](https://github.com/kubevela/catalog) with a demo readme, the demo is necessary.

**Describe alternatives you've considered**

**Additional context**

**Comment by oeular** [comment]
It‘s a nice addon.’

**Comment by oeular** [comment]
I have a try for this issue. The k8s job is described like this.
apiVersion: batch/v1
kind: Job
metadata:
  name: netlify
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 10
  template:
        metadata:
          name: netlify
        spec:
          containers:
          - name: netlify
            image: an-image:latest
            env:
            - name: SITE_NAME
              value: deploy-from-k8s
            - name: TOKEN
              value: your-token
            - name: REPO_NAME
              value: oeular.github.io
            - name: GIT_REPO
              value: https://github.com/oeular/oeular.github.io.git			  
          restartPolicy: OnFailure

**Comment by oeular** [comment]
And the result is like this.
[root@yxl-abc ~]# kubectl create ns netlify
namespace/netlify created
[root@yxl-abc ~]# kubectl apply -f deploy-by-netlify.yaml -n netlify
job.batch/netlify created
[root@yxl-abc ~]# kubectl get po -n netlify --watch=true
NAME            READY   STATUS    RESTARTS   AGE
netlify-n67xq   1/1     Running   0          27s
netlify-n67xq   0/1     Completed   0          38s
^C[root@yxl-abc ~]# kubectl logs netlify-n67xq -n netlify
update repo...
Cloning into 'oeular.github.io'...
update repo successfully
------------
Site deploy-from-k8s does not exist
clean create site API response...
e8ee7d2e-ce27-44a1-b680-92be7daf4819 exists, going to update the website
Site already linked to "lala-website"
Admin url: https://app.netlify.com/sites/lala-website

To unlink this site, run: netlify unlink

? Initial build environment
cwd: /
featureFlags: []
mode: cli
siteId: e8ee7d2e-ce27-44a1-b680-92be7daf4819

? UI build settings
baseRelDir: false

? Resolved build environment
branch: master
buildDir: /
context: production
env:
  - DEPLOY_ID
  - BUILD_ID
  - NETLIFY_LOCAL
  - HEAD
  - PULL_REQUEST
  - LANG
  - LANGUAGE
  - LC_ALL
  - GATSBY_TELEMETRY_DISABLED
  - NEXT_TELEMETRY_DISABLED

? Resolved config
build:
  publish: /
  publishOrigin: default

────────────────────────────────────────────────────────────────
  Netlify Build
────────────────────────────────────────────────────────────────

? Version
  @netlify/build 27.1.3

? Flags
  debug: true
  mode: cli

? Current directory
  /

? Config file
  No config file was defined: using default values.

? Resolved config
  build:
    publish: /
    publishOrigin: default

? Context
  production

────────────────────────────────────────────────────────────────
  Netlify Build Complete
────────────────────────────────────────────────────────────────

(Netlify Build completed in 13ms)
Deploy path: /oeular.github.io
Deploying to main site URL...
- Hashing files...
? Finished hashing
- CDN diffing files...
? CDN requesting 0 files
- Uploading 0 files
? Finished uploading 0 assets
- Waiting for deploy to go live...
? Deploy is live!

Logs:              https://app.netlify.com/sites/deploy-from-k8s/deploys/62a381466f744377a3e7c2a5
Unique Deploy URL: https://62a381466f744377a3e7c2a5--deploy-from-k8s.netlify.app
Website URL:       https://deploy-from-k8s.netlify.app

**Comment by wonderflow** [comment]
You should be able to exposte the URL for `vela status`

**Comment by wonderflow** [comment]
closing as we already have this addon https://github.com/kubevela/catalog/tree/master/addons/netlify
