### ISSUE TITLE
Improve `vela provider add` response

### ISSUE THREAD

**Issue by alisson276** [kubevela/kubevela#3936]
**Describe the bug**

When calling `vela provider add` twice or more times, the error message is generic and only says `Error: failed to authenticate Terraform cloud provider terraform-<provider>`. The error should be passed back to the CLI. In the case you run it more than once, the `err` on https://github.com/kubevela/kubevela/blob/master/references/cli/provider.go#L194 is `terraform provider <name> for terraform-<provider> already exists` (I've added an `ioStreams.Infof("%s\n", err.Error())` to see it), what is much more specific than "failed to authenticate".

**To Reproduce**

```
vela addon enable terraform
vela addon enable terraform-azure
vela provider add terraform-azure --ARM_CLIENT_ID $ARM_CLIENT_ID --ARM_CLIENT_SECRET $ARM_CLIENT_SECRET --ARM_SUBSCRIPTION_ID $ARM_SUBSCRIPTION_ID --ARM_TENANT_ID $ARM_TENANT_ID --name azure-personal
```

It will return Sucessful if correct authenticate, but if you run again the provider add it will say "wrong credentials", what is not an accurate message.

**Expected behavior**

Receive an:
`Error: terraform provider azure-personal for terraform-azure already exists`

**Screenshots**

**KubeVela Version**

1.3.4

**Cluster information**

**Additional context**

**Comment by StevenLeiZhang** [comment]
my proposal:
1.  `vela provider add ` does not return any details, it is just "add" operation, which means store the config to databases. It does not care the status of provider
2. add `vela provider status` command to check the status and result. If the provider is in abnormal status, it prints error details.
