### ISSUE TITLE
vela reports error when apply configmap: annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3938]
**Describe the bug**

> Vela在apply一个Grafana面板的configmap的时候，有“metadata.annotations: Too long: must have at most 262144 bytes”的报错；这个用kubectl提交可以用kubectl replace去workaround

When submit a grafana configmap by using kubevela, it reports “metadata.annotations: Too long: must have at most 262144 bytes”.

This is also a common issue in kubectl, but we can use `kubectl replace` to workaround, in kubevela, how can I fix that?

**To Reproduce**

Write an application with long configmap nested by using `ref-objects` component type.

**Expected behavior**

We can have any work around to update the object.

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by linktimecloud** [comment]
### 测试样例
[test-huge-dashboards.zip](https://github.com/kubevela/kubevela/files/8735649/test-huge-dashboards.zip)

* 先 `vela def apply dashboard.cue`
* 再 `kubectl apply -f dashboard.yaml`

**Comment by linktimecloud** [comment]
抱歉YAML文件有格式问题，请用这个：
[test-huge-dashboards.zip](https://github.com/kubevela/kubevela/files/8735833/test-huge-dashboards.zip)
