### ISSUE TITLE
Wrong version check for EKS clusters

### ISSUE THREAD

**Issue by s4rd1nh4** [kubevela/kubevela#3950]
**Describe the bug**

Wrong version check for EKS clusters.

`version v1.21.9-eks-14c7a48 require: >=v1.19`
**To Reproduce**

Set in metadata.yaml any kubernetes version check.
```
system:
  kubernetes: ">=v1.19"
```
From EKS cluster run `vela addon enable <addon>`.

**Expected behavior**

Addon installed.

**Screenshots**

<img width="705" alt="image" src="https://user-images.githubusercontent.com/26822325/169708124-f19f8f95-fdb4-41b9-a52e-b5d3d282d5b4.png">

**KubeVela Version**
v1.21.9

**Cluster information**

**Additional context**

**Comment by StevenLeiZhang** [comment]
v1.21.9-eks-14c7a48  does not follow the standard https://semver.org/

**Comment by diego-milhomes** [comment]
Tks @StevenLeiZhang , in this case, if it's not the semver version it should skip the kubernetes version check?
https://github.com/kubevela/kubevela/blob/eb5f416e4e264513e3fa7358a9795b378b29048d/pkg/addon/addon.go#L1398-L1411

**Comment by s4rd1nh4** [comment]
Tks @StevenLeiZhang , in this case, if it's not the semver version it should skip the kubernetes version check?
https://github.com/kubevela/kubevela/blob/eb5f416e4e264513e3fa7358a9795b378b29048d/pkg/addon/addon.go#L1398-L1411

**Comment by wonderflow** [comment]
@s4rd1nh4 agree If we don't have better way
