### ISSUE TITLE
Terraform provider "add" doesn't work using v1.3.5

### ISSUE THREAD

**Issue by alisson276** [kubevela/kubevela#3955]
**Describe the bug**

It seems that the current CRDs (or other thing) from master are different of those are in use on the v1.3.5.

**To Reproduce**

`vela provider add terraform-azure --ARM_CLIENT_ID $ARM_CLIENT_ID --ARM_CLIENT_SECRET $ARM_CLIENT_SECRET --ARM_SUBSCRIPTION_ID $ARM_SUBSCRIPTION_ID --ARM_TENANT_ID $ARM_TENANT_ID --name <some-name>` returns 
```
Error: failed to authenticate Terraform cloud provider terraform-azure
```

**Expected behavior**

Message `Successfully authenticate provider azure-personal for terraform-azure`

**Screenshots**

**KubeVela Version**

CLI Version: 1.3.5
Core Version: 1.3.5
GitRevision: cbed2b5cb3371b48357dbda3b5fc278a506c4d70
GolangVersion: go1.18.2

**Cluster information**

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9+k3s1", GitCommit:"8b0b50a5e88214f69e4ef35ebfd60c6adac9735f", GitTreeState:"clean", BuildDate:"2022-04-28T22:46:07Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

I've cloned the repo and made a little debug:
```
diff --git a/references/cli/provider.go b/references/cli/provider.go
index 2bdc09c8..d483ed60 100644
--- a/references/cli/provider.go
+++ b/references/cli/provider.go
@@ -192,6 +192,7 @@ func prepareProviderAddSubCommand(c common.Args, ioStreams cmdutil.IOStreams) ([
                                }

                                if err := config.CreateApplication(ctx, k8sClient, name, providerType, string(data), config.UIParam{}); err != nil {
+                                       ioStreams.Infof("%s\n", err.Error())
                                        return fmt.Errorf(errAuthenticateProvider, providerType)
                                }
                                ioStreams.Infof("Successfully authenticate provider %s for %s\n", name, providerType)
```

When doing checkout to v1.3.5, running `make vela-cli` and using this to run `provider add` it returns me `no kind is registered for the type v1beta1.ProviderList in scheme "pkg/runtime/scheme.go:100"`. If I do a checkout to master again and build the application I got no error when calling the same command, receiving that it was successfully registered.

**Comment by alisson276** [comment]
Even after having the provider successfully created using kubevela from `master` instead of `v1.3.5` I receive an error when listing the providers from vela CLI:
```
$ vela provider list
Error: failed to retrieve providers: no kind is registered for the type v1beta1.ProviderList in scheme "pkg/runtime/scheme.go:100"
```

If I use my compiled version from master I got the correct result:
```
$ bin/vela provider list
TYPE           	NAME          	CREATED-TIME
terraform-azure	azure-personal	2022-05-23 10:07:01 +0100 WEST
```

**Comment by zzxwill** [comment]
@alisson276 Thanks for reporting the problem. @barnettZQG has fixed it in master per https://github.com/kubevela/kubevela/pull/3878/files#diff-34b55c11ab5300d3a9d50547854bd984e45aa35cacc4b1289221bddb717502c6. 
I am fixing it for v1.3.5.
