### ISSUE TITLE
[Addon] Integrate trivy for security scan trait

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#3957]
**Is your feature request related to a problem? Please describe.**

Trivy has announced some new features in kubecon EU: https://blog.aquasec.com/trivy-cloud-native-security-scanner

I think we can Integrate it as KubeVela addon for  following scenarios:

1. A trait that can scan pod in development environment and report the results, leveraging the `Kubernetes security scanning` capability from trivy.
2. A policy that scan IaC Yaml in workflow before real deploy.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oeular** [comment]
Here I propose an addon. https://github.com/kubevela/catalog/pull/380#issue-1270753555

**Comment by wonderflow** [comment]
supported now https://github.com/kubevela/catalog/tree/master/addons/trivy-operator

Thanks to @oeular and @FogDong
