### ISSUE TITLE
[Feature] support multiple drivers application gateway rule management

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#3983]
**Is your feature request related to a problem? Please describe.**

In the Kubernetes ecosystem, there are two most widely used application north-south traffic (gateway) management APIs, namely Ingress and [Gateway API](https://github.com/kubernetes-sigs/gateway-api). 

The Ingress mainly covers the HTTP protocol, and the Kubernetes SIG currently drives the latter in order to implement a standard API for more protocol traffic management. 

KubeVela is an application delivery platform. Its advantage is that it can integrate APIs of similar requirements downward and is compatible with different implementations; it provides users with a unified management process and experience upwards. 

**Describe the solution you'd like**

In this topic, a set of gateway management functions compatible with multiple load balancers can be developed based on Ingress and Gateway API, so that users do not need to change the traffic management policy configuration when deploying applications in different environments with different gateway implementations.

* Based on the Ingress API needs to support the Nginx, Istio, Traefik, Aliyun CLB etc.
* Based on the Gateway API needs to support the Istio, Traefik, Kong etc. 

**Additional context**

[The Traefik addon](https://github.com/kubevela/catalog/tree/master/addons/traefik) is an example.

Refer to https://github.com/kubernetes-sigs/gateway-api/pull/1131

**Comment by sbdtu5498** [comment]
@barnettZQG, I am really interested in this project, If you permit I would like to draft a proposal for the issue to participate in ASoC 2022.

**Comment by sbdtu5498** [comment]
@barnettZQG, Sir I am really interested in this issue and if you permit, I would like to draft a proposal for the issue to participate in ASoC 2022. I have sent you a message on CNCF Slack as well to introduce myself properly. Also, as the last date of proposal submission is approaching, I would be grateful if you can answer at the earliest.
