### ISSUE TITLE
🏕 Alibaba Summer of Code (ASOC) 2022

### ISSUE THREAD

**Issue by BinaryHB0916** [kubevela/kubevela#3997]
Welcome to the open-source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and code with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open-source project and work with the core members of the project.

This is a master issue to track the progress and result of [Alibaba Summer of Code 2022](https://opensource.alibaba.com/asoc2022).

### 🎊 What you can get?
On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation
- Get a scholarship from Alibaba
- Obtain an open-source contributor certificate
- Get a fast pass of Alibaba Internship
- Get your code adopted and used by the open-source project！

### 👨‍🏫 Our Mentor
Qingguo Zeng (@[barnettZQG](https://github.com/barnettZQG) ), Maintainer, Core member of KubeVela community.
Da Yi (@[Somefive](https://github.com/Somefive) ), Approver, Core member of KubeVela community.
Zhengxi Zhou (@[zzxwill](https://github.com/zzxwill)), Maintainer, Core member of KubeVela community.

### ⏱ Timeline
![image](https://user-images.githubusercontent.com/57997154/170422231-3d1ea27d-b353-480a-848f-6b145928719d.png)

### 🚀 Apply Now!
1.Browse open idealist here:
- [support multiple drivers application gateway rule management](https://github.com/kubevela/kubevela/issues/3983)
- [System Info & Diagnose](https://github.com/kubevela/kubevela/issues/3924)
- [Build static site and serve it on OSS](https://github.com/kubevela/kubevela/issues/3898)

2.Upload your CV and project proposal via ASOC 2022 official website

### 🐚 Contact the Organizer

If you have any questions, visit the event website:  https://asoc2022.opensource.alibaba.com/

You can also comment on this issue or send us an email: [opensource@alibaba-inc.com](mailto:opensource@alibaba-inc.com)

**Comment by wonderflow** [comment]
closing as the program is finished
