### ISSUE TITLE
[Feature] Add the web shell API

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4052]
**Is your feature request related to a problem? Please describe.**

There are three basic ways to troubleshoot the application delivery process.

* Pod Status
* Logger
* Remote Shell.

Currently, Pod Status and Logger are already supported in the API server. Remote Shell is ready in vela CLI, and it is running via the cluster gateway.

We should add a secure web shell API and support the web terminal. refer to https://github.com/yudai/gotty

**Comment by oeular** [comment]
It will be like this ?
velaux-ui ----> the web shell api: gotty --port 90 <vela command>, and the gotty will be as another endpoint for velau-ui

**Comment by barnettZQG** [comment]
@oeular 

The web shell API should upgrade to the WebSocket protocol, and reuse the existing endpoint.
