### ISSUE TITLE
通过VelaUX扩展能力进行操作启用禁用都不生效

### ISSUE THREAD

**Issue by SQGE** [kubevela/kubevela#4098]
![image](https://user-images.githubusercontent.com/30278569/171543195-df562d68-9ab5-4187-9112-d74ec86e9f30.png)

### KubeVela Version

```
CLI Version: v1.4.0
Core Version: 1.4.0
GitRevision: git-8f7a825
GolangVersion: go1.17.10
```

**Comment by barnettZQG** [comment]
@SQGE The reason for this issue is that the query list is preferentially got from the cache, After the definition status changes, it will delay entering the cache. In fact, it has already been changed.
