### ISSUE TITLE
Can't upgrade to 1.4.0 using both vela install or helm upgrade

### ISSUE THREAD

**Issue by rgaoistheone** [kubevela/kubevela#4102]
**Describe the bug**
Can't upgrade to 1.4.0 using both vela install or helm upgrade

**To Reproduce**
```
vela install --version v1.4.0
```
![image](https://user-images.githubusercontent.com/5696899/171550605-f15cd7a8-00f1-47db-9080-6ebc4c036605.png)
```
helm rollback -n vela-system 
vela install --set multicluster.clusterGateway.image.tag=v1.4.0
```
And got this error:
![image](https://user-images.githubusercontent.com/5696899/171550544-975f521c-61f3-4b71-8daa-57815a1086c0.png)

And then try to upgrade by helm upgrade
```
helm upgrade kubevela kubevela/vela-core --set multicluster.clusterGateway.image.tag=v1.4.0 -n vela-system
```
But got errors from vela-core like:
`
I0602 03:41:02.514359       1 utils.go:134] waiting for cluster gateway service: ClusterGateway APIService v1alpha1.cluster.core.oam.dev is not found
`

**Expected behavior**

**Screenshots**

**KubeVela Version**
client 1.4.0
server 1.3.0

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
@rgaoistheone 

Can you try the 1.4.1 version? This issue is fixed by #4092

```
# Upgrade the vela CLI
$ curl -fsSl https://kubevela.net/script/install.sh | bash -s 1.4.1

# Upgrade the vela Core
$ vela install --version v1.4.0
```

**Comment by barnettZQG** [comment]
If the upgrade process is terminated abnormally, the system prompts you to wait 18 minutes for the next upgrade. You can delete the release with the status `pending-install` or `pending-upgrade` or `pending-rollback`.

```
$ k get secret -l owner=helm,name=kubevela -n vela-system -o custom-columns="NAME:.metadata.name,DATA:.metadata.labels"
```

**Comment by rgaoistheone** [comment]
> If the upgrade process is terminated abnormally, the system prompts you to wait 18 minutes for the next upgrade. You can delete the release with the status `pending-install` or `pending-upgrade` or `pending-rollback`.
> 
> ```
> $ k get secret -l owner=helm,name=kubevela -n vela-system -o custom-columns="NAME:.metadata.name,DATA:.metadata.labels"
> ```

Thanks to @barnettZQG , finally got it fixed. Much appreciated !
