### ISSUE TITLE
use mongoDB datastorage to integration sso fail

### ISSUE THREAD

**Issue by fengkang01** [kubevela/kubevela#4104]
**Describe the bug**

我希望使用dex插件集成ldap来实现单点登录的功能，按照官方的文档进行配置并已经将admin账号的邮箱设置为和ldap账号邮箱相同
当使用ldap中和admin配置的邮箱相同的账号登录时，并没有继承原本的admin的,并且在登出再次登录同样的账号时页面显示“data record is exist”，但是我将存储方式改为kubeAPI后则可以正常的使用并可以继承原本本地账号的权限

I hope use dex addon integration ldap to implementa sso function,i had config admin account email same as ldap account.When i login ,this account not inheritance the local admin account permissions,and when i login by same account again ,the page display "data record is exist",but when i change the datastorage to kubeapi,all thing become right .

**To Reproduce**

**Expected behavior**

使用ldap账号可以登录kubevela并且相同邮箱的账号可以继承本地账号的权限
use ldap account login kubevela and the same email account can inheritance the permissions
**Screenshots**

<img width="1068" alt="企业微信截图_16540766817109" src="https://user-images.githubusercontent.com/103910304/171575999-8f73c0a8-6614-4dca-8e39-45f6d501696b.png">

<img width="331" alt="企业微信截图_16540817044590" src="https://user-images.githubusercontent.com/103910304/171575615-1f36b5d1-82de-4426-8729-8b2924201bb3.png">

**KubeVela Version**
kubevela core 1.4.0
kubevela cli 1.4.0
velaux 1.4.0

**Cluster information**

docker info
```
Client: Docker Engine - Community
 Version:           20.10.16

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
```
kubernetes info
```
Kubernetes v1.21.0
```
mongoDB
```
mongo:4.2.9
```

**Additional context**

**Comment by FogDong** [comment]
That's because we replace some symbols like `@` to `-` to meet the requirement of `kubeapi`, see the code here: https://github.com/kubevela/kubevela/blob/master/pkg/apiserver/domain/model/user.go#L76

But in mongoDB, we shouldn't do the replacement.
