### ISSUE TITLE
[Feature] Show component health status in graph view

### ISSUE THREAD

**Issue by h7kanna** [kubevela/kubevela#4106]
**Is your feature request related to a problem? Please describe.**
Need component health status in Graph view

**Describe the solution you'd like**
Display Healthy status in graph view of the components in addition to the Overview tab (Green dots)

**Describe alternatives you've considered**
Use Overview tab

**Additional context**

**Comment by h7kanna** [comment]
Oops may be duplicate of https://github.com/kubevela/velaux/issues/536

**Comment by wonderflow** [comment]
Closing, it's dup with https://github.com/kubevela/velaux/issues/536, and please refer to https://github.com/kubevela/velaux/pull/615
