### ISSUE TITLE
[Feature] support archive addon as a helm chart that can be installed by `helm install`

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4116]
**Is your feature request related to a problem? Please describe.**

We must use `vela addon enable` to install an addon, while it seems everything can be done by using `helm install` ?

We add  burden to end user that they must know the concept of addon.

**Describe the solution you'd like**

1. Add a `vela addon archive` command that can convert current addon to a helm chart, which can be uploaded to the chart museum.
2. The helm chart addon will deploy by `helm install` into the control plane cluster. It leverages application controller for multi-cluster delivery just like what it works now. Anything that only need to be installed in the control-plane should just be yaml files in the chart while resources need to be delivered into multi-clusters should be in the application yaml.
3. The rest thing can be aligned with helm chart, such as Notes.txt, parameters.cue(values.yaml), etc.

**Describe alternatives you've considered**

The currunt solution use `vela addon` command for installation, actually we are building a new wheel which is no better.

**Additional context**

Hope there's some unique features that make `vela addon enable` a necessary thing. In this case, `vela addon archive` is necessary as it converts cue into helm charts. \cc @wangyikewxgm 

## What makes this issue?

* #4114 seems just a Notes.txt in helm chart but we're rebuilding in the addon system.
* #3822 helm chart already solves this by it's go templating 
* #3905 we wrap all the things in the addon and deploy them without thinking, if addon align with helm chart and it contains an application inside, everything become clear.
* #3891  helm chart also has this issue with a solution that uses label check.
* #3692 same issue with helm

We MUST solve this before any progress of addon framework.

## What Values Addon should ADD?

Any feature as a package management tool, the addon should be aligned with Helm. So addon can hardly add values besides:

1. Automation: convert a helm chart into an addon by automatically detect the CRD controller and add OAM Definition for it.
2. Glue/Orchestration: addon can provide an abstraction layer for the real Implementation, which means one addon can depends on another addon which can be different implementation( different helm charts).

**Comment by wangyikewxgm** [comment]
I propose add "vela addon create create" subcommand in cli for user to generate a addon scaffold base  a helm chart's url
eg: run `vela addon create mongodb --helm-repo-url=https://marketplace.azurecr.io/helm/v1/repo  --helm-chart=mongodb --version=12.1.16`  

this command will generate a dir along with base files of an adddon, eg:

```
mongodb/
├──  metadata.yaml   
├── template.yaml    
└── definitions/    
└── resources/    
    └── mongodb.cue  
```

And the mongodb.cue is:
```cue
output: {
        type: "helm"
        properties: {
                repoType: "helm"
                url:      "https://marketplace.azurecr.io/helm/v1/repo"
                chart:    "mongodb"
                version:  "12.1.16"
        }
}
```

By doing this, would help user create an addon more quickly.

**Comment by StevenLeiZhang** [comment]
"vela addon package" command is already done by https://github.com/kubevela/kubevela/pull/3787. It package addon directory to Helm Chart package.

**Comment by StevenLeiZhang** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> We must use `vela addon enable` to install an addon, while it seems everything can be done by using `helm install` ?
> 
> We add burden to end user that they must know the concept of addon.
> 
> **Describe the solution you'd like**
> 
> 1. Add a `vela addon archive` command that can convert current addon to a helm chart, which can be uploaded to the chart museum.

This feature is partly implemented by https://github.com/kubevela/kubevela/pull/3787
"vela addon package" command is already done by https://github.com/kubevela/kubevela/pull/3787. It package addon directory to Helm Chart package.

**Comment by wonderflow** [comment]
The conclusion is kubevela addon has more features than helm, it already packaged as helm chart but it must be installed by vela command line to make the features work.

Closing.
