### ISSUE TITLE
doc of installation for windows not working with 1.4.1

### ISSUE THREAD

**Issue by oudi** [kubevela/kubevela#4127]
**Describe the bug**

install in Windows 10 in a pure evnironment. according to the doc https://kubevela.io/docs/install , there are some practices not fit with the doc. But kubevela running successfully(with other commands instead).

* There is no velad.exe under C:\vela after install powershell script. use `vela install` works. 
    * powershell not under administrator
* `vela addon enable ~/.vela/addons/velaux` shows `Error: addon: ~/.vela/addons/velaux not found in registries`, use `vela addon enable velaux` works.
    * there exists a .vela folder in the current user's home location. there are two folder names capabilities, centers under .vela .
    * I created addons folder under .vela but the Error persists when re run above command.

**Screenshots**

![image](https://user-images.githubusercontent.com/2518192/172514395-695054ae-8459-4e23-923d-1827ca9a7f74.png)

**KubeVela Version**

CLI Version: v1.4.1
Core Version:1.4.1
GitRevision: git-ea0508a
GolangVersion: go1.17.10

**Cluster information**

Rancher Desktop 1.3.0 [K3s]
Windows 10

**Comment by StevenLeiZhang** [comment]
Please refer to  https://github.com/kubevela/velad/releases。 Velad seems do not work on windows。So need update doc to clarify it.

**Comment by oudi** [comment]
download velad-v1.4.1-windows-amd64.zip and unzip under c:\vela, copy velad under windows-amd64 to parent path named velad.exe,  there has an error when run `velad install`

```
Preparing K3s images...
Successfully prepare k3s image:  C:\Users\oudi\.vela\velad\k3s\k3s-airgap-images-amd64.tgz
Successfully prepare k3d images
Loading k3d images...
Error: Fail to set up cluster: failed to setup k3d: failed to extract k3d images: exec: "gzip": executable file not found in %PATH%
```
seems it need gzip which is not installed and included in windows's path.

But I think there is no need velad(vela in k3d?) because vela detected my k3s cluster and runs sucessful. closed!

**Comment by chivalryq** [comment]
Script has been fixed here: https://github.com/kubevela/kubevela.io/pull/710

VelaD support Windows. 

We are using gzip in terminal PATH, maybe it should be replaced with a Go lib.
