### ISSUE TITLE
[Feature] vela def support list version and get detail for definition revision

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4131]
**Is your feature request related to a problem? Please describe.**

We have version control for definition, but they can only be used by `kubectl` which is not unified with `vela` cli.

https://kubevela.io/docs/platform-engineers/x-def-version

**Describe the solution you'd like**

I propose we should align with `vela def` command:

1. list versions
```
$ vela def get webservice --versions
NAME            REVISION   HASH               TYPE
webservice-v1   1          3f6886d9832021ba   Component
webservice-v2   2          b3b9978e7164d973   Component
```

2. get detailed parameters with specified version

```
$ vela show webservice --version=v1
```

**Describe alternatives you've considered**

**Additional context**

**Comment by StevenLeiZhang** [comment]
1. refer to `vela addon list`, how about show x-definition's versions, when user list them.
2. `vela def get` still get the details of specified x-definition, if user specify `--version`, show the details of specified version. Show the latest version, if version is not specified explicitly

**Comment by wonderflow** [comment]
The result between `vela def get` and `vela show` are different:

```
$ vela show webservice
# Properties
+-------+----------------------------------------------------------------------------------+---------------+----------+---------+
| NAME  |                                   DESCRIPTION                                    |     TYPE      | REQUIRED | DEFAULT |
+-------+----------------------------------------------------------------------------------+---------------+----------+---------+
| cmd   | Commands to run in the container                                                 | []string      | false    |         |
| env   | Define arguments by using environment variables                                  | [[]env](#env) | false    |         |
| image | Which image would you like to use for your service                               | string        | true     |         |
| port  | Which port do you want customer traffic sent to                                  | int           | true     |      80 |
| cpu   | Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core) | string        | false    |         |
+-------+----------------------------------------------------------------------------------+---------------+----------+---------+
<the usage of the parameter>
```

```
$ vela def get webservice

<it print the whole result for CUE definition>
```

Users may need the result of the parameters they can use.

**Comment by wonderflow** [comment]
Yes. We're on the same side. The only difference is we already have vela show. I don't deny to add a  vela def show but we should still keep vela show.

**Comment by charlie0129** [comment]
Do we need revisions on doc site as well (`vela show webservice --web --version v1`)? Although I don't think that's much needed.

CLI might just be enough, for history versions.

```console
vela show -h
Show the reference doc for component, trait or workflow types.

Usage:
  vela show [flags]

Examples:
show webservice

Flags:
  -e, --env string         specify environment name for application
  -h, --help               help for show
  -n, --namespace string   specify the Kubernetes namespace to use
  -v, --version string     Get the specified version of a definition.
      --web                 start web doc site

Global Flags:
  -y, --yes   Assume yes for all user prompts
```

**Comment by wonderflow** [comment]
Yes CLI is enough for now.

**Comment by charlie0129** [comment]
I would suggest using `--revision` over `--version`, since it is called DefinitionRevision literally

**Comment by wonderflow** [comment]
> I would suggest using `--revision` over `--version`, since it is called DefinitionRevision literally

Yes, better
