### ISSUE TITLE
Panic to get addon registry

### ISSUE THREAD

**Issue by dongwenjuan** [kubevela/kubevela#4132]
**Describe the bug**
Panic to get addon registry

**To Reproduce**

# vela addon registry list
Name            Type    URL
KubeVela        helm    https://addons.kubevela.net

# vela addon registry get KubeVela
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x24cfd8a]

goroutine 1 [running]:
github.com/oam-dev/kubevela/references/cli.getAddonRegistry({0x328c238, 0xc000230000}, {0xc0008b8480, 0xc0009be770, {0x32e50f8, 0xc00129a5b0}, {0x0, 0x0}, 0x0, 0x0}, ...)
        /home/runner/work/kubevela/kubevela/references/cli/addon-registry.go:231 +0x46a
github.com/oam-dev/kubevela/references/cli.NewGetAddonRegistryCommand.func1(0xc00157b680, {0xc00155d120, 0x1, 0x1})
        /home/runner/work/kubevela/kubevela/references/cli/addon-registry.go:97 +0xc5
github.com/spf13/cobra.(*Command).execute(0xc00157b680, {0xc00155d0e0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001517900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/runner/work/kubevela/kubevela/references/cmd/cli/main.go:39 +0x16a

**Expected behavior**

**Screenshots**

**KubeVela Version**

# vela version
CLI Version: v1.4.1
Core Version: 1.4.1
GitRevision: git-ea0508a
GolangVersion: go1.17.10

**Cluster information**

**Additional context**

**Comment by wangyikewxgm** [comment]
Do you use `vela addon registry list` command?

**Comment by ZhongsJie96** [comment]
This is caused by KubeVela is a Helm registry.

**Comment by dongwenjuan** [comment]
ok, thanks for everyone~
