### ISSUE TITLE
[Feature] Create chart-museum  addon

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#4138]
**Is your feature request related to a problem? Please describe.**

[Chart-museum](https://chartmuseum.com/) is project helm for store helm chart. So this addon can help user store their own private helm chart.
Since by using "vela addon package" can package an addon as helm-chart format package which can be stored in chart-museum. this chart-museum can be used to store addon too.So this can help user build a private versioned addon registry.

**Describe the solution you'd like**

**Describe alternatives you've considered**

This addon only run in control plane cluster

**Additional context**

**Comment by StevenLeiZhang** [comment]
Is Harbor or chart-museum? since Harbor already integrated museum.
