### ISSUE TITLE
[Feature]集成配置新增配置能否支持可编辑的形式

### ISSUE THREAD

**Issue by SQGE** [kubevela/kubevela#4139]
![1111](https://user-images.githubusercontent.com/30278569/172790968-fcc3e426-d016-48d8-a40f-d51734839ab4.png)

**Comment by zzxwill** [comment]
@SQGE We did not support the `update` operation as we didn't want to expose sensitive information. If the operation is supported, you have to retry all sensitive fields. Is that what you want?

**Comment by weiy730** [comment]
@zzxwill Is this feature necessary or not ?

**Comment by barnettZQG** [comment]
@weiy730 Hi, There are some changes to this demand. Please wait for me to update the designs.

**Comment by weiy730** [comment]
> @weiy730 Hi, There are some changes to this demand. Please wait for me to update the designs.

OK.

**Comment by barnettZQG** [comment]
@weiy730 Please upgrade to 1.6+, already support editing the config.
