### ISSUE TITLE
enable dex addon failure

### ISSUE THREAD

**Issue by fengkang01** [kubevela/kubevela#4168]
**Describe the bug**

when i enable dex addon，the addon status is keep rendering,and i found the addon-dex applicaiton Applied Conditions display 
```
admission webhook "mutating.core.oam-dev.v1alpha2.components" denied the request: WorkloadDefinition.core.oam.dev "Opaque" not found
```
**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="960" alt="lQLPJxZmSyU6lE7NA2LNB4Cwf0Fwc8JTsxQCqKn-AcCUAA_1920_866" src="https://user-images.githubusercontent.com/103910304/173486462-42e2886c-ca59-48bd-a994-f23befb1541a.png">

**KubeVela Version**
```
CLI Version: v1.4.1
Core Version: 1.4.1
GitRevision: git-ea0508a
GolangVersion: go1.17.10
```

**Cluster information**

```
v1.21.4
```
**Additional context**

**Comment by wangyikewxgm** [comment]
have you modified the addon?

**Comment by fengkang01** [comment]
I'm not modify the dex addon ,i jsust execute the command "vela addon enable dex"

**Comment by fengkang01** [comment]
I may have found the reason,i found the pod status keep pedding ,and i see the reason,that display the cpu resource isInsufficient，maybe is this reason

**Comment by wangyikewxgm** [comment]
> I may have found the reason,i found the pod status keep pedding ,and i see the reason,that display the cpu resource isInsufficient，maybe is this reason

Ok. please let us know if you solved this problem in order to we can close this issue.

**Comment by fengkang01** [comment]
> > I may have found the reason,i found the pod status keep pedding ,and i see the reason,that display the cpu resource isInsufficient，maybe is this reason
> 
> Ok. please let us know if you solved this problem in order to we can close this issue.

yes,i had solved this problem .
