### ISSUE TITLE
support `vela env set --labels` for K8s namespace

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4180]
this command should be something like  :

```
vela env set vela-system --label trivy-scan=true
```

Then we can tell users that this is a environment for development which can scan vulnerabilities.

Under the hood, we are labeling the k8s namespace.

_Originally posted by @wonderflow in https://github.com/kubevela/catalog/pull/380#discussion_r897503638_

**Comment by drewwells** [comment]
I'm really failing to see why this is the way kubevela label namespaces. Is there a way to do this via the CD install system? We want to stand up clusters in automated fashion and this requires some manual CI commands.
