### ISSUE TITLE
[Feature] make kpack/Kaniko as an addon for source to image

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4182]
**Is your feature request related to a problem? Please describe.**

We don't have source to image capability for now, we can make the kpack as an addon follow this tutorial:

https://github.com/pivotal/kpack/blob/main/docs/tutorial.md

**Describe the solution you'd like**

1. make the addon for installation of kpack. 
2. Besides the addon, we should make a demo for the whole process.
    - 2.1 make a workflowstep to build image from source code.
    - 2.2 use [data passing mechanism](https://kubevela.io/docs/end-user/workflow/component-dependency-parameter) to use the image name built in the above step and pass it in the following deploy step.
    - 2.3 use vela kube apply to manage the secret
  ```
  vela kube apply secret.yaml  
  ```

**Describe alternatives you've considered**

Other alternatives: https://github.com/kubevela/kubevela/issues/3817

**Additional context**

**Comment by wonderflow** [comment]
another option is [Kaniko](https://github.com/GoogleContainerTools/kaniko), refer to https://devopscube.com/build-docker-image-kubernetes-pod/

**Comment by anoop2811** [comment]
We would be very interested in the kpack addon.

**Comment by semmet95** [comment]
@wonderflow 
One clarification please.
The tutorial you've linked is for the installation of kpack resources. Is the addon meant to install kpack controller/control-plane as mentioned [here](https://github.com/pivotal/kpack/blob/main/docs/install.md)?
Or are we just targeting the resources, assuming kpack is already installed on the cluster?

**Comment by wonderflow** [comment]
@semmet95 Installation is one of the requirement, we need to use this CR to create [workflow step](https://kubevela.net/docs/platform-engineers/workflow/workflow) for image build and pass the generated image to the new step.

**Comment by wonderflow** [comment]
It‘s supported in v1.7.0+ now, we already have a built-push-image workflow step which is implemented by kaniko.

https://kubevela.net/docs/end-user/workflow/built-in-workflow-defs#build-push-image
