### ISSUE TITLE
Error: addon terraform-alibaba system requirement miss match: deployments.apps "kubevela-vela-core" not found

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#4199]
**Describe the bug**

```
$ vela addon enable terraform-alibaba
Error: addon terraform-alibaba system requirement miss match: deployments.apps "kubevela-vela-core" not found
```

**To Reproduce**

1. install kubevela chart with another release name like `ack-kubevela`
2. enable add-on terraform-alibaba 

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

The root cause might lie in https://github.com/kubevela/kubevela/blob/a9210487fa5fcf623e4345055aaa6c9def288d80/pkg/addon/addon.go#L1517.

**Comment by wangyikewxgm** [comment]
Have you installed the vela core?

**Comment by wangyikewxgm** [comment]
A possible solution is use label to select the controller deployment. No matter what helm-release name specified when install, the deployment always has a same label is `app.kubernetes.io/name: vela-core`.

**Comment by zzxwill** [comment]
> A possible solution is use label to select the controller deployment. No matter what helm-release name specified when install, the deployment always has a same label is `app.kubernetes.io/name: vela-core`.

Yes, that should work.

**Comment by StevenLeiZhang** [comment]
> A possible solution is use label to select the controller deployment. No matter what helm-release name specified when install, the deployment always has a same label is `app.kubernetes.io/name: vela-core`.

I think we should change the Chart.

kubevela-controller.yaml as below
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevela.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kubevela.labels" . | nindent 4 }}
```


helpers.tpl as below
```
{{- define "kubevela.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

The Deployment name of vela-core is one variable, I think it should be one fixed value: "kubevela-vela-core".

The labels are variables too.
```
{{/*
Common labels
*/}}
{{- define "kubevela.labels" -}}
helm.sh/chart: {{ include "kubevela.chart" . }}
{{ include "kubevela.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{/*
Selector labels
*/}}
{{- define "kubevela.selectorLabels" -}}
app.kubernetes.io/name: {{ include "kubevela.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
```

**Comment by wonderflow** [comment]
@StevenLeiZhang Agree, but will it cause incompatible issues for users who upgrade from old ones?

**Comment by wonderflow** [comment]
We also need to provide some way to work around, in case the version check fail again. @wangyikewxgm
