### ISSUE TITLE
Old ReplicaSet Not deleted

### ISSUE THREAD

**Issue by RainElohim** [kubevela/kubevela#4204]
deploy a new application version，the old ReplicaSet was not deleted
![image](https://user-images.githubusercontent.com/34337869/174535867-5278f73c-a1fb-460a-8837-97ec48f1703b.png)

**Comment by wonderflow** [comment]
What's your version of vela? Can you describe more details about how to re-produce?

**Comment by barnettZQG** [comment]
@RainElohim This is the Deployment version mechanism, you can set the `spec.revisionHistoryLimit`, and the default value is 10.
refer to : https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy

In Kubevela, the webservice component type can not support this field, you can custom the definition and refer to the document:  http://kubevela.net/docs/platform-engineers/oam/x-definition

**Comment by RainElohim** [comment]
> @RainElohim This is the Deployment version mechanism, you can set the `spec.revisionHistoryLimit`, and the default value is 10. refer to : https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy
> 
> In Kubevela, the webservice component type can not support this field, you can custom the definition and refer to the document: http://kubevela.net/docs/platform-engineers/oam/x-definition

thanks for your reply
