### ISSUE TITLE
The user can't be modified in dex mode

### ISSUE THREAD

**Issue by rgaoistheone** [kubevela/kubevela#4212]
**Describe the bug**
Ldap user can't be assigned to roles in ux after login.

**To Reproduce**
1. Enable sso login (ldap)
2. Login with ldap credentials (user1)
3. admin user can't assign user1 to role, see screenshot below

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5696899/174737974-52594af5-a46a-40d1-93b9-2d59dcbbf3bc.png)

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
For the auto-generate users, we should support changing the roles and alias, etc.

**Comment by oupinghao** [comment]
> For the auto-generate users, we should support changing the roles and alias, etc.

Ldap user include space not a valid name and can't changing the roles.also cant's modify the username. 
<img width="831" alt="image" src="https://user-images.githubusercontent.com/16694954/174767763-848af150-35ad-4694-9249-a287378a32c4.png">

**Comment by barnettZQG** [comment]
@weiy730 Thanks, but this issue is fixed.
