### ISSUE TITLE
[Feature] how to display vela application yaml from CLI?

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4235]
**Is your feature request related to a problem? Please describe.**

In #4230, when we need to get the application yaml, we have no way but using kubectl.

**Describe the solution you'd like**

I think we can have a command such as:

```
vela status <myapp> -o yaml
```

This can display the whole application with status.

**Describe alternatives you've considered**

**Additional context**

**Comment by Somefive** [comment]
Is it just an alternative for `kubectl get app <myapp> -n <ns>`? Or more functions like pretty format / coloring / subcommand would be supported?

**Comment by wonderflow** [comment]
Just an alternative is fine.
