### ISSUE TITLE
[Feature] About applications, whether deployed applications can be displayed in a list

### ISSUE THREAD

**Issue by opswfit** [kubevela/kubevela#4245]
The following layout, the experience is not good, when there are many applications, the screen is full of ICONS, not simple enough .It is recommended that you display them in a list, which is intuitive and concise

![image](https://user-images.githubusercontent.com/13762962/175453606-0093b197-e1b0-4e82-a62c-3979c4a3fe79.png)

**Comment by barnettZQG** [comment]
@opswfit This is a good proposal, can you contribute to it?

**Comment by StevenLeiZhang** [comment]
maybe add one button, let user to select Card or Table style.
