### ISSUE TITLE
[Feature] add policy definitions for advanced internal policy

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#4246]
**Is your feature request related to a problem? Please describe.**

Previous PR(https://github.com/kubevela/kubevela/pull/3894) adds topology and override policy definition for schema.

Advanced policies' are also welcomed, including apply-once, garbage-collect, shared-resouece.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
already added
