### ISSUE TITLE
[Feature] don't ask for confirm when delete --force 

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4258]
**Is your feature request related to a problem? Please describe.**

I delete an application with --force, it still ask for confirm.
```
$ vela delete ecs-2 --force
Do you want to delete the application ecs-2 from namespace default (y/n)y
```

The same issue for `-y` is that the ask information printed.

```
 vela delete ecs-2 -y
Do you want to delete the application ecs-2 from namespace default (y/n)app "ecs-2" deleted from namespace "default"
```

**Describe the solution you'd like**

Don't ask/print for confirm when delete `--force`  and `--yes` .

**Describe alternatives you've considered**

**Additional context**

**Comment by sumit-tembe** [comment]
@wonderflow I would like to work on this.

**Comment by Somefive** [comment]
this behavior is a design by @barnettZQG 
please do not fix it unless all of you agree to that.

**Comment by barnettZQG** [comment]
I think `--force` doesn't means no need to ask for confirmation. It simply means that the dependency is ignored for application deletion.

In a test or demo scenario, we might find double-checking troublesome. However, the deletion itself is a dangerous action for a formal environment. On the other hand, there is a local environment parameter that determines the target namespace. If without confirmation. The user may initiate an incorrect operation.

example:

```
$ vela env init default

$ vela up -f app.yaml

$ vela env init prod

$ vela up -f app.yaml

# After a while

$ vela delete app --force
```

The last command will delete the app from the prod namespace. But the user will think it is deleted from the default namespace.

**Comment by wonderflow** [comment]
Yes, I agree we should ask for permission when use `--force`, while we should at least omit the output when we already specify `--yes`. The following case should be avoided. \cc @sumit-tembe 

```
$ vela delete ecs-2 -y
Do you want to delete the application ecs-2 from namespace default (y/n)app "ecs-2" deleted from namespace "default"
```
