### ISSUE TITLE
[Feature] support delete several applications in one command

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4271]
**Is your feature request related to a problem? Please describe.**

When I want to delete more than one apps, I have to do it one by one.
```
vela delete composed-app -y
vela delete frp-proxy -y
vela delete vela-app-with-sidecar -y
vela delete ecs-demo -y
```

It's annoying when I have many apps. 

**Describe the solution you'd like**

I hope we can delete them together at once:

```
vela delete composed-app frp-proxy vela-app-with-sidecar ecs-demo
```

**Describe alternatives you've considered**

**Additional context**

**Comment by StevenLeiZhang** [comment]
It sounds a little dangerous. Do you think user should double confirm batch delete?

**Comment by wonderflow** [comment]
yes, user need confirm.

**Comment by Mcduller** [comment]
I was wondering  if user can delete app in different namespace by this new feature ?

**Comment by wonderflow** [comment]
> I was wondering if user can delete app in different namespace by this new feature ?

I think they shouldn't
