### ISSUE TITLE
Suggest the removal of an inappropriate binary file

### ISSUE THREAD

**Issue by charlie0129** [kubevela/kubevela#4310]
There is a large binary file at project root: https://github.com/kubevela/kubevela/blob/master/vela

Commit: https://github.com/kubevela/kubevela/commit/2772f0311b35c98ea42267db0d6b6b2deb2e3b84

> Bin 0 -> **93,689,008 bytes**

We should delete it to prevent Git repo getting too large. **Preferably, remove it from Git history.**

**Comment by wonderflow** [comment]
MUST removed, thanks

**Comment by wonderflow** [comment]
fixed
