### ISSUE TITLE
`vela addon upgrade` missing the history args

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4311]
**Describe the bug**

The different `vela addon upgrade`  with `vela addon enable` should keep the history args and support override it with new args. But, currently, it is not.

**To Reproduce**

1. `vela addon enable velaux --version=v1.4.2 repo=acr.kubevela.net`
2. `vela addon upgrade velaux --version=v1.4.5`

The `repo=acr.kubevela.net` will be missing

**KubeVela Version**

1.4.5

**Comment by charlie0129** [comment]
BTW, the usage about adding args like `repo=acr.kubevela.net` is not documented in command help text (only on web doc). The user have no way of knowing this only using CLI. We should add it to CLI command help.

**Comment by wonderflow** [comment]
> BTW, the usage about adding args like `repo=acr.kubevela.net` is not documented in command help text (only on web doc). The user have no way of knowing this only using CLI. We should add it to CLI command help.

Yes, definitely. The command help text should be the best document.

**Comment by StevenLeiZhang** [comment]
> BTW, the usage about adding args like `repo=acr.kubevela.net` is not documented in command help text (only on web doc). The user have no way of knowing this only using CLI. We should add it to CLI command help.

because it is argument of VelaUX addon, not vela cmd
