### ISSUE TITLE
应用回收之后，UI界面一直显示删除中，实际系统上没有这个应用了，是个bug么?

### ISSUE THREAD

**Issue by opswfit** [kubevela/kubevela#4314]
![image](https://user-images.githubusercontent.com/13762962/177045152-1497b722-1dcf-45f0-94c8-ee593f1e424c.png)

[root@iZj6c8l1o9y83oohkrljirZ ~]# vela ls -n vela-test
APP       	COMPONENT 	TYPE      	TRAITS                                    	PHASE   	HEALTHY	STATUS                                                      	CREATED-TIME                 
vela-nginx	vela-nginx	webservice	scaler,gateway,annotations,storage,rollout	deleting	healthy	Host not specified, visit the cluster or load balancer in   	2022-06-12 23:05:07 +0800 CST

![image](https://user-images.githubusercontent.com/13762962/177044987-b106bcf2-6a05-47ea-9635-edc0fadd9953.png)

vela信息：
[root@iZj6c8l1o9y83oohkrljirZ ~]# vela version
CLI Version: v1.5.0-alpha.2
Core Version: 1.5.0-alpha.2
GitRevision: git-2772f03
GolangVersion: go1.17.11

velaux 1.4.5

terrafrom controller错误信息
0703 15:30:11.757602       1 status.go:16] "checking Terraform init and execution status" Namespace="vela-test" Job="vela-nginx-rds-vela-test-destroy"
E0703 15:30:11.771476       1 controller.go:304] controller-runtime/manager/controller/configuration "msg"="Reconciler error" "error"="continue reconciling to destroy cloud resource: Job.batch \"vela-nginx-rds-vela-test-destroy\" not found" "name"="vela-nginx-rds-vela-test" "namespace"="vela-test" "reconciler group"="terraform.core.oam.dev" "reconciler kind"="Configuration"

**Comment by FogDong** [comment]
Is the status of Application is `deleting` in the cluster?

**Comment by opswfit** [comment]
> Is the status of Application is `deleting` in the cluster?

![image](https://user-images.githubusercontent.com/13762962/177177190-77d2e1f4-1f81-4e9f-b623-e5f1b9f0b1b0.png)
![image](https://user-images.githubusercontent.com/13762962/177177281-c70c8396-ff90-4cef-9c8d-bc138e786fa4.png)

**Comment by FogDong** [comment]
You can check out the resource tracker of the Application in which you can see what resources are not deleted with:

```bash
kubectl get resourcetracker | grep vela-nginx

kubectl get resourcetracker <rt-name> -o yaml
```

**Comment by opswfit** [comment]
> ```shell
> -o yaml
> ```
    kind: Configuration
    name: vela-nginx-rds-vela-test

是这个资源没删除，但是一直删除不了，我强制删除也没有删除掉
![image](https://user-images.githubusercontent.com/13762962/177259206-52fbbdab-fa12-442b-8166-2037cbe038d3.png)
