### ISSUE TITLE
尝试使用terraform alibaba插件，授权异常

### ISSUE THREAD

**Issue by unionhu** [kubevela/kubevela#4328]
报错日志：
Error: failed to authenticate Terraform cloud provider terraform-alibaba err: failed to authenticate Terraform cloud provider alibaba for terraform-alibaba: context canceled

文档链接：
https://kubevela.net/zh/docs/reference/addons/terraform

**Screenshots**
![Uploading Snip20220705_7.png…]()

**KubeVela Version**

1.4.5

**Cluster information**
k8s 1.19

**Comment by wonderflow** [comment]
Does your cli version matches 1.4.5？ It's a known issue of CLI fixed in 1.4.5.

**Comment by unionhu** [comment]
> Does your cli version matches 1.4.5？ It's a known issue of CLI fixed in 1.4.5.

No, cli version is 1.4.3
1.4.5 is work, thanks!
