### ISSUE TITLE
[Feature] Enhance label and annotation feature to all managed resources not only pods

### ISSUE THREAD

**Issue by tommy1199** [kubevela/kubevela#4342]
**Is your feature request related to a problem? Please describe.**

When using kubevela with ArgoCD, ArgoCD will track all resources created by Kubevela which leads to problems, as the created resources are dynamically created and not known to ArgoCD. So it could happen that ArgoCD prunes these resources. This can be prevented by setting the following annotations

```
argocd.argoproj.io/compare-options: IgnoreExtraneous
argocd.argoproj.io/sync-options: Prune=false
```

If using the annotations trait, these will only be set to the pods and not all resources. When setting them directly as annotations on the kubevela application, all resources are inheriting these annotations correctly. But the problem is then, that the application itself is also marked to be ignored by ArgoCD, but only all sub-resources shall be ignored.

**Describe the solution you'd like**
Extend the annotation trait to have the possibility to define if the annotations shall only be set on the pods or on all created resources by kubevela

**Describe alternatives you've considered**

I could not find any other way to set annotations to all sub-resources.

**Additional context**

**Comment by barnettZQG** [comment]
@tommy1199 
I'm curious Argo will delete resources it doesn't know, is this the default behavior?

**Comment by tommy1199** [comment]
ArgoCD can be configured to "self-heal". In this case it would auto-prune everything which is linked to an app, but not found in the yaml files. 

Also it happens when running a sync with prune activated which is not the default, but often used. It is quite helpful to remove unwanted resources when they are removed from git.

**Comment by tommy1199** [comment]
I also tried to create an own trait to handle these annotation, but as far as I can see, it then just works with the defined workload resource like deployment. Could it work when I define an own policy for that?

**Comment by wonderflow** [comment]
What kind of component are you using? I think we can just define a custom trait for fix.

**Comment by tommy1199** [comment]
Currently webservice, but I think this would fit to all. If you could provide an example for a custom trait, that would be great.

**Comment by tommy1199** [comment]
I tried the following

```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Specify annotations to mark all resources to be ignored by ArgoCD"
  name: argocd
spec:
  schematic:
    cue:
      template: |
        patch: {
            metadata: annotations: {
                "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
                "argocd.argoproj.io/sync-options": "Prune=false"
            }
        }
```

But this only adds the annotations to the deployment, but not e.g. to the Service, HPA, Ingress, etc...

**Comment by wonderflow** [comment]
Try like the following:

```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Specify annotations to mark all resources to be ignored by ArgoCD"
  name: argocd
spec:
  schematic:
    cue:
      template: |
        patch: {
            metadata: annotations: {
                "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
                "argocd.argoproj.io/sync-options": "Prune=false"
            }
        }
        patchOutputs: {
          ingress: {
            metadata: annotations: {
                "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
                "argocd.argoproj.io/sync-options": "Prune=false"
            }
          }
        }
```

Use patch for workload while use `patchOutputs` for the rest resources. https://kubevela.net/docs/platform-engineers/traits/patch-trait#patch-in-traits 


I think we can even use `for loop` in the patch trait, not sure if it works. \cc @FogDong 
It could be something like below:

```cue
patchOutputs: {
	for k, v in context.outputs {
		"\(k)": {
			metadata: annotations: {
				"argocd.argoproj.io/compare-options": "IgnoreExtraneous"
				"argocd.argoproj.io/sync-options":    "Prune=false"
			}
		}
	}
}
```

**Comment by tommy1199** [comment]
I tried both now and it seems to work with the for-loop. Thanks for the tip. Only thing I have to keep in mind is that the argocd trait has to be the last in the list, so that outputs contains all resources also created by the other traits.

But this looks feasible to me :)

**Comment by wonderflow** [comment]
>  Only thing I have to keep in mind is that the argocd trait has to be the last in the list, so that outputs contains all resources also the ones created by the other traits.

Yes. It Must be the last trait to patch for other trait. Thanks for the reminds.

**Comment by wonderflow** [comment]
@tommy1199 Would you like to share something more about how you use KubeVela with ArgoCD? I'm also thinking of write some blog for that.

**Comment by tommy1199** [comment]
Sure,

in several projects I already used ArgoCD which brings the benefits of GitOps, but also has a nice UI showing all resources which are part of an "App" (not the same as the kubevela app). Most of these benefits are more in the direction of the platform team, but a developer still has to handle the complexity of pure K8s resources. They have to understand how a deployment works, how to setup services, pvcs, etc... and also have to write these resources. But most developers want to focus on their business and not on the operational aspects coming from K8s.

So I check how to put kubevela into the mix to have a probably better interface for the developer, because it gives back a more application centric view. But of course it is a tradeoff as git now does not show the full list of resources anymore, but will be created on the fly by kubevela. So it is tough for GitOps tools like ArgoCD or Flux to understand if the resources deployed with kubevela are really a representation of what is in git.

**Comment by Tranceh2** [comment]
@wonderflow I have a question related to the proposed solution. How could I apply it to an "appfile" type file? I tried in the following way.

```yaml
name: demo
services:
  testsvc:
    type: webservice
    image: crccheck/hello-world
    port: 8000
    argocd:
      name: argocd

```
but it doesn't work and it only works by applying it in the following way in an application type manifest
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo
spec:
  components:
  - name: testsvc
    properties:
      image: crccheck/hello-world
      port: 8000
    type: webservice
    traits:
      - type: argocd
        properties:
          name: argocd

```

I apologize if this is not the place to ask, but I have searched and cannot find the correct way to apply your traitDefinition.

Thanks

**Comment by wonderflow** [comment]
@Tranceh2 Let's raise an discussion for this.
