### ISSUE TITLE
[Feature] Support resourcetracker can be stored after compressing

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#4392]
For saving the capacity of the etcd cluster in the hub cluster, some resources are expected to less size.

For the resourcetrackers with more versions and  within all resources specifications, compressing them before saving will save much capacity, and improving usability of the hub cluster.

For implematation, we can set a parameter --feature-gate when core-controller work

**Comment by fourierr** [comment]
Not only rt  but also apprev.

**Comment by chivalryq** [comment]
Let's talk this in #4395

**Comment by wonderflow** [comment]
@chivalryq They're not the same thing, so I removed the dup label. I think compress the data should be important as the data can be large and exceed the etcd limit(2MB) that make the vela core not work.
