### ISSUE TITLE
Error in Vela cli enabling velaux additional DEX parameters

### ISSUE THREAD

**Issue by lgj101** [kubevela/kubevela#4404]
**Describe the bug**
When velaux is enabled with Vela cli, the following error occurs when you want to configure the DEX parameter to true，

**To Reproduce**

vela addon enable velaux dex=true
{"level":"info","ts":1658135083.7932477,"caller":"addon/versioned_registry.go:210","msg":"Not specified any version, so use the latest version v1.4.6"}
Error: render addon application fail: fail to render cue template yaml: unsupported node <[l2// from source] _|_> (*ast.BottomLit)

![image](https://user-images.githubusercontent.com/29968308/179480696-e4f89761-17e7-4c91-a9d5-a6ad31fce812.png)

**Expected behavior**

As long as the DEX parameter is added, this problem will occur, but this parameter is configurable. Shouldn't this be the case

**KubeVela Version**
CLI Version: v1.4.6
Core Version: 1.4.2
GitRevision: git-dfe12cd
GolangVersion: go1.17.11

**Comment by chivalryq** [comment]
cc @FogDong

**Comment by barnettZQG** [comment]
@lgj101 There is a way to bypass this issue. You can enable the VelaUX first, then set the DEX parameter via UI.

**Comment by lgj101** [comment]
> @lgj101 There is a way to bypass this issue. You can enable the VelaUX first, then set the DEX parameter via UI.

Thank you, I saw this in the document, but I want to start single sign on by default. After all, DEX parameters are also allowed to be configured here

**Comment by lgj101** [comment]
> > > @lgj101 There is a way to bypass this issue. You can enable the VelaUX first, then set the DEX parameter via UI.
> > 
> > 
> > Thank you, I saw this in the document, but I want to start single sign on by default. After all, DEX parameters are also allowed to be configured here
> 
> ```
> vela addon enable velaux dex="true"
> ```

Can you do this over there? I still show the same error here
