### ISSUE TITLE
Vela CLI 纳管集群后，无法通过APi接口对该集群创建namespace

### ISSUE THREAD

**Issue by 519859716** [kubevela/kubevela#4421]
版本信息：
KubeVela 1.4.6
问题现象：
1、通过后台 CLI  vela cluster join 128config --name work001
![image](https://user-images.githubusercontent.com/40968187/180164221-8699f97b-b2ad-4bf1-8ea8-ec10458f651b.png)
2、通过APiserver 向该work001集群创建namespace时报错“cluster not found in data store”
![image](https://user-images.githubusercontent.com/40968187/180164332-33d0ff74-3445-48fa-8a53-cfcba123c0b1.png)
3、根据解决方式 ，通过 list cluster 接口 同步数据，发现work001没有状态信息 
![image](https://user-images.githubusercontent.com/40968187/180164522-aecaf1d4-ef07-47db-a40a-d5af6e63f7fa.png)
4、继续创建namespace,依然不行
![image](https://user-images.githubusercontent.com/40968187/180164604-8b404a0f-a7bf-4368-92c6-1baebea13edb.png)
5、登录Velaux界面，集群列表 ，点击编辑，后点击取消
![image](https://user-images.githubusercontent.com/40968187/180165011-96ec72a4-e6c4-4324-9399-c9fcce3b2202.png)
![image](https://user-images.githubusercontent.com/40968187/180165337-7ec1d57e-5811-4902-b9b1-7426adcef416.png)
集群显示健康
![image](https://user-images.githubusercontent.com/40968187/180165379-85ee06a4-be57-49c4-ae38-0a093b7304e1.png)
6、可以给集群创建namespace
![image](https://user-images.githubusercontent.com/40968187/180165468-30ff36ae-7d10-48ce-8255-55ca4b337d31.png)

**Comment by barnettZQG** [comment]
@519859716 Currently, VelaUX syncs the cluster metadata from the cluster only in Detail API. So you can create the namespace after you click the edit button.

This really should be improved. @Somefive  What do you think?

**Comment by wonderflow** [comment]
@barnettZQG We should directly read the underlying secret in the vela apiserver instead of sync for a copy.
