### ISSUE TITLE
install error on kubernete 1.22.11

### ISSUE THREAD

**Issue by clcc2019** [kubevela/kubevela#4501]
![image](https://user-images.githubusercontent.com/46099295/181708086-fbcfebd2-0c1e-4a81-ad4f-7d8ef98f3c1e.png)

Ubuntu 21.04

**Comment by barnettZQG** [comment]
@clcc2019 What is your machine's CPU architecture?

**Comment by clcc2019** [comment]
> @clcc2019 What is your machine's CPU architecture?

amd64

**Comment by clcc2019** [comment]
v1.4.0-amd64 tag is ok

**Comment by barnettZQG** [comment]
OK, let's close this issue.
