### ISSUE TITLE
[Addon] make minio as an addon to provide multi-cloud object storage

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4509]
**Is your feature request related to a problem? Please describe.**

https://github.com/minio/minio

minio operator: https://github.com/minio/operator/blob/master/README.md

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oiar** [comment]
I'm interested in this. Can I have a try?

**Comment by wonderflow** [comment]
Sure! @oiar  Next time, you can use the following script to mark this issue:

/assign

**Comment by oeular** [comment]
Here is the helm repo for minio-operator: https://artifacthub.io/packages/helm/wenerme/minio-operator

**Comment by oiar** [comment]
> Here is the helm repo for minio-operator: https://artifacthub.io/packages/helm/wenerme/minio-operator

Thank you. I'll take a look.

**Comment by fly3366** [comment]
lgtm

**Comment by MdSahil-oss** [comment]
@wonderflow Assign this issue to me :)
