### ISSUE TITLE
[Addon] make ChaosBlade as an addon for chaos engineering 

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4510]
**Is your feature request related to a problem? Please describe.**

There's an operator for doing so: https://github.com/chaosblade-io/chaosblade-operator

**Describe the solution you'd like**

1. make a trait to an vela app for chaos engineering
2. report to grafana for the chaos report.

**Describe alternatives you've considered**

**Additional context**

**Comment by oeular** [comment]
There is no helm repo url for ChaosBlade  now. Here I propose an issue for this: https://github.com/chaosblade-io/chaosblade-operator/issues/167

**Comment by fourierr** [comment]
helm charts is convenient， but it's not necessary for addon

> There is no helm repo url for ChaosBlade now. Here I propose an issue for this: [chaosblade-io/chaosblade-operator#167](https://github.com/chaosblade-io/chaosblade-operator/issues/167)

**Comment by wonderflow** [comment]
Yes, helm chart is not necessary for addon, you can refer to https://github.com/kubevela/catalog/blob/master/experimental/addons/clickhouse/resources/ck-op.cue

**Comment by oeular** [comment]
For future upgrade with the capacity provider，the way for installing with helm charts is better.

**Comment by oeular** [comment]
Here I make a helm repo on https://artifacthub.io/packages/helm/chaosblade-operator/chaosblade-operator,  and  provide it to the issue.

https://github.com/kubevela/catalog/pull/471#issue-1372396923

**Comment by MdSahil-oss** [comment]
@wonderflow this issue needs to be closed [oeular](https://github.com/oeular) has built the addon.
