### ISSUE TITLE
Vela CLI not installed and gzip issue

### ISSUE THREAD

**Issue by BartNetJS** [kubevela/kubevela#4542]
I've followed the documentation here https://kubevela.io/docs/install to install on a windows system with the latest docker desktop.

First when running "velad install" I got an error message "Fail to set up cluster: failed to setup k3d: failed to extract k3d images: exec: "gzip": executable file not found in %PATH%"
I've installed cygwin and added the bin folder to the user environment variables to get it working.

When checking with "velad status" I got this:
![image](https://user-images.githubusercontent.com/4865355/182406804-521e5b97-4cac-4257-bf37-647e67eeaf3c.png)

vela cli is not installed.

What is missing in the docu to install vela cli?

Versions:

![image](https://user-images.githubusercontent.com/4865355/182407043-c6bcef9d-0718-461b-8ea8-a33c6b00dac1.png)

![image](https://user-images.githubusercontent.com/4865355/182407117-eb88a32e-1d6d-44e4-9455-7d99e71073f6.png)

**Comment by charlie0129** [comment]
This is because velad unzip the image tarball before loading it in docker, and can be resolve by loading the tarball directly into docker.

cc @chivalryq

**Comment by BartNetJS** [comment]
About the Vela CLI, how do I install it manually?

**Comment by wonderflow** [comment]
A quick install can be:
```
curl -fsSl https://kubevela.net/script/install.sh | bash
```

You can refer to the detail doc here: https://kubevela.io/docs/platform-engineers/advanced-install#2-install-kubevela-cli

**Comment by charlie0129** [comment]
For Windows users, `powershell -Command "iwr -useb https://kubevela.net/script/install.ps1 | iex"`. See the doc posted by @wonderflow

**Comment by chivalryq** [comment]
> This is because velad ungzip the image tarball (which uses gzip) before loading it into docker, and can be resolved by loading the tarball directly into docker. We should not rely on gzip in Windows.

Yes, it can be unusual for Windows user have `gzip` in their cmd PATH. We should either try if it's possible to load tarball to docker or use gzip golang lib to decompress the image file.

**Comment by charlie0129** [comment]
> We should either try if it's possible to load tarball to docker or use gzip golang lib to decompress the image file.

Yes, the docker daemon can read compressed data.

https://github.com/moby/moby/blob/9100e3c087216343e4149887d43f1e7ae272968a/daemon/images/image_import.go#L95

**Comment by chivalryq** [comment]
We finally remove the dependency for `gzip` in PATH! 🎉
