### ISSUE TITLE
ApplyOnce ResourceSelector ambiguous and not aligned with other ResourceSelector

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#4594]
**Describe the bug**

The implementation for FindStrategy in apply-once policy is confusing. 

https://github.com/kubevela/kubevela/blob/436ff916b65fcf3e57e7043904343e9db6bbcec1/apis/core.oam.dev/v1alpha1/applyonce_types.go#L62

The major problem is that it misuses `componentNames` and `resourceNames`.

The minor problem is that this selector is not aligned with selector in other policies (garbage-collect & shared-resource).

https://github.com/kubevela/kubevela/blob/436ff916b65fcf3e57e7043904343e9db6bbcec1/apis/core.oam.dev/v1alpha1/garbagecollect_types.go#L74

I plan to refactor this part of code. Is there any special case that might break existing usage outside test cases?
/cc @fourierr 

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by fourierr** [comment]
Thx for reminding me, I see it and fix
