### ISSUE TITLE
[Feature]  Enhanced horizontal scaling of app controller

### ISSUE THREAD

**Issue by fourierr** [kubevela/kubevela#4596]
**Is your feature request related to a problem? Please describe.**
Due to the leader-election of the controller, when there are thousands of application CRs in the hubcluster,
the new application will be delayed for updating longer and longer time.

**Describe the solution you'd like**
For this issue, i have made some experimental solution.
We want to dispatch several deployment of app controller in hubcluster.
Firstly, enabling the leader election and set `leader-election-resource-name` with different name e.g sharding-1, sharding-2.
Secondly, we add a label tag for every application CR, e.g `app.oam.dev/sharding=sharding-1`
Thirdly, add a filter to controller's eventFilter. Only the value of label tag is equal to `leader-election-resource-name`, the controller will handle the application CR.

The final effect is: application CR with label value of `sharding-1` will only be processed by app controller with `leader-selection-resource-name` value of `sharding-1`

**Comment by Somefive** [comment]
Great! This solution looks good and is similar to what I have been thinking for sharding. Would you like to make a PR for that?

**Comment by fourierr** [comment]
> 



> Great! This solution looks good and is similar to what I have been thinking for sharding. Would you like to make a PR for that?

Of course, i will make a PR.

**Comment by wonderflow** [comment]
lgtm

**Comment by wonderflow** [comment]
Just FYI, there's another solution for this issue, which don't need change the controller code: https://github.com/openkruise/controllermesh

**Comment by wonderflow** [comment]
Sharding is supported now, please check https://github.com/kubevela/kubevela/pull/5360 

It will be released in 1.8.0 and you can already enjoy this feature in https://github.com/kubevela/kubevela/releases/tag/v1.8.0-alpha.1

Closing
