### ISSUE TITLE
Can't add cluster by "Connect Existing Cluster"

### ISSUE THREAD

**Issue by nicoloxu** [kubevela/kubevela#4607]
**Describe the bug**
Can't add cluster by "Connect Existing Cluster"

**To Reproduce**
MacBook-Pro .kube % vela cluster join ./staging --name=cluster-staging
Error: failed to ensure vela-system namespace installed in cluster cluster-staging: failed to check if namespace vela-system exists: no such cluster cluster-staging

Apiserver error log:
{"level":"error","ts":1660190564.089943,"caller":"bcode/bcode.go:111","msg":"Business exceptions, error message: failed to join cluster: failed to ensure vela-system namespace installed in cluster staging: failed to check if namespace vela-system exists: no such cluster staging, path:/api/v1/clusters method:POST","stacktrace":"github.com/oam-dev/kubevela/pkg/apiserver/utils/bcode.ReturnError\n\t/workspace/pkg/apiserver/utils/bcode/bcode.go:111\ngithub.com/oam-dev/kubevela/pkg/apiserver/interfaces/api.(*ClusterAPIInterface).createKubeCluster\n\t/workspace/pkg/apiserver/interfaces/api/cluster.go:209\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/filter.go:23\ngithub.com/oam-dev/kubevela/pkg/apiserver/domain/service.(*rbacServiceImpl).CheckPerm.func1\n\t/workspace/pkg/apiserver/domain/service/rbac.go:618\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/filter.go:21\ngithub.com/oam-dev/kubevela/pkg/apiserver/interfaces/api.authCheckFilter\n\t/workspace/pkg/apiserver/interfaces/api/authentication.go:123\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/filter.go:21\ngithub.com/oam-dev/kubevela/pkg/apiserver.(*restServer).requestLog\n\t/workspace/pkg/apiserver/server.go:251\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/filter.go:21\ngithub.com/oam-dev/kubevela/pkg/apiserver.(*restServer).OPTIONSFilter\n\t/workspace/pkg/apiserver/server.go:265\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/filter.go:21\ngithub.com/emicklei/go-restful/v3.(*Container).OPTIONSFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/options_filter.go:15\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/filter.go:21\ngithub.com/emicklei/go-restful/v3.CrossOriginResourceSharing.Filter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/cors_filter.go:65\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/filter.go:21\ngithub.com/emicklei/go-restful/v3.(*Container).dispatch\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/container.go:296\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2047\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2425\ngithub.com/emicklei/go-restful/v3.(*Container).ServeHTTP\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.8.0/container.go:316\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2879\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1930"}

**KubeVela Version**
CLI Version: v1.5.0
Core Version: 1.5.0
GitRevision: git-e29b1af
GolangVersion: go1.17.12
velaux: enabled (v1.5.0)
==> Installed Clusters
[local]
==> Registry Name
KubeVela

**Cluster information**
- Kubernetes Version: ASK  1.20.11-aliyun.1

**Comment by Somefive** [comment]
Is your managed cluster to join is connectable from the hub cluster? (Are they in the same VPC or use the public IP for the apiserver)

**Comment by nicoloxu** [comment]
> 

use the public IP  for the apiserver

**Comment by Somefive** [comment]
Could you run `kubectl get secret -n vela-system -w` aside while running `vela cluster join` command? There should be a secret named `cluster-staging` created.

**Comment by nicoloxu** [comment]
> kubectl get secret -n vela-system -w

cluster-staging                                               Opaque                                4      0s
cluster-staging                                               Opaque                                4      5s

**Comment by Somefive** [comment]
I see. Seems the creation of cluster-staging is okay. Try `vela cluster join ./staging --name=cluster-staging --create-namespace=""`. This should not block in your case (seems you are blocked during creating namespace in managed cluster). But you need an additional post verification for the connection. `vela cluster probe cluster-stage` could help you check that.

**Comment by nicoloxu** [comment]
> vela cluster probe cluster-stage

MacBook-Pro .kube % vela cluster join ./staging --name=cluster-staging --create-namespace=""
Successfully add cluster cluster-staging, endpoint: https://106.xxx.xxx.xxx:xxxx.
MacBook-Pro .kube % vela cluster probe cluster-staging
Error: failed connect cluster cluster-staging: an error on the server ("unknown") has prevented the request from succeeding

**Comment by Somefive** [comment]
> > vela cluster probe cluster-stage
> 
> MacBook-Pro .kube % vela cluster join ./staging --name=cluster-staging --create-namespace="" Successfully add cluster cluster-staging, endpoint: https://106.xxx.xxx.xxx:xxxx. MacBook-Pro .kube % vela cluster probe cluster-staging Error: failed connect cluster cluster-staging: an error on the server ("unknown") has prevented the request from succeeding

Okay, there might be several possible problem with your case.
1. You need to make sure `cluster-gateway` is working correctly. Try to run `kubectl get clustergateway` and see if it works. If not, cluster-gateway is not working well. You should see your `cluster-staging` in the clustergateway list now.
2. If `cluster-gateway` works, then it might be an issue for your provided KubeConfig. You can try to access your managed cluster directly through the provided KubeConfig, like running `kubectl version`. Sometimes, your KubeConfig may not have correct credential, or CA settings. Notice that cluster-gateway currently only support X509/ServiceAccount authentication, so if you are using other authentication methods to access your managed cluster, it might not be supported.
3. If you can access your managed cluster through your provided KubeConfig, then it might be an issue for accessing your managed cluster  from your hub control plane (where KubeVela lives). There might be network issues like firewalls or dns problems. You can try to create a pod in your hub control plane and try to access your managed cluster from inside.
