### ISSUE TITLE
[Feature] workflowstepdefinition webhook

### ISSUE THREAD

**Issue by qinjia127** [kubevela/kubevela#4623]
> workflowstepdefinition webhook Only supported POST method, not  supported GET| PATCH.......

webhook: op.#Steps & {
if parameter.url.value != _|_ {
	http: op.#HTTPPost & {
		url: parameter.url.value
		request: {
			body: data.value
			header: "Content-Type": "application/json"
		}
	} @step(4)
}
if parameter.url.secretRef != _|_ && parameter.url.value == _|_ {
	read: op.#Read & {
		value: {
			apiVersion: "v1"
			kind:       "Secret"
			metadata: {
				name:      parameter.url.secretRef.name
				namespace: context.namespace
			}
		}
	} @step(5)

**Comment by wonderflow** [comment]
Seems it's supported now, check the step operation here: https://kubevela.net/docs/platform-engineers/workflow/cue-actions#requests

\cc @qinjia127 

Feel free to re-open it if issue still occurs, closing...
