### ISSUE TITLE
[Feature] Support the configurable resync for application controller 

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#4642]
Support the resync control can be enable or disable.

For now, Only can set the period for the resync.

**Comment by wonderflow** [comment]
Use apply once policy can turn off the resync. http://kubevela.net/docs/end-user/policies/apply-once

**Comment by chivalryq** [comment]
It seems this is solved, or at least have work around. Closing. Feel free to reopen it there are further questions about this.

**Comment by wonderflow** [comment]
@chivalryq After offline talk with @oeular , he wants a feature flag to disable resync for the whole controller.
