### ISSUE TITLE
[UX] The options under the Persistent Storage of the WebService are lost

### ISSUE THREAD

**Issue by RainElohim** [kubevela/kubevela#4647]
![image](https://user-images.githubusercontent.com/34337869/186061891-ea081133-8c2f-4812-bc75-01a1f9a95d9b.png)
When I hit the switch twice,the options under the Persistent Storage of the WebService are lost
CLI Version: v1.5.2
Core Version: 1.5.0
GitRevision: git-3df1776
GolangVersion: go1.17.13
ux v1.5.2

**Comment by barnettZQG** [comment]
Yes, this is a bug. we will fix it, before this you could close the dialog and reopen it. @RainElohim
