### ISSUE TITLE
[Bug] Vela CLI: `vela logs <app>` failed with cue marshal error

### ISSUE THREAD

**Issue by lunarwhite** [kubevela/kubevela#4655]
**Describe the bug**

When using `vela logs <app>` to check the app log, it will pop up with `cue: marshal error` error.

**To Reproduce**

To easily reproduce, just using `first-app.yaml` on official doc: https://kubevela.net/docs/quick-start.

`vela up` and then `vela logs`, more details:

```shell
$ vela up -f https://kubevela.net/example/applications/first-app.yaml
Applying an application in vela K8s object format...
I0824 10:34:36.910901   29826 apply.go:113] "creating object" name="first-vela-app" resource="core.oam.dev/v1beta1, Kind=Application"
✅ App has been deployed 🚀🚀🚀
    Port forward: vela port-forward first-vela-app -n prod
             SSH: vela exec first-vela-app -n prod
         Logging: vela logs first-vela-app -n prod
      App status: vela status first-vela-app -n prod
        Endpoint: vela status first-vela-app -n prod --endpoint
Application prod/first-vela-app applied.

$  vela logs first-vela-app -n prod
Error: cue: marshal error: collectedPods.0.app.name: cannot convert incomplete value "string" to JSON
cue: marshal error: collectedPods.0.app.name: cannot convert incomplete value "string" to JSON
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

Tested on macOS and Ubuntu and got same error.

```shell
$ vela version
CLI Version: v1.5.2
Core Version: v1.5.2
GitRevision: git-3df1776
GolangVersion: go1.17.13
```

**Cluster information**

**Additional context**

I've upgrade the vela by `velad install`, per https://kubevela.net/docs/install. Before updating to the latest version, everthing with `vela logs` goes will.

So I'm wondering if this upgrade operation is what caused this issue.  And how should I do for trouble shooting?

BTW, what's the best practice to update velad installed vela?

**Comment by chivalryq** [comment]
I've test this application and I didn't reproduce the bug. Can you run `velad uninstall` and `velad install` and try again?

**Comment by lunarwhite** [comment]
`velad uninstall` helps! Thanks
