### ISSUE TITLE
The `vela system info` command can not work 

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4672]
**Describe the bug**

```
➜  calculator git:(master) ✗ vela system info
Error: the server could not find the requested resource (get pods.metrics.k8s.io)
```

There is no API resource `pods.metrics.k8s.io` in my test cluster.

**Expected behavior**

We should tolerate this error.

**KubeVela Version**

1.5.3

**Cluster information**

kind 

Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-27T23:27:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Hanmengnan** [comment]
What do you think of the bug, i also have met this problem, i think this is because metrics-server misses in the cluster.
metrics-server:  https://github.com/kubernetes-sigs/metrics-server

**Comment by barnettZQG** [comment]
If there is no metric server, do not show metrics, but should show other information.
