### ISSUE TITLE
Collect pods in HelmRespoitory and HelmRelease will display many error log. 

### ISSUE THREAD

**Issue by Hanmengnan** [kubevela/kubevela#4690]
**Describe the bug**

When use the  `CollectPods`  method in `velaQL` to get the pods in HelmRespoitory and HelmRelease will display many error log.

And this will cause the error log will display in `vela top`,  and the view will disorderly.

**To Reproduce**

**Expected behavior**

**Screenshots**

![helm bug](https://user-images.githubusercontent.com/30918851/188259180-a16f26c5-abb4-47c1-b1e8-6789aa0c7d07.gif)

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
We should make the logs as multiple levels. The `vela top` do not show these logs.

**Comment by wonderflow** [comment]
@Hanmengnan please help check if it's fixed by https://github.com/kubevela/kubevela/pull/5448

**Comment by Hanmengnan** [comment]
> @Hanmengnan please help check if it's fixed by https://github.com/kubevela/kubevela/pull/5448

ok

**Comment by Hanmengnan** [comment]
> it's fixed

Great, it has been fixed.
