### ISSUE TITLE
[Feature] orphan删除app时，detach资源与app关联

### ISSUE THREAD

**Issue by codingknees** [kubevela/kubevela#4694]
orphan delete app时，发现k8s资源，包括rt都被删掉了，但是app还留着，只是状态被标记为deleting：
```
$ k delete application keyword-extract  --cascade=orphan  # 这个命令会stock住，下面的命令新开终端执行
$ k get app keyword=extract -o yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    ...
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-09-05T07:21:32Z"
  finalizers:
  - orphan
  name: keyword-extract
  ...
spec:
  ...
```

原因经社区大佬@Somefive 定位，是k8s添加的orphan这个finalizer覆盖了vela-core的app.oam.dev/resource-tracker-finalizer的行为，导致资源删除异常。
作为验证，当删除orphan这个finalizer时，命令立即退出，完成删除操作。

当前vela设计并未考虑orphan删除app的情况。建议，orphan删除app是不是可以实现成detach操作？即，接触app对底层资源的管控？

**Comment by Somefive** [comment]
Great idea! Will look into it soon.
