### ISSUE TITLE
[Bug] vela show webservice --format markdown error

### ISSUE THREAD

**Issue by ZhongsJie96** [kubevela/kubevela#4697]
**Describe the bug**

`vela show webservice --format markdown`

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/62382570/188629490-0cec78d1-88c4-4cc6-8344-de7040dee32a.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
CLI Version: master
Core Version: 0.1.0
GitRevision: git-d7f57ed1
GolangVersion: go1.17.7

**Cluster information**

**Additional context**

**Comment by chivalryq** [comment]
Testing with velad v1.6.0-alpha.1
```shell
╭─qiaozp@B-Q698Q05P-1858 ~/repo/kubevela ‹master●›
╰─$ ./vela version
CLI Version: v1.6.0-alpha.1
Core Version: v1.6.0-alpha.1
GitRevision: git-be0914f
GolangVersion: go1.17.13
╭─qiaozp@B-Q698Q05P-1858 ~/repo/kubevela ‹master●›
╰─$ ./vela show webservice --format markdown|tail
 port | The TCP socket within the container that should be probed to assess container health. | int | true |


#### hostAliases

 Name | Description | Type | Required | Default
 ---- | ----------- | ---- | -------- | -------
 ip |  | string | true |
 hostnames |  | []string | true |
```
