### ISSUE TITLE
[Addon] make Nacos as an addon

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#4707]
Is your feature request related to a problem? Please describe.

There's an operator for doing so: https://github.com/harmonycloud/nacos-operator

Describe the solution you'd like

make traits to an vela app for dynamic service discovery, configuration and service management.

**Comment by barnettZQG** [comment]
@oeular This operator repo may be in bad repair. We only need traits to set and get configuration from the Nacos.

**Comment by oeular** [comment]
OK. Some more notes are needed in README.md for how to deploy a Nacos server.

**Comment by wonderflow** [comment]
Another option: https://github.com/nacos-group/nacos-k8s/tree/master/operator
