### ISSUE TITLE
CLI fail to upgrade addon if disable multi-cluster

### ISSUE THREAD

**Issue by chivalryq** [kubevela/kubevela#4719]
**Describe the bug**

*Original posted at https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1662661491621009*

If user pass `multicluster.enabled=false` in values.yaml, cluster-gateway is not installed.

`vela addon upgrade/enable` will fail because after applying application it will check the endpoint of addon application, which uses cluster-gateway. 
> See reference/cli/status.go printAppEndpoint(). It called multicluster.Initialize() which will wait until cluster-gateway to be ready.

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by Somefive** [comment]
Solved for v1.6 & v1.7.
