### ISSUE TITLE
[velaux] cloudshell vela exec error

### ISSUE THREAD

**Issue by zhiyu0729** [kubevela/kubevela#4728]
**Describe the bug**

project admin or project member use cloudshell exec will get error:
```
Error: fail to get view template vela-system/component-pod-view from configMap: configmaps "component-pod-view" is forbidden: User "xxxx" cannot get resource "configmaps" in API group "" in the namespace "vela-system"
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
This auth problem also affects the following commands:

* vela port-forward
* vela status --pod --endpoint
* vela logs

**Comment by hprotzek** [comment]
We have the same error, but not in velaux, just our normal users using the vela cli 1.5.4 running vela logs or vela exec.
```
Error: fail to get view template vela-system/component-pod-view from configMap: configmaps "component-pod-view" is forbidden: User "nn.nn@nnn.com" cannot get resource "configmaps" in API group "" in the namespace "vela-system": requires one of ["container.configMaps.get"] permission(s).
```

**Comment by barnettZQG** [comment]
@hprotzek  As a temporary solution, you could bind a new role to the normal users to grant permission that reads the ConfigMap from the vela-system namespace.
