### ISSUE TITLE
`vela def show` always opens a browser

### ISSUE THREAD

**Issue by Adri2000** [kubevela/kubevela#4733]
Even without the `--web` flag, `vela def show` will open a browser.

When I just need to generate the doc, but don't want to display it in a browser, it'd be nice to not have the browser open automatically.

I believe this is where the behavior is defined: https://github.com/kubevela/kubevela/blob/master/references/cli/show.go#L91-L96

**Comment by wonderflow** [comment]
You can specify a capability to avoid the opening of the browser, e.g.

```
vela def show webservice
```

**Comment by Adri2000** [comment]
But that doesn't generate all the doc in `~/.vela/reference/docs/`, does it?
I'd like to be able to generate all the doc in order to re-use it somewhere else, in an automated fashion (hence why I don't want a browser opening up automatically...).

**Comment by wonderflow** [comment]
@Adri2000 I got it,  in the previous version, `vela def show` will report an error, I think we can generate all docs silently as you expect.
