### ISSUE TITLE
[Feature] "vela def vet" can support  the input "dir" and many cue files 

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#4744]
Now "vela def vet" only can vet on cue file, it is necessay to support the specified dir, the local dir and many cue files, such as:
- vela def vet /home/dir/*
- vela def vet dir/*
- vela def vet *
- vela def vet a.cue b.cue c.cue

And output the vet results of all the input cue files.

**Comment by wonderflow** [comment]
Good idea! Would you like to contribute this feature?

**Comment by 26tanishabanik** [comment]
@wonderflow , can I work on this issue

**Comment by wonderflow** [comment]
> @wonderflow , can I work on this issue?

Sure, Please go ahead. Thanks.

**Comment by 26tanishabanik** [comment]
@wonderflow , can you guide me, what would be the starting point for this issue in the repo?

**Comment by wonderflow** [comment]
You can focus on the code starting from here: https://github.com/kubevela/kubevela/blob/master/references/cli/def.go#L1037-L1063

**Comment by wonderflow** [comment]
@26tanishabanik Hi, are you still working on it?

**Comment by 26tanishabanik** [comment]
@wonderflow , yah, I am working on it. I got some personal emergency. Will resume again soon

**Comment by glokta1** [comment]
Hey @wonderflow, seems like there hasn't been any progress on this since. Can I take this up?

**Comment by glokta1** [comment]
I'm trying to test my changes but getting this error: 
![image](https://user-images.githubusercontent.com/71697384/214519998-9eee61a4-7ba4-47ab-bafc-917545b8677e.png)
I'm new to the Kubernetes ecosystem so I'm unsure how to resolve this...

**Comment by previousdeveloper** [comment]
@glokta1 By default, cli looks for a file named config in the $HOME/. kube directory. So you have to rename your config file or set its location properly.

example: export KUBECONFIG=/temp/config

**Comment by glokta1** [comment]
Thanks @previousdeveloper! Unfortunately, now I get this error:
 > Invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

I think I haven't set up the dev environment properly. Could you give me a rundown of the things I need to do before I can start working on this?

**Comment by wonderflow** [comment]
Hi, @26tanishabanik  sorry that it's been 3 months since the last ping. I'm going to un-assign the issue.

> Hey @wonderflow, seems like there hasn't been any progress on this since. Can I take this up?

Thanks, please just go ahead.

**Comment by wonderflow** [comment]
> I'm trying to test my changes but getting this error: ![image](https://user-images.githubusercontent.com/71697384/214519998-9eee61a4-7ba4-47ab-bafc-917545b8677e.png) I'm new to the Kubernetes ecosystem so I'm unsure how to resolve this...

You can use velad to setup a dev environment: https://kubevela.io/docs/installation/standalone

**Comment by Sajiyah-Salat** [comment]
hey @glokta1 are you still working on this issue. I would like to take this up?

**Comment by glokta1** [comment]
@Sajiyah-Salat Hey, you can take this up :). Busy with other things right now

**Comment by Mcduller** [comment]
Hey @wonderflow  it seems there is no progress on this issue，can i take it?

**Comment by wonderflow** [comment]
@Mcduller seems no progress, please go ahead.
