### ISSUE TITLE
Can't not open cloudshell on RKE

### ISSUE THREAD

**Issue by haiyuanhe** [kubevela/kubevela#4746]
**Describe the bug**

I found an exception error after clicking the button

`Failed:failed to prepare the kubeconfig for the user: [certificatesigningrequests.certificates.k8s.io](http://certificatesigningrequests.certificates.k8s.io/) "kubevela-csr-admin" already exists`

**KubeVela Version**

CLI Version: v1.5.4
Core Version: 1.5.4
GitRevision: git-17872f9
GolangVersion: go1.17.13

**Cluster information**
Kubernetes Version  v1.23.8

**Comment by barnettZQG** [comment]
@haiyuanhe  Can you delete the "kubevela-csr-admin" CSR and retry?

```bash
kubectl delete CertificateSigningRequest kubevela-csr-admin
```

**Comment by hanxinhang** [comment]
> @haiyuanhe Can you delete the "kubevela-csr-admin" CSR and retry?
> 
> ```shell
> kubectl delete CertificateSigningRequest kubevela-csr-admin
> ```



> @haiyuanhe Can you delete the "kubevela-csr-admin" CSR and retry?
> 
> ```shell
> kubectl delete CertificateSigningRequest kubevela-csr-admin
> ```

我有相同的问题，使用这个方式执行之后，提示：Failed:failed to prepare the kubeconfig for the user: context deadline exceeded

**Comment by barnettZQG** [comment]
@hanxinhang This depends on the Certificate Signing feature available. You could custom-create a CertificateSigningRequest resource and watch its status, to make sure this feature can work.
