### ISSUE TITLE
The `vela def edit` command loss the labels

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4766]
**Describe the bug**

If we use the `vela def edit` command to edit the definition, the labels of the definition will be lost.

**To Reproduce**

```bash
vela def edit config-image-registry
```
![image](https://user-images.githubusercontent.com/18493394/191399271-0e1514d1-699c-4f43-aca0-716323d6e2bc.png)

The `config-image-registry` definition has some labels, when we edit it, the labels are lost. We add some labels and save it, but these labels can not be saved. 

**KubeVela Version**

v1.5.3

**Comment by wonderflow** [comment]
It's fixed here: https://github.com/kubevela/kubevela/pull/4666
