### ISSUE TITLE
[Feature] Migrate the helm release applications to KubeVela

### ISSUE THREAD

**Issue by yuezhimi** [kubevela/kubevela#4784]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by barnettZQG** [comment]
@yuezhimi Please provide more info for this issue. For examples:

* Your use cases or an example.
* The effect you want to achieve.

**Comment by nuclearwu** [comment]
> @yuezhimi Please provide more info for this issue. For examples:
> 
> * Your use cases or an example.
> * The effect you want to achieve.

Migrate an already deployed application(such as the application deployed through `helm install` or the application deployed by `kubectl apply yaml`) to kubevela, and then manage the deployed application through the kubevela control plane.
