### ISSUE TITLE
it does not check the same name for "vela env init"

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/kubevela#4793]
**Describe the bug**
When an env is created through "vela env init", the same name of env is not checked, resulting in the existence of an env with the same name in the env list obtained through ‘’vela env ls‘’.
![image](https://user-images.githubusercontent.com/37976659/192510445-9c1df59a-ae3c-4ebe-9047-093814609cc2.png)

**To Reproduce**

**Expected behavior**
it should not exist env with the same name

**Screenshots**

**KubeVela Version**
1.5.5

**Cluster information**
1.21.5

**Additional context**

**Comment by wonderflow** [comment]
Good catch, you're welcome to send a PR to fix. Thanks

**Comment by nuclearwu** [comment]
> Good catch, you're welcome to send a PR to fix. Thanks

done
