### ISSUE TITLE
[Feature] Make mongodb as an addon

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#4823]
Is your feature request related to a problem? Please describe.

There's an operator for doing so: https://ot-container-kit.github.io/helm-charts/

Describe the solution you'd like

make two kinds of components, such as mongodb-standalone and mongodb-cluster.

**Comment by oeular** [comment]
Here is the PR: https://github.com/kubevela/catalog/pull/466#issue-1369212595

**Comment by wonderflow** [comment]
Merged, great job
