### ISSUE TITLE
[Feature] vela-apiserver supports mysql driver

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#4824]
In vela-apiser, there are two drivers (kubeapi and mongodb) to save the metadata, and now mysql driver is needed.

**Comment by oeular** [comment]
For some reasons, mysql driver is needed: 
- the LIST operation for configmaps will get all configmaps in namespace which makes request pressure for k8s apiserver, and this is high latency, but mysql driver can low the latency by db index.
- the configmaps for metadata will increase highly with the increasing of applications and components, but mysql can scale up easily and in safety.
- with mysql driver, it's high-available and high-reliability naturally.

**Comment by oeular** [comment]
@[tangoliu](https://github.com/tangoliu)

**Comment by oeular** [comment]
In this issue, it will be much better to provide the API or vela-cli for migrating the metadata from kube-api to mysql, and it's optional for migrating from mongodb to mysql.

**Comment by chivalryq** [comment]
duplicate with #3666

**Comment by wonderflow** [comment]
https://github.com/kubevela/velaux/pull/841
