### ISSUE TITLE
[Feature] integrate with backstage to register backstage catalog automatically

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4842]
**Is your feature request related to a problem? Please describe.**

Backstage (https://backstage.io) is very popular.

KubeVela can integrate with backstage to register kubevela apps as backstage catalog to manage IT resources, the ownership, relationship and developer portal.

**Describe the solution you'd like**

1. make backstage as an addon
2. integrate with backstage API and build a workflowstep or trait to do the register job.

**Describe alternatives you've considered**

**Additional context**

Some discussion in chinese community: 

> 用backstage catalog 管理IT 资产的owership， relationship和developer portal，比如创建出来的APP，database 可以自动注册到backstage里面是急需解决的。比如一个插件可以把vela里面的APP，user，group自动显示在backstage catalog里。这样backstage可以作为统一的IT 资产管理portal。  -- by 吴进

**Comment by anoop2811** [comment]
This would be very helpful @wonderflow !

**Comment by wonderflow** [comment]
Hi, please try this addon to enjoy the integration with backstage: https://github.com/kubevela/catalog/tree/master/experimental/addons/backstage
