### ISSUE TITLE
[BUG][Addon] Failed to enable grafana addon

### ISSUE THREAD

**Issue by miyoosan** [kubevela/kubevela#4846]
**Describe the bug**
failed to enable grafana addon

**To Reproduce**
```shell
vela addon enable grafana --version v0.1.0 
{"level":"info","ts":1665452220.216344,"caller":"addon/versioned_registry.go:236","msg":"Use the latest version v0.2.0 by default, you can use --version to speicify"}
fail to install v0.2.0 version of grafana-definitions, because vela cli/ux version: v1.5.5  require: >=v1.6.0-alpha.4.
Install grafana-definitions(vv0.1.0) which is the latest version that suits current version requirements (y/n)y
{"level":"info","ts":1665452222.17403,"caller":"addon/versioned_registry.go:236","msg":"Use the latest version v0.2.0 by default, you can use --version to speicify"}
Error: fail to dispatch dependent addon resource: fail to install v0.2.0 version of grafana-definitions, because vela cli/ux version: v1.5.5  require: >=v1.6.0-alpha.4.
Install grafana-definitions(vv0.1.0) which is the latest version that suits current version requirements
```

**Expected behavior**
success

**Screenshots**
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/25057968/194977958-e79ba55d-c926-4269-9c28-973d40c92513.png">

**KubeVela Version**

```shell
CLI Version: v1.5.5
Core Version: 1.5.5
GitRevision: git-b6a7d86
GolangVersion: go1.17.13
```

**Cluster information**

- Kubernetes Version 1.22.3

**Comment by barnettZQG** [comment]
@miyoosan Can you try:

```
vela addon enable addon grafana-definitions --version v0.1.0
vela addon enable addon grafana --version v0.1.0
```

**Comment by miyoosan** [comment]
@barnettZQG 谢谢，可以了。不过命令应该是
```shell
vela addon enable grafana-definitions --version v0.1.0
vela addon enable grafana --version v0.1.0
```

**Comment by wonderflow** [comment]
Because the dependent addons also need to follow v0.1.0. While the version of dependency addon is defined, which is causing this problem. Dependency addons can be installed manually in this case.

\cc @wangyikewxgm

**Comment by miyoosan** [comment]
Thanks very much, it works for me.

**Comment by wonderflow** [comment]
I'll keep this issue open untinl we fixed this.

> Because the dependent addons also need to follow v0.1.0. While the version of dependency addon is defined, which is causing this problem. Dependency addons can be installed manually in this case.
> 
> \cc @wangyikewxgm

**Comment by wangyikewxgm** [comment]
The reason is addon's dependency hasn't supported to specify version, always use the latest version by default.

**Comment by apmartins85** [comment]
I also see a typo, init? 
`Install grafana-definitions(vv0.1.0) which is the latest version that suits current version requirements`
`vv`
