### ISSUE TITLE
[Feature] support parameter in health evaluation cue template

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4863]
**Is your feature request related to a problem? Please describe.**

I need to define multiple traits of the SAME TYPE to the same component. Thus I need to get the output of that specific trait by its name. Something the folllowing `healthPolicy` but it is not working… What can I do?

**Describe the solution you'd like**

```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: mytrait
spec:
  schematic:
    cue:
      template: |
        outputs: "mytrait-\(parameter.name)": {
          // ...
        }
        parameter: {
          name: string
        }
  status:
    healthPolicy: 'isHealth: context.outputs."mytrait-\(parameter.name)".status.state == "Available"'
```

**Describe alternatives you've considered**

**Additional context**

From slack https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1665675028027679 by Manuel Coppotelli

**Comment by manuelcoppotelli** [comment]
Thank you @wonderflow for opening the feature request on my case
