### ISSUE TITLE
application's PHASE is running and status is healthy,but have no any resource ,such as pod ,svc ,pvc.

### ISSUE THREAD

**Issue by seedsunrise1** [kubevela/kubevela#4887]
application's status 
![QQ图片20221019170655](https://user-images.githubusercontent.com/73209573/196652043-b8cab9d9-43ee-4cb0-88d9-e283803d5cdc.png)
application's yaml
![QQ图片20221019170929](https://user-images.githubusercontent.com/73209573/196652155-0fda4e1a-7be0-4ef0-8e78-7227ac568ae3.png)
application's revision 
![QQ图片20221019171212](https://user-images.githubusercontent.com/73209573/196652262-ee9c12b7-8379-484b-998e-59122599888f.png)
application's resourceTrackers
![QQ图片20221019171428](https://user-images.githubusercontent.com/73209573/196652336-ca22514f-2a48-4f24-8622-38bbdd09b725.png)
application have no any resource 
![image](https://user-images.githubusercontent.com/73209573/196652593-cd8e7c92-bd8d-47f2-9d38-903549b2282c.png)
![image](https://user-images.githubusercontent.com/73209573/196652687-868933ac-1b3d-41f5-9c7f-daa35757a725.png)
![image](https://user-images.githubusercontent.com/73209573/196652762-307f522d-f586-4ed6-a705-220baaf7ecdb.png)

**Comment by Somefive** [comment]
This is a known issue. Probably due to the re-run of workflow. We will handle it recently. Thanks for the reporting.

**Comment by Somefive** [comment]
Should be fixed in #5240. Feel free to reopen the issue if re-occurred.
