### ISSUE TITLE
velaux更新到1.5.6时，从页面上打开看应用的实例会有一个报错：view query failed

### ISSUE THREAD

**Issue by ouweijun1** [kubevela/kubevela#4897]
![image](https://user-images.githubusercontent.com/111876424/196958693-26d4d176-b1be-43c0-8877-f69193cb22c9.png)
页面上报错是这样子的
日志报错：
{"level":"error","ts":1666270229.1308448,"caller":"service/velaql.go:74","msg":"fail to query the view fail to get view template vela-system/component-pod-view from configMap: configmaps \"component-pod-view\" not found

**Comment by ouweijun1** [comment]
解决方式：下载下面的文件,修改下格式还有命令空间，然后apply一个就可以解决这个问题
https://github.com/kubevela/kubevela/blob/master/charts/vela-core/templates/velaql/component-pod.yaml

**Comment by ouweijun1** [comment]
后面发现少了不止这个配置，还有好几个，解决方法就是再更新到1.5.0这个版本，然后再更新回1.5.6就可以了，1.5.6没有把1.5.0新加的一些配置带上
![image](https://user-images.githubusercontent.com/111876424/197109321-96c1c0d6-f546-4fd9-8d0d-85cc39c9a60f.png)

**Comment by Hanmengnan** [comment]
请问你是从哪个版本升级到1.5.6遇到的这个问题？

**Comment by ouweijun1** [comment]
> 你是从哪个版本升级到1.5.6 遇到这个问题？

1.4.1

**Comment by Hanmengnan** [comment]
我尝试复现了一下您的错误，但并没有成功。
就像你自己所说的，你发现缺少了一些configMap导致报错，这些configMa是在velaUX安装的过程中apply的，所以在存在velaUX的情况下，是一定会存在这些configMap，所以我不太清楚你为何会出现上文中的问题。

**Comment by wonderflow** [comment]
Thanks for reporting this issue, as it's not reproducable, I'm closing. While the solution here is helpful!

When view query failed, just apply the corresponding velaql template.
