### ISSUE TITLE
[Bug] 'vela env init' occasionally reports an error

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/kubevela#4929]
**Describe the bug**

'vela env init' occasionally reports an error as "Operation cannot be fulfilled on namespaces "prod": the object has been modified; please apply your changes to the latest version and try again", but actually env was created successfully.
![image](https://user-images.githubusercontent.com/37976659/198178787-b6cdbbb4-6669-4efe-b65e-ed870e2ef64c.png)
![image](https://user-images.githubusercontent.com/37976659/198178830-28b2e70d-bf24-4696-b4ad-b0fa9d8ab337.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.5.6, 1.5.7

**Cluster information**
1.21.5

**Additional context**

**Comment by nuclearwu** [comment]
After adding the relevant logs in the `updateNamespace` stage and rebuilding the binary package and execute `vela env init`, it is located that the error occurs in the `updateNamespace` stage. But the update is based on the changes made after `getNamespace`, it is not clear why the problem of resourceVersion is triggered. In fact, if the namespace does not exist, it can be returned directly after adding the relevant env tag after the successful creation, and there is no need to execute updateNamespace, what do you think? @wonderflow 
![image](https://user-images.githubusercontent.com/37976659/198481121-6c94cb9a-43d0-42eb-811f-0f3ef7921bcb.png)

**Comment by wonderflow** [comment]
yes, if the namespace is just created, we don't need to upodate it. Only if the namespace don't have the env label that we need to create it.
