### ISSUE TITLE
[Feature] make spark as an addon

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#4956]
Is your feature request related to a problem? Please describe.

There's a repo for making an addon : https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

Describe the solution you'd like

make one  component definition called spark.

**Comment by MdSahil-oss** [comment]
This issue needs to be closed, Addon already exist

**Comment by chivalryq** [comment]
Addon added in https://github.com/kubevela/catalog/tree/master/experimental/addons/spark-kubernetes-operator
