### ISSUE TITLE
Workflow may infinity loop when use cue templete.

### ISSUE THREAD

**Issue by fly3366** [kubevela/kubevela#4965]
**Describe the bug**
use notification with any value and inputs.

**To Reproduce**
error:
![image](https://user-images.githubusercontent.com/38378045/198945380-978f84b8-f6fe-4559-898c-ae0c66b3b238.png)

yaml slice:
![image](https://user-images.githubusercontent.com/38378045/198945573-46fe627d-1279-452e-9ab6-17435efdceea.png)

**KubeVela Version**
1.5.8

**Cluster information**
1.24 k3s

**Comment by FogDong** [comment]
Can you provide the application status?

You specify the inputs in the step, which means this step will wait for the inputs to execute, and in your case, the `dingding.message.text.content` had filled twice with your input and the value, which will cause conflict.
