### ISSUE TITLE
[Feature] Support error handler when workflow throw error.

### ISSUE THREAD

**Issue by fly3366** [kubevela/kubevela#4968]
**Is your feature request related to a problem? Please describe.**
Now, we use webhook will always success. If network error or other application's error broken hook's request. 
Other like read-object step. Sometime we need nullable and someone always not want it.

There is no way to stop workflow and notify user.

**Describe the solution you'd like**
Any step need return their status. like webhook, stop workflow and do "Error Handler Step" if status code was not 2xx or 3xx.

**Describe alternatives you've considered**
Cue step template add inner param like errno. It could be save to context. Check it when this step has done.

**Comment by FogDong** [comment]
You can check the example in doc that write a step definition for send a http request, and fail the step if the status code is >200: https://kubevela.net/docs/next/platform-engineers/workflow/workflow#deliver-a-simple-workflow-step

**Comment by FogDong** [comment]
In a short, you can use `op.#Fail` to fail the step: https://kubevela.net/docs/next/platform-engineers/workflow/cue-actions#fail

And use `if: status["stepname"].fail` in your error handling step: https://kubevela.io/docs/end-user/workflow/if-condition#custom-if-conditions
