### ISSUE TITLE
Env trait not work in override scenario

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4993]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2173670/199689387-125dc5a6-f6c1-473a-a37e-f2a6a2d8b8a5.png)

![image](https://user-images.githubusercontent.com/2173670/199689196-1581bd82-4fba-46e0-b78d-4fdba241f67d.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

v1.6.0

**Cluster information**

**Additional context**

**Comment by Somefive** [comment]
Caused by CUE 0.5.0 bug as mentioned in https://github.com/cue-lang/cue/issues/2062
