### ISSUE TITLE
velaux1.6 with domain setting not work

### ISSUE THREAD

**Issue by reckless-huang** [kubevela/kubevela#5008]
use vela addon enable velaux domain=velaux.xxx deploy ux , get error 
```
E1105 10:19:27.244493   18216 endpoint.go:114] no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"find v1 Ingress velaux/vela-system from cluster local failure
```
my cluster info
```
(base) reckless@reckless-ubuntu:~$ kc version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-14T02:36:39Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```
ingress info
```
(base) reckless@reckless-ubuntu:~$ kc get ingress demo-localhost -o yaml
apiVersion: networking.k8s.io/v1
```
 error happend here?
https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/gateway.cue#L58

**Comment by wonderflow** [comment]
Thanks for reporting, but I didn't reproduce your error in mycluster.

**Comment by wonderflow** [comment]
It seems it's not caused by clusterVersion, it possible caused by get endpoint.

My K8s cluster is 1.21 while the issue happen on 1.24, in that version ingress v1beta1 is not supported anymore.

**Comment by wonderflow** [comment]
![image](https://user-images.githubusercontent.com/2173670/200099297-97925be2-dc03-4645-b7f5-430c7a44e25c.png)

To he corresponding code is here:

![image](https://user-images.githubusercontent.com/2173670/200099309-246db1bb-e169-4244-b6f1-7c0cda41778d.png)

**Comment by wonderflow** [comment]
The code has ingress.SetGroupVersionKind in it but seems not working, still using `v1beta1`.
