### ISSUE TITLE
[Feature] make rabbitmq as an addon

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#5009]
Is your feature request related to a problem? Please describe.

There's a repo for making an addon: https://github.com/rabbitmq/cluster-operator

Describe the solution you'd like

make some kinds of components for rabbitmq cluster

**Comment by Hanmengnan** [comment]
> Issue needs to be closed, resolved by the PR https://github.com/kubevela/catalog/pull/634

Good Job!
