### ISSUE TITLE
[Feature] make koordinator as an addon

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#5010]
Is your feature request related to a problem? Please describe.

There's a repo for making an addon : https://github.com/koordinator-sh/koordinator

Describe the solution you'd like

make some kinds of traits, such as  Colocation Profile, 
Load Aware Scheduling, Fine-grained CPU Orchestration, Resource Reservation, PodMigrationJob, Device Scheduling, GangScheduling, Multi Hierarchy Elastic Quota Management

**Comment by MdSahil-oss** [comment]
Issue has been resolved by the PR https://github.com/kubevela/catalog/pull/643.
