### ISSUE TITLE
vela 获取vele core版本时为空？

### ISSUE THREAD

**Issue by limary** [kubevela/kubevela#5030]
问题： 一台linux 主机上安装的有vela bin进制命令工具，一个可连接k8s集群的conf文件，查看 k8s集群上vela core版本时，没有获取到版本号？

vela CLI 版本： v1.5.3

**Comment by chivalryq** [comment]
Have you installed the vela-core in that cluster?

**Comment by limary** [comment]
问题已处理

**Comment by wonderflow** [comment]
How do you fix it?
