### ISSUE TITLE
升级至1.6.0 后helm secret 分发问题

### ISSUE THREAD

**Issue by yang-maple** [kubevela/kubevela#5038]
**Describe the bug**

kubevela v1.6.0 版本发布一个chart 项目时 使用默认的ns 去部署时报错 在default ns 下找不到helm-chart 的 secret 文件，原secret存在于 vela-system 中。导致无法进行chart 部署

**Expected behavior**

部署chart 时报错

![图片](https://user-images.githubusercontent.com/90596113/200803721-ec357d00-4ae5-4c36-adbb-03237866ab84.png)

添加的helm 仓库

![InkedD8716E5D-2D2E-44e8-97E0-E3BB60BC2763](https://user-images.githubusercontent.com/90596113/200804731-f8da5ca5-69c1-42bf-9964-e3cd048e9a5c.jpg)

**Found Reason**

但是在default ns 下没有一个helm-chart 的secret 文件
仅在vela-system 下存在helm-chart 的secret 文件

![图片](https://user-images.githubusercontent.com/90596113/200805551-1d5028e6-a867-4b65-8146-5eb05dc9ded5.png)
![Inked111FC08A-848F-46f1-A7C6-3D34BE3ADD24](https://user-images.githubusercontent.com/90596113/200805838-b058ae78-1ace-4dff-8cc9-98c0fc6389f3.jpg)

**Resolve**

vela-system ns 下的 helm-chart  secret   copy 到 default

![图片](https://user-images.githubusercontent.com/90596113/200806980-2781fae5-346c-4331-a6b4-61666dcab655.png)

部署成功 
![图片](https://user-images.githubusercontent.com/90596113/200807018-f1e433f3-725d-4e7e-a452-85090ac9f5c8.png)

**Comment by barnettZQG** [comment]
@yang-maple 是否使用的配置管理添加了仓库，如果是请在项目管理页面中点击分发该配置，选择你想使用的Target即可。

**Comment by yang-maple** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yang-maple** [comment]
如果每次手动进行分发的话 ，对于多集群进行部署的话 是不是存在一定的不便利性。

**Comment by yang-maple** [comment]
自动分发完成后 secrets 并不能和默认的 vela-system 进行同步。我在ui页面删除相关配置文件后，secrets 在默认的 vela-system 进行了删除。但是其他namespaces 并不能和vela-system 进行同步。其他分发的ns 中仍然存在该 secrets.且在ui页面无法删除
**
![图片](https://user-images.githubusercontent.com/90596113/201064950-5039af11-527b-4a96-9257-9f4c03114a96.png)
**

![图片](https://user-images.githubusercontent.com/90596113/201065045-b6fe67f6-31c9-4775-80b5-36039632fd3c.png)


![图片](https://user-images.githubusercontent.com/90596113/201065405-6e0692cd-be1e-4d1a-937b-5dee35654cfe.png)

**Comment by barnettZQG** [comment]
@yang-maple 需要删除 Config Distribution。UI 需要升级到 1.6.1 后删除按钮有效。不升级情况下可使用 CLI 命令：
```
vela config distribute <config-name> --recall
```

**Comment by barnettZQG** [comment]
We will close this issue, If the problem persists, please reopen it.
