### ISSUE TITLE
[Feature]make zookeeper as an addon

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#5057]
Is your feature request related to a problem? Please describe.

There's a repo for making an addon : https://github.com/pravega/zookeeper-operator

Describe the solution you'd like

make one or more kinds of components, such as zookeeper cluster , zookeeper cluster with istio, zookeeper cluster with ephemeral storage.

**Comment by 0xquark** [comment]
Hi @wangyikewxgm ! I'd like to work on this.

**Comment by MdSahil-oss** [comment]
This enhacement has been resolved by https://github.com/kubevela/catalog/pull/622, Issue need to be closed :)
