### ISSUE TITLE
no matches for kind "Provider" in version "terraform.core.oam.dev/v1beta1"

### ISSUE THREAD

**Issue by RainElohim** [kubevela/kubevela#5087]
no matches for kind "Provider" in version "terraform.core.oam.dev/v1beta1"
ux 1.6.1 core 1.6.2
![image](https://user-images.githubusercontent.com/34337869/202658637-fa20ced2-5c9a-4ec0-8e6f-0fee44f682d0.png)
Select any project when creating a new target, the error will be reported

**Comment by barnettZQG** [comment]
We need to check the terraform addon is enabled before loading the providers.

**Comment by barnettZQG** [comment]
Fixed, Refer to: https://github.com/kubevela/kubevela/pull/5252/files#diff-d3fb5ccd7877a7d7296b1acec61a1ba319f2269033c3c175af3d67902caa9314
