### ISSUE TITLE
[Bug] Non-admin role user get project error 

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/kubevela#5095]
**Describe the bug**
![image](https://user-images.githubusercontent.com/37976659/202943030-d9ea78aa-5ec8-485b-9234-43f9754600aa.png)
![image](https://user-images.githubusercontent.com/37976659/202943387-8a510d5f-34d3-4ada-afc6-865b32ea80f3.png)

Non-admin roles do not have permission to obtain the user list, so there is no need to provide a list of responsible persons when creating a project. By default, the currently logged-in user is the responsible person.

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
@nuclearwu  A project manager should be assigned user management permissions.

**Comment by nuclearwu** [comment]
> @nuclearwu A project manager should be assigned user management permissions.
