### ISSUE TITLE
[Feature] vela cli uses namespace from kubeconfig if env not set

### ISSUE THREAD

**Issue by Kolossi** [kubevela/kubevela#5121]
If `vela env set` has not been used, and a `vela` command requiring a namespace is used without specifying namespace, then use the namespace from the current KUBECONFIG rather than `default`.

Example commands would include:
* `vela status`
* `vela up`
* `vela list`
* ... or any other command which accepts `-n | --namesapce`

**Current behaviour:**
```bash
$ kubectl config view --minify -o jsonpath='{.contexts[?(@.name == "'$(kubectl config view -o=jsonpath='{.current-context}')'")].context.namespace}'
my-namespace

$ kubeconfig get application
NAME                COMPONENT               TYPE           PHASE              HEALTHY   STATUS      AGE
my.app              my.app.component        webservice     workflowSucceeded  true      Ready:1/1   44h

$ vela list my.app
APP     COMPONENT       TYPE    TRAITS  PHASE   HEALTHY STATUS  CREATED-TIME

$ vela status my.app
Error: failed to load application my.app from namespace default: applications.core.oam.dev "my.app" not found
```
**Desired behaviour:**
```bash
$ kubectl config view --minify -o jsonpath='{.contexts[?(@.name == "'$(kubectl config view -o=jsonpath='{.current-context}')'")].context.namespace}'
my-namespace

$ kubeconfig get application
NAME                COMPONENT               TYPE           PHASE              HEALTHY   STATUS      AGE
my.app              my.app.component        webservice     workflowSucceeded  true      Ready:1/1   44h

$ vela list my.app
APP     COMPONENT         TYPE        TRAITS   PHASE               HEALTHY  STATUS     CREATED-TIME
my.app  my.app.component  webservice  gateway  workflowSucceeded   healthy  Ready:1/1  2022-11-22 16:44:15 +0000 GMT

$ vela status my.app
{status output...}
```

(`vela list` and `vela status` find app in kubeconfig current namespace `my-namespace`)

Initially discussed with @wonderflow and @FogDong in [this slack thread](https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1668683316799719)

**Comment by PratikforCoding** [comment]
can you provide some resources to go though and get some hints to resolve this?

**Comment by PratikforCoding** [comment]
can you provide some resources to go though and get some hints to resolve this?

**Comment by Kolossi** [comment]
> can you provide some resources to go though and get some hints to resolve this?

@PratikforCoding is that targetted at me? I'm afraid I don't know how to resolve it, I've nothing else I can add aside the repro in my OP.
