### ISSUE TITLE
[Feature] report error when app not exist for endpoint list

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#5124]
**Is your feature request related to a problem? Please describe.**

When I'm getting the endpoint for my addon-velaux, I forget to specify the namespace, it shows as below:

```
$ vela status addon-velaux --endpoint
Please access addon-velaux from the following endpoints:
+---------+-----------+--------------------------+----------+-------+
| CLUSTER | COMPONENT | REF(KIND/NAMESPACE/NAME) | ENDPOINT | INNER |
+---------+-----------+--------------------------+----------+-------+
+---------+-----------+--------------------------+----------+-------+
```

It didn't report any error message. Actually, I should specify the namespace by:

```
$ vela status addon-velaux --endpoint -n vela-system
Please access addon-velaux from the following endpoints:
+---------+-----------+-------------------------------+----------------------------+-------+
| CLUSTER | COMPONENT |   REF(KIND/NAMESPACE/NAME)    |          ENDPOINT          | INNER |
+---------+-----------+-------------------------------+----------------------------+-------+
| local   | apiserver | Service/vela-system/apiserver | apiserver.vela-system:8000 | true  |
+---------+-----------+-------------------------------+----------------------------+-------+
```

**Describe the solution you'd like**

Report error when the namespace don't have this app.

**Describe alternatives you've considered**

**Additional context**

**Comment by PratikforCoding** [comment]
hey can you give me some resources to resolve it @wonderflow . I want to work on this.

**Comment by wonderflow** [comment]
@PratikforCoding The code here should report the error that the application not exist https://github.com/kubevela/kubevela/blob/master/references/cli/status.go#L219
