### ISSUE TITLE
[Feature] addon enable failed with confusion error message

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#5128]
**Is your feature request related to a problem? Please describe.**

```
$ vela addon enable experimental/addons/harbor/
enable addon by local dir: experimental/addons/harbor/
W1125 16:31:19.621537    5830 render.go:253] Application name addon-harbor will be overwritten with . Consider removing metadata.name in template.
Error: resource name may not be empty
```

I can't understand what's the real error. The actual error is I forget the name the Component:

![image](https://user-images.githubusercontent.com/2173670/203937634-da2cad23-87d6-485b-9a6b-048da0b352f8.png)

**Describe the solution you'd like**

Report the right error, pointing out what's wrong and guide me to fix the error.

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyikewxgm** [comment]
This error is produced  when the addon's dir hasn't a `metadata.yaml` file, has been fixed by pr: https://github.com/kubevela/kubevela/pull/5298. Closing, feel free to reopen if still exist.
