### ISSUE TITLE
[Bug] Specifying a cluster to enable fluxcd will delete the fluxcd installed on the previously joined cluster

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/kubevela#5138]
**Describe the bug**

Specifying a cluster to enable fluxcd will delete the fluxcd installed on the previously joined cluster
![image](https://user-images.githubusercontent.com/37976659/204460254-0a078937-103c-472a-9e0a-b48f923c1ec8.png)
![image](https://user-images.githubusercontent.com/37976659/204460277-0f3ae6fa-9277-453b-a24d-ea51ada32e5b.png)
![image](https://user-images.githubusercontent.com/37976659/204460317-f027812a-7bbf-4f15-8dd6-f0e92d69e587.png)

**To Reproduce**

**Expected behavior**

We hope that the installation of fluxcd in the specified cluster will not affect the installed fluxcd of the previously

**Screenshots**

**KubeVela Version**
1.6.2

**Cluster information**
1.21.5

**Additional context**

**Comment by nuclearwu** [comment]
@wangyikewxgm

**Comment by wonderflow** [comment]
Yes, the current addon deployment with clusters specified is confusing in this case. Actually we are using clusters to specify which clusters should be deployed while it's easily be confused as which clusters to add into the deployment.

As a quick fix, we need to detect the behavior when users specify a new cluster set without the existing one, we should report a warning and make interactive confirmation.

**Comment by nuclearwu** [comment]
> Yes, the current addon deployment with clusters specified is confusing in this case. Actually we are using clusters to specify which clusters should be deployed while it's easily be confused as which clusters to add into the deployment.
> 
> As a quick fix, we need to detect the behavior when users specify a new cluster set without the existing one, we should report a warning and make interactive confirmation.

Yes, you can first consider explaining the "clusters" parameter to inform the user that the previous enable operation will be override. In the future, you can consider adding a subcommand to implement adding deployment.
