### ISSUE TITLE
[Feature]deploy workflow don't support inputs/outputs

### ISSUE THREAD

**Issue by zhaohuiweixiao** [kubevela/kubevela#5139]
**Is your feature request related to a problem? Please describe.**
i want use inputs/outputs with deploy workflow, bug when run the application，it run faild. the vela version is 1.6.2，and fluxcd is 2.1.7
![1669703552160_D5FD6636-3CB0-4079-9CFB-525190941C27](https://user-images.githubusercontent.com/6092586/204463150-acfd6892-1a66-4c68-8055-91f6c38891e5.png)
![image](https://user-images.githubusercontent.com/6092586/204463173-5ebd27cb-f41a-4a2a-881b-8ecc1834dcbd.png)

**Describe the solution you'd like**
the deploy workflow support inputs/outputs

**Comment by wonderflow** [comment]
ref #4339

**Comment by wonderflow** [comment]
It's supported in https://github.com/kubevela/kubevela/pull/5161 and released in v1.7.0. Check the doc https://kubevela.io/docs/end-user/workflow/component-dependency-parameter#multi-cluster-orchestration
