### ISSUE TITLE
关于vela logs查看被管理集群pod没有日志输出

### ISSUE THREAD

**Issue by limary** [kubevela/kubevela#5140]
vela logs查看被管理集群pod没有日志输出

版本说明：
- vela cli :1.5.4
- vela core: 1.5.4
- k8s server : 1.21.14

排查
- 1、通过命令`vela logs`查看发部到本地集群pod中的日志正常
- 2、通过命令`kubectl logs`查看发部到被管理集群pod中的日志正常
- 3、通过命令`vela exec` 进入发部到被管理集群pod正常
- 4、通过dlv 通`vela logs` debug 输出 "upsupported command: cannot process "source" request"

dlv debug 
```golang
import (
    	"github.com/oam-dev/kubevela/pkg/utils/common"
	"github.com/oam-dev/kubevela/pkg/utils/util"
	"github.com/oam-dev/kubevela/references/appfile"
	"github.com/oam-dev/kubevela/references/cli"
	"github.com/stretchr/testify/assert"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

scheme := common.Scheme
	c := common.Args{
		Schema: scheme,
	}

	largs := cli.Args{Args: c}
	largs.Namespace = "lim-foo-dev-lped"
	largs.PodName = "ferr-6d67cf47bd-blwnq"
	largs.ClusterName = "c01"
	largs.ComponentName = "ferr"
	// largs.Namespace = "vela-system"
	// largs.PodName = "apiserver-5db5557c4f-7l7xm"
	// largs.ClusterName = "local"
	//largs.Name = "lped"
	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
	app, err := appfile.LoadApplication(largs.Namespace, "lped", c)
	if err != nil {
		fmt.Println(err)
		return
	}
	ioStreams := util.NewDefaultIOStreams()
	largs.App = app
	if err := largs.Run(ctx, ioStreams); err != nil {
		fmt.Println(err)
		return
	}

```

**Comment by wonderflow** [comment]
辛苦帮忙验证下最新版本的 CLI 是否同样能够复现，只需要升级CLI，不需要升级vela-core

**Comment by limary** [comment]
> 辛苦帮忙验证下最新版本的 CLI 是否同样能够复现，只需要升级CLI，不需要升级vela-core

使用最新版本CLI(版本1.6.3)还是一样问题，日志没有输出信息

**Comment by limary** [comment]
通过dlv 通vela logs debug 输出 "upsupported command: cannot process "source" request" 此是代码中有误出现在，
看了原码后发现，vela logs 本身是不支持从被管理集群获取日志的，pkg/utils/common/args.go 中获取 rest.Config是管理的配置，产生client-go client后传给了stren.Watch方法，所以本地pod是正常的

**Comment by wonderflow** [comment]
代码里只要加入这三行即可获取远端日志
```
	if selectPod.Cluster != "" {
		ctx = multicluster.ContextWithClusterName(ctx, selectPod.Cluster)
	}
```

**Comment by limary** [comment]
> if selectPod.Cluster != "" {
> 		ctx = multicluster.ContextWithClusterName(ctx, selectPod.Cluster)
> 	}
vela logs 发布的 cli 1.6.3 cli 1.5.4 被管里发布的pod都看不了日志的
我用自己写的代码可以正常，传入一个被管理的client

**Comment by limary** [comment]
> 代码里只要加入这三行即可获取远端日志
> 
> ```
> 	if selectPod.Cluster != "" {
> 		ctx = multicluster.ContextWithClusterName(ctx, selectPod.Cluster)
> 	}
> ```

vela logs 发布的 cli 1.6.3 cli 1.5.4 被管里发布的pod都看不了日志的
我用自己写的代码可以正常，传入一个被管理的client

**Comment by wonderflow** [comment]
reproduced, will fix it ASAP.

**Comment by wonderflow** [comment]
已在 1.6.4 中修复
