### ISSUE TITLE
[Feature]kubevela结合istio实现服务治理

### ISSUE THREAD

**Issue by suwliang3** [kubevela/kubevela#5148]
使用场景：
将istio作为addon集成到kubevela中，根据集群是否支持双栈选择安装相应的istio。对于集群中的应用（工作负载为deployment和statefulSet），使用该集群上的istio实现服务治理能力，包括金丝雀发布、熔断等能力。具体包括将应用进行多版本发布，并通过设置header和cookie等路由规则，将流量路由到对应的版本。

当前状态：
在验证社区提供的[kubevela结合istio的方案](https://www.bookstack.cn/read/kubevela.io-1.1-zh/3aecdfaa8a4c3bf2.md)
时，发现社区提供的rollout插件只支持工作负载是deployment类型的，不支持statefulSet类型的工作负载。对于deployment类型的应用，已验证可以实现金丝雀发布。

**Comment by wangyikewxgm** [comment]
1. 这个方案中的结合 istio 的案例是通过 app 内 workflow 来实现灰度发布过程的，现在有了独立于 app 的 workflow 之后，可以在 app 上的层的发布工作流来执行金丝雀发布的工作流。发布过程中的各个参数可以通过 trait 的方式来配置。
2. 现在 rollout 已经支持了 statefulset ，麻烦贴一下 statefulset 使用 vela rollout 的报错截图。

**Comment by suwliang3** [comment]
@wangyikewxgm 
1. "可以在 app 上的层的发布工作流来执行金丝雀发布的工作流" 的意思是指？
2.![image](https://user-images.githubusercontent.com/105624645/205024597-ea35c787-0d4c-4a59-9a77-e3280d3dedd8.png)

**Comment by wangyikewxgm** [comment]
> @wangyikewxgm
> 
> 1. "可以在 app 上的层的发布工作流来执行金丝雀发布的工作流" 的意思是指？
>    2.![image](https://user-images.githubusercontent.com/105624645/205024597-ea35c787-0d4c-4a59-9a77-e3280d3dedd8.png)

这个原因应该是 rollout 在发布 statefulset 的情况下，rollout 的 status 字段为空了。可以看下是否是这样的 @suwliang3

**Comment by suwliang3** [comment]
@wangyikewxgm 
![image](https://user-images.githubusercontent.com/105624645/206078729-14635d01-b49b-4929-ab62-edcd212bcd87.png)
`kubectl get rollouts.standard.oam.dev ihit-test -oyaml`也看不到status的信息。
![image](https://user-images.githubusercontent.com/105624645/206079143-f2832ec1-b4c2-4efc-93dd-7dcbb4cc16e6.png)
