### ISSUE TITLE
[Feature] add namespces support to WorkflowStep Apply-Component 

### ISSUE THREAD

**Issue by mujinhuakai** [kubevela/kubevela#5176]
**Is your feature request related to a problem? Please describe.**

When using  Apply-Component step to deploy a component to a specific cluster, I also need to deploy to a specific namespace in the cluster

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Somefive** [comment]
Use `deploy` workflowstep and `topology` policy could give a solution.

**Comment by tfzhaod** [comment]
> Use `deploy` workflowstep and `topology` policy could give a solution.

Can you provide a reference example?

**Comment by tfzhaod** [comment]
``

> Use `deploy` workflowstep and `topology` policy could give a solution.

I also need to use op.#ConditionalWait What should I write?

**Comment by Somefive** [comment]
> 

Do you mean you want to write WorkflowStepDefinition and use op.#ConditionalWait with op.#ApplyComponent ?

**Comment by tfzhaod** [comment]
> > 
> 
> Do you mean you want to write WorkflowStepDefinition and use op.#ConditionalWait with op.#ApplyComponent ?

Yes. A component needs to be deployed in the deployed application. The component needs to be deployed in the specified cluster and namespace. After the component is deployed, obtain the returned parameters and write them to the configmap.

**Comment by tfzhaod** [comment]
In the 1.6 document, #ApplyComponent supports specifying a namespace, but I wrote that the namespace is not specified.

**Comment by FogDong** [comment]
Yes we do support `namespace` parameter in `op.#ApplyComponent`, but we did not expose `namespace` in workflow step definition `ApplyComponent`.

**Comment by tfzhaod** [comment]
> Yes we do support `namespace` parameter in `op.#ApplyComponent`, but we did not expose `namespace` in workflow step definition `ApplyComponent`.

import (
  "vela/op"
)

"my-helm": {
    annotations: {}
    attributes: {}
    description: "Apply helm charts and wait till it's running."
    labels: {}
    type: "workflow-step"
}

template: {
  // 部署应用中的所有资源
  load: op.#Load & {}

  apply: op.#ApplyComponent & {
     value: load.value[parameter.component]
	 cluster: parameter.cluster
	 namespace: parameter.namespace
  }

  resource: op.#Read & {
     value: {
       kind: "Deployment"
       apiVersion: "apps/v1"
       metadata: {
         name: "tomcat"
         // 可以使用 context 来获取该 Application 的任意元信息
         namespace: context.namespace
       }
     }
  }

  workload: resource.value
  // 等待 helm 的 deployment 可用
  wait: op.#ConditionalWait & {
    continue: workload.status.readyReplicas == workload.status.replicas && workload.status.observedGeneration == workload.metadata.generation
  }
}

Does namespace in op.#ApplyComponent specify a namespace

**Comment by FogDong** [comment]
```
resource: op.#Read & {
value: {
kind: "Deployment"
apiVersion: "apps/v1"
metadata: {
name: "tomcat"
// 可以使用 context 来获取该 Application 的任意元信息
namespace: context.namespace
}
```

Seems like you apply component with `parameter.namespace` and read the deployment with `context.namespace`, please make them consistent.

**Comment by tfzhaod** [comment]
> ```
> resource: op.#Read & {
> value: {
> kind: "Deployment"
> apiVersion: "apps/v1"
> metadata: {
> name: "tomcat"
> // 可以使用 context 来获取该 Application 的任意元信息
> namespace: context.namespace
> }
> ```
> 
> Seems like you apply component with `parameter.namespace` and read the deployment with `context.namespace`, please make them consistent.

 Change context.namespace to parameter.namespace. Can the namespace parameter in op.#ApplyComponent specify a namespace?

**Comment by Somefive** [comment]
> Change **context.namespace** to **parameter.namespace**. Can the namespace parameter in op.#ApplyComponent specify a namespace?

Yes, it can.

**Comment by nuclearwu** [comment]
> Use `deploy` workflowstep and `topology` policy could give a solution.

The `topology` policy applies to all components. If there are multiple components, no one component can be specified.

**Comment by nuclearwu** [comment]
resolved by https://github.com/kubevela/kubevela/pull/6228
