### ISSUE TITLE
[Feature]the webservice component has no args parameter

### ISSUE THREAD

**Issue by xingming01** [kubevela/kubevela#5226]
**Is your feature request related to a problem? Please describe.**

At present, the webservice component has only command parameter, but no args parameter. Therefore, it needs to be extended for easy use
**Describe the solution you'd like**

Add the args parameter to the webservice component
**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
https://github.com/kubevela/kubevela/pull/5227
