### ISSUE TITLE
[Bug] index structure  map[string]string ,mongo  resulting in inconsistent results obtained by filtering non-string type by index.

### ISSUE THREAD

**Issue by LiuFang07** [kubevela/kubevela#5263]
**Describe the bug**

Now the datastore index structure is map[string]string, the value of non-string type stored in mongo is not string, resulting in inconsistent results obtained by filtering non-string type by index. Can I change the index to map[string]interface? I can submit the relevant fix code.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/26155892/210482047-e90d9c4e-04ae-4cd4-8b63-c44516ffb29b.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/26155892/210482229-465b0b4c-c507-4129-8cbc-a873cd042936.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
@LiuFang07 The index implements base on the label when the driver is `kubeapi`. It only supports map[string]string. For MongoDB, are there any errors?

**Comment by LiuFang07** [comment]
> @LiuFang07 The index implements base on the label when the driver is `kubeapi`. It only supports map[string]string. For MongoDB, are there any errors?

the value of non-string type stored in mongo is not string, resulting in inconsistent results obtained by filtering non-string type by index. 

The reason is that when mongo stores the index is still filtered by string value but the actual value is not a string, like the bool in the picture

**Comment by LiuFang07** [comment]
@barnettZQG 

My solution is that index is a map[string]interface type. Driven by kubeapi and mongo, the kubeapi driver converts the interface to string. mongo can use the actual type filtering.

**Comment by barnettZQG** [comment]
@LiuFang07 You can try.
