### ISSUE TITLE
[Feature]vela addon list installed only 

### ISSUE THREAD

**Issue by cezhang** [kubevela/kubevela#5348]
**Is your feature request related to a problem? Please describe.**

Provide an option for user to list installed addons only by cli.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyikewxgm** [comment]
`vela addon list | grep enabled` can solve this problem?

**Comment by cezhang** [comment]
I review most of the cli commands and (maybe i miss) those doesn't need or provide options to query "status" of the result. Maybe this is the design methodology of vela cli, or there is space to add more functionality. 

I close it for now, if needed , will open this again.
