### ISSUE TITLE
[Bug] Specify the env of a project to take over the application, but the project is the default project

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/kubevela#5352]
**Describe the bug**

Specify the env of a project to take over the application, but the project is the default project rather than the project to which the env belongs.
![image](https://user-images.githubusercontent.com/37976659/212801627-60bb841b-a2dc-4fe1-8797-71c76c5a6a11.png)
![image](https://user-images.githubusercontent.com/37976659/212801607-19c5d8f2-e22b-4449-829a-5d7265122cbd.png)
![image](https://user-images.githubusercontent.com/37976659/212801718-2de1f79a-9763-49cc-affe-3f3a6a10f6a4.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.7.0

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
Yes. We need to provide a way to sync project from app crd to velaux. This feature request also mentioned recently by Aurora.

**Comment by nuclearwu** [comment]
> Yes. We need to provide a way to sync project from app crd to velaux. This feature request also mentioned recently by Aurora.
@wonderflow Yes, if it is not particularly urgent, I would be happy to come back for the Spring Festival to deal with this issue
