### ISSUE TITLE
[Feature] [LFX] Support auto generation of CUE schema and docs from Go struct

### ISSUE THREAD

**Issue by FogDong** [kubevela/kubevela#5364]
## Project description

In our provider system, we can use our defined go functions in cue schema.

The go provider usually has a `parameter` and `return`, for example, in a `http` provider, we have struct like:

```
// input: parameters

type RequestVars struct {
	Method  string `json:"method"`
	URL     string `json:"url"`
	Request struct {
		Body string `json:"body"`
	} `json:"request"`
	Header  http.Header `json:"header"`
	Trailer http.Header `json:"trailer"`
}

// output: returns
// ResponseVars is the vars for http response
type ResponseVars struct {
	Body       string      `json:"body"`
	Header     http.Header `json:"header"`
	Trailer    http.Header `json:"trailer"`
	StatusCode int         `json:"statusCode"`
}

```

And the CUE schema is like:

```
package http

#Do: {
	#do:       "do"
	#provider: "http"

	// +usage=The params of this action
	$params: {
		// +usage=The method of HTTP request
		method: *"GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "CONNECT" | "OPTIONS" | "TRACE"
		// +usage=The url to request
		url: string
		// +usage=The request config
		request?: {
			// +usage=The request body
			body?: string
			// +usage=The header of the request
			header?: [string]: string
			// +usage=The trailer of the request
			trailer?: [string]: string
			...
		}
	}
	// +usage=The response of the request will be filled in this field after the action is executed
	$returns: {
		// +usage=The body of the response
		body?: string
		// +usage=The header of the response
		header?: [string]: [...string]
		// +usage=The trailer of the response
		trailer?: [string]: [...string]
		// +usage=The status code of the response
		statusCode: int
		...
	}
	...
}
```

The field is the same as these in the struct, so it's possible to support an auto generator of CUE schema from Go struct.
After is schema is generated, we can also support generating the docs from CUE schema with its comments automatically.

## Expected outcomes

1. Support the auto generator of CUE schema from Go struct.
2. Support the auto generator of docs from CUE schema.
3. The generators will be the command of vela cli.

## Mentors

@FogDong 

## Expected size of the project

200 hours

## Difficult level

Medium.

## Reference

Go struct example: https://github.com/kubevela/pkg/blob/main/cue/cuex/providers/http/http.go
CUE schema example: https://github.com/kubevela/pkg/blob/main/cue/cuex/providers/http/http.cue
Doc schema example: https://kubevela.io/docs/end-user/components/references

**Comment by 0xquark** [comment]
Hello @FogDong 
I recently came across your project while reviewing the issues on Kubevela. The project caught my attention and I am eager to explore it further. I am currently familiarizing myself with CUE and would like to contribute to the project.I am looking forward to working on this.

**Comment by glokta1** [comment]
Hey @FogDong, this issue caught my eye. I've learned Golang and been loving it. I would like to give this issue a go (pun intended xD) during this LFX season. Will be perusing the docs in the coming days to familiarize myself with CUE. Looking forward to hopefully working with you on this!

**Comment by FogDong** [comment]
@0xquark @glokta1 Great! We can discuss more details on slack!

**Comment by tiger-yash** [comment]
Hi @FogDong! I am really interested to contribute on this project, please guide on how I should proceed with the application and further communication.

**Comment by iyear** [comment]
Hello! I'm also interested in the program and want to work on this project under LFX Mentorship. I'm writing a demo to initially validate my idea.

And another question:  `Request.Header` and `Request.Trailer` in Golang and Cue do not seem to correspond in the example.

**Comment by ahsenkamal** [comment]
Hi @FogDong, I came across this project for LFX mentorship and I'm interested to contribute to it. Could you please guide me through the process?

**Comment by FogDong** [comment]
Hi, @iyear @ahsenkamal , you can checkout the [cue toturial](https://kubevela.io/docs/platform-engineers/cue/basic) to get started!

Hi, @iyear , yes, currently in Go, the `Request.Trailer` is a concrete struct, but in Cue, we just specify it as a map and lose the constraints. That's because we do not have the generator right now, so we just simplify the struct to map manually. But it would be better if we can have the concrete struct in cue as well so that we can constrict the user input more precisely.

**Comment by FogDong** [comment]
Everyone who's interested in this project is welcome to discuss it with me in the [slack](https://cloud-native.slack.com/archives/C01BLQ3HTJA), my slack ID is the same as my GitHub ID.

**Comment by chivalryq** [comment]
Closing for this project is finished successfully.
