### ISSUE TITLE
addon vela-workflow upgrade error：exists but not managed by any application now

### ISSUE THREAD

**Issue by nicoloxu** [kubevela/kubevela#5370]
**Describe the bug**

addon vela-workflow upgrade error：exists but not managed by any application now
0.3 to 0.4.0 

~ % vela addon status vela-workflow
vela-workflow: enabling
==> Installed Clusters
[local]
==> Registry Name
KubeVela
diagnose addon info from application addon-vela-workflowAbout:

  Name:      	addon-vela-workflow
  Namespace: 	vela-system
  Created at:	2022-11-07 17:28:26 +0800 CST
  Status:    	workflowFailed

Workflow:

  mode: DAG-DAG
  finished: true
  Suspend: false
  Terminated: true
  Steps
  - id: jl8z2wr3j3
    name: workflowrun-crd
    type: apply-component
    phase: failed
    message: run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot apply ApplyOption: CustomResourceDefinition /workflowruns.core.oam.dev exists but not managed by any application now)]
  - id: 3h292hpyc2
    name: vela-workflow
    type: apply-component
    phase: failed
    message: run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot apply ApplyOption: Deployment vela-system/vela-workflow exists but not managed by any application now)]
  - id: 95s9lqlzfx
    name: vela-workflow-additional-privileges
    type: apply-component
    phase: failed
    message: run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 4 errors. [(cannot apply ApplyOption: ServiceAccount vela-system/vela-workflow exists but not managed by any application now), (cannot apply ApplyOption: ClusterRoleBinding /vela-workflow:manager-rolebinding exists but not managed by any application now), (cannot apply ApplyOption: Role vela-system/vela-workflow:leader-election-role exists but not managed by any application now), (cannot apply ApplyOption: RoleBinding vela-system/vela-workflow:leader-election-rolebinding exists but not managed by any application now)]

Services:

  - Name: workflow-helm
    Cluster: local  Namespace: vela-system
    Type: webservice
    Healthy Fetch repository successfully, Create helm release successfully
    No trait applied

**KubeVela Version**

CLI Version: v1.7.0
Core Version: 1.7.0
GitRevision: git-8ef2513
GolangVersion: go1.19.4

**Comment by barnettZQG** [comment]
@nicoloxu There is CRD in the cluster. Do you install the workflow CRD in another way?

**Comment by barnettZQG** [comment]
@wangyikewxgm Should we add some policy for the vela-workflow addon same as the fluxCD?

**Comment by nicoloxu** [comment]
> @nicoloxu There is CRD in the cluster. Do you install the workflow CRD in another way?

I only follow the document。use vela cli：vela install -v 1.7.0
