### ISSUE TITLE
When binding the environment to the application”application name is not exist“

### ISSUE THREAD

**Issue by nicoloxu** [kubevela/kubevela#5371]
**Describe the bug**

When binding the environment to the application, an error will be prompted。”application name is not exist“

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/23714756/215324414-08d719f8-ea5a-49ac-b83c-07feb8d415f2.png)

**KubeVela Version**

CLI Version: v1.7.0
Core Version: 1.7.0
GitRevision: git-8ef2513

**Comment by barnettZQG** [comment]
@nicoloxu Could you tell me how do you create this application?
