### ISSUE TITLE
[Feature] Add resource metrics display to `vela top`

### ISSUE THREAD

**Issue by Hanmengnan** [kubevela/kubevela#5375]
**Is your feature request related to a problem? Please describe.**

If we can introduce the resource metrics display function, we can display this information in vela top with the help of related functions.

![image](https://user-images.githubusercontent.com/30918851/215370285-5be4a8fd-68ac-446a-a771-2a452386aeb5.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
sounds great! the UI LGTM
