### ISSUE TITLE
Upgrade addon of prometheus-server error is as follows

### ISSUE THREAD

**Issue by yincyx** [kubevela/kubevela#5393]
About:

  Name:         addon-prometheus-server
  Namespace:    vela-system
  Created at:   2023-01-31 16:38:09 +0800 CST
  Status:       [33mworkflowFailed[0m

Workflow:

  mode: StepByStep-DAG
  finished: true
  Suspend: false
  Terminated: true
  Steps
  - id: kvelut5tve
    name: deploy-prometheus
    type: deploy
    phase: [31mfailed[0m
    message: run step(provider=multicluster,do=deploy): Found 1 errors. [(error encountered in cluster local: Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot apply ApplyOption: Namespace /o11y-system exists but not managed by any application now)])]
  - id: zbdl2rhpgw
    name: deploy-thanos
    type: deploy
    phase: [33mskipped[0m
  - id: vvd5s9vod1
    name: get-prometheus-endpoint
    type: collect-service-endpoints
    phase: [33mskipped[0m
  - id: fnbmld3wpn
    name: prometheus-server-register
    type: create-config
    phase: [33mskipped[0m

**Comment by Somefive** [comment]
By far, the current solution includes:
1. Add `app.oam.dev/name: addon-prometheus-server`, `app.oam.dev/namespace: vela-system` to the labels of the namespace o11y-system. Then add `app.oam.dev/shared-by: vela-system/addon-prometheus-server` to the annotations of the namespace o11y-system.
2. Delete the namespace o11y-system first and then re-enable the prometheus-server addon.

You can choose solution 2 if you haven't used o11y-system before. If you have used it before, you can use solution 1.

We will later enhance the addon installation. This problem frequently occurs when using VelaUX to manage the target and env of o11y-system.

**Comment by Somefive** [comment]
A fix has been done here. You can try the latest addon version. https://github.com/kubevela/catalog/pull/617
