### ISSUE TITLE
[Feature] Velaux implement Component/Trait Definition management page

### ISSUE THREAD

**Issue by Ghostbaby** [kubevela/kubevela#5420]
**Is your feature request related to a problem? Please describe.**
We can only use vela CLI to manage the Definitions, maybe we should to implement the Definitions manage page in Velaux.

**Describe the solution you'd like**

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/3281480/216769855-9a30d8a9-baff-44d7-8d6f-4428cc195b9a.png">

**Comment by barnettZQG** [comment]
@Ghostbaby Could you provide some helps for this feature? Such as contributing to the API implementation.

**Comment by wonderflow** [comment]
If we implement this feature, we can have two steps:

1. just provide a way to copy-paste existing definition with UI operations, users should edit in their local IDE and debug to make it work.
2. We should provide a convenient way to edit the definition files, provide validation, auto-completion in some cases.
