### ISSUE TITLE
[Feature] need podAntiAffinity for vela pods, in order to make kubevela high availability 

### ISSUE THREAD

**Issue by StevenLeiZhang** [kubevela/kubevela#5425]
**Is your feature request related to a problem? Please describe.**

`podAntiAffinity` is not set by default, it can not meet HA requirement, all the pods of vela may be scheduled to the same node.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Do you mean the vela controller?

**Comment by StevenLeiZhang** [comment]
> Do you mean the vela controller?

yes
