### ISSUE TITLE
[Feature] [LFX] Expand multiple database drivers for the API server

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#5426]
**Is your feature request related to a problem? Please describe.**

Now, there are two database drivers. Reference: https://github.com/kubevela/kubevela/tree/master/pkg/apiserver/infrastructure/datastore

MongoDB is the only driver of production recommendations. More users request the community to support more databases. Such as Mysql(#4824), Amazon DocumentDB, and others.

Based on database protocol compatibility considerations, we should support the following databases first:

- [x] Mysql
- [ ] PostgreSQL

**Additional context**

1. The already existing drivers all belong to NoSQL. The database models are not necessarily directly applicable to SQL databases.  So we need to design a data conversion scheme.
2. We need a tool to migrate the data from one driver to another driver.  #5082

**Comment by jameszhangyukun** [comment]
Hey @barnettZQG I am a master from SEL laboratory of Zhejiang University, familiar with cloud native,  Mysql，PostgreSQL. Now I am very interested in the kubevela community and hope to participate in the community through this issue.

**Comment by barnettZQG** [comment]
@jameszhangyukun Nice! Concat me via Slack or Email if you have any problems.

**Comment by yikuaibro** [comment]
Hi @barnettZQG, I have written to express my interest in participating in the GSOC 2023 program with the KubeVela community. I am very excited about the "Expand multiple database drivers for the API server" project idea listed on the GSOC website, and I would like to know more about the specific requirements and expectations for this project.

**Comment by Amit-unchartered** [comment]
hi @barnettZQG I am willing to participate in GSOC 2023 program and contribute to the KubeVela community. I want to work for this issue. I am quite familiar with MySQL and PostgreSQL and learning about the cloud native technologies. I will be happy to contribute to this project. Please tell me how to start.

**Comment by barnettZQG** [comment]
@jameszhangyukun @yikuaibro @Amit-unchartered Thanks very much for your enthusiasm. Please write a proposal about this topic and send it to me.  Please contact me via Slack.  https://cloud-native.slack.com/archives/C01BLQ3HTJA
My name is Barnett.

**Comment by yikuaibro** [comment]
@barnettZQG I sent you a concise proposal a few days ago, I wonder if you received it. The email used is yikuaibro@gmail.com.

**Comment by barnettZQG** [comment]
> 

@yikuaibro I am sorry to see it just now. It's great. I will review it.

**Comment by Amit-unchartered** [comment]
@barnettZQG Thankyou for your reply

**Comment by GauriBhandari** [comment]
Hey @barnettZQG  I am a student from India and I would like to contribute to this issue. I wanted to know if this is still available? If it is available then I would like to write a proposal for this.

**Comment by barnettZQG** [comment]
@GauriBhandari I'd like to see your proposal.

**Comment by GauriBhandari** [comment]
Hey @barnettZQG  is this project still available for gsoc?  I am unable to see this on gsoc dashboard. Could you please help

**Comment by barnettZQG** [comment]
> Hey @barnettZQG is this project still available for gsoc? I am unable to see this on gsoc dashboard. Could you please help

@GauriBhandari  Thanks for your attention. A student submitted a proposal for this project. I'm not sure if that means you won't be able to view it.

**Comment by J0SAL** [comment]
Hello, @barnettZQG @chivalryq,I am interested in learning about this project and want to work on this project under LFX Mentorship.
Please let me know about any materials or resources that I should learn to get a better understanding of the project and its requirements.

Additionally, I was wondering if there is anything else I can do to get started, such as research and learn about the project from the existing documentation.

**Comment by chivalryq** [comment]
Hi @J0SAL Glad you are interested. You can contact me in Slack.

**Comment by shashankiitbhu** [comment]
Hello @barnettZQG @chivalryq , I am Interested in working on this project under LFX Mentorship. I would like to learn more about this project. I have already set up that project and trying to understand the project design, what else I can do to get a better understanding of this project?

**Comment by sripor62** [comment]
Hello @chivalryq @barnettZQG, I am interested in working on this project and being a part of  LFX mentorship. I am familiar with MongoDB, MySQL, and PostgreSQL.Kindly tell me the steps where I should begin and explore the project.

**Comment by GetRohitansh** [comment]
Is this issue sorted, I wanted to contribute to it.

**Comment by chivalryq** [comment]
Hi @sripor62 @GetRohitansh This issue has been almost done. Thanks and you can find other issues.

**Comment by chivalryq** [comment]
LFX mentee @NeerajGartia21 has successfully finish mentorship project. Document has been updated to https://kubevela.io/docs/reference/addons/velaux/. PR: https://github.com/kubevela/kubevela.github.io/pull/1280
