### ISSUE TITLE
[Feature Request] Double check on config update

### ISSUE THREAD

**Issue by chivalryq** [kubevela/kubevela#5427]
**Describe the bug**

When I create the second config using terraform-alibaba template, vela CLI override and update the default provider silently. This causes all the cloud resources in my cluster to re-build. 

This is dangerous and we can add a double check when overriding happens.

**To Reproduce**

1. vela config create foo -t terraform-alibaba ALICLOUD_REGION=cn-hangzhou ALICLOUD_ACCESS_KEY=$ALICLOUD_ACCESS_KEY ALICLOUD_SECRET_KEY=$ALICLOUD_SECRET_KEY
2. vela config create bar -t terraform-alibaba ALICLOUD_REGION=cn-hangzhou ALICLOUD_ACCESS_KEY=$ALICLOUD_ACCESS_KEY ALICLOUD_SECRET_KEY=$ALICLOUD_SECRET_KEY
3. Check the Provider. The provider `default` is updated with newer config.

**Expected behavior**

In CLI, the config creation should be provide prompts if the command will update the 
**Screenshots**

In CLI: Don't allow update config output (e.g. Provider) to be updated silently. It could provide a double check prompt to ask user if this is intended.

**Comment by afzalbin64** [comment]
I can see CLI sub cmd config stays here and wants condition before updates silently.

https://github.com/kubevela/kubevela/blob/c0c1f6fdbb33099dab5fdcc3b9c6a9c909f9bdbe/references/cli/config.go#L378-L390
