### ISSUE TITLE
kubevela patch behavior is inconsistent with kubectl apply

### ISSUE THREAD

**Issue by zxbyoyoyo** [kubevela/kubevela#5457]
**Describe the bug**

we want kubevela to be able to manage existing resources of k8s
1. be able to force take over existing resources 
2. behavior is the same as kubectl apply

we set `--feature-gates=LegacyResourceOwnerValidation=true` to achieve this, but found that if the resource has been manually modified in K8s, the behavior of kubevela after merging is not consistent with kubectl apply, resulting in some redundant data can never be deleted.

possible reason: kubevela maintains the `app.oam.dev/last-applied-configuration` annotation alone, which is not aligned with the annotation of kubectl apply, so that the first merge does not count the reduced patch.

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by swastik959** [comment]
@Somefive can we include kubectl.kubernetes.io/last-applied-configuration so that kubevela will be able to match the annotation used by kubectl apply and ensure that the merge process takes into account any modifications made outside of kubevela.

**Comment by Somefive** [comment]
Yes, I think we can add some parameter to allow that. I think @FogDong has some related implementations in kubevela/pkg but it is not introduced in kubevela/kubevela for now. I will go on with that later.

**Comment by zxbyoyoyo** [comment]
> Yes, I think we can add some parameter to allow that. I think @FogDong has some related implementations in kubevela/pkg but it is not introduced in kubevela/kubevela for now. I will go on with that later.

hope to raise the priority of this, our new platform is already open for use, and urgently need this feature, thank you!

**Comment by zxbyoyoyo** [comment]
adding feature switches to control this piece is a bit complicated, the default behavior is better
