### ISSUE TITLE
[Feature] vela adopt support multi-cluster adoption

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#5464]
**Is your feature request related to a problem? Please describe.**

By far, vela adopt only support adopt resources on the hub control plane, aka, the local cluster.

In the case users want to take over resources in managed cluster, it is recommended to make some adoption support for that.

**Describe the solution you'd like**

Support `vela adopt deployment/cluster-asia/default/nginx` typed resource adoption. This should automatically retrieve the nginx deployment in cluster-asia's default namespace and add topology policy for that.

**Describe alternatives you've considered**

**Additional context**

**Comment by basuotian** [comment]
Is there anyone working on this feature? 
I would like to help if no one is assigned @Somefive

**Comment by wonderflow** [comment]
@basuotian Sure, just go ahead! Thanks!
