### ISSUE TITLE
[BUG] Failed helm deployment on k8s > 1.25.x due removed batch/v1beta1

### ISSUE THREAD

**Issue by hprotzek** [kubevela/kubevela#5476]
Deploy helm chart on k8s > 1.25.x fails due the removed CronJob batch/v1beta1 version.

We are still using vela 1.5.10 but it seems the cron-task is still using batch/v1beta1 in the master.

```
Error: UPGRADE FAILED: cannot patch "cron-task" with kind ComponentDefinition: admission webhook "mutating.core.oam-dev.v1beta1.componentdefinitions" denied the request: no matches for kind "CronJob" in version "batch/v1beta1"
```

**Comment by chivalryq** [comment]
This definition can be made compatible with both v1.24- and v1.25+ . Refer to these doc: https://kubevela.io/docs/platform-engineers/traits/customize-trait#cluster-version

**Comment by wonderflow** [comment]
Yes, we can update the Component definition here with the following code:

```
 output: {
    if context.clusterVersion.minor < 25 {
        apiVersion: "batch/v1beta1"
    }
    if context.clusterVersion.minor >= 25 {
        apiVersion: "batch/v1"
    }
    kind: "CronJob"
}
```

Anyone who's interested on this issue can help fix.

**Comment by wonderflow** [comment]
BTW, this feature is introduced in KubeVela v1.6.0+ by [this PR](https://github.com/kubevela/kubevela/pull/4890), I'm afraid you have to upgrade to 1.6.0+ for it. @hprotzek 

We have a great improvement on KubeVela 1.6 especially we have aligined with the CUE 0.4.x version.

The upgrade from 1.5 to 1.6 can follow [this guide](https://kubevela.net/docs/platform-engineers/system-operation/migration-from-old-version#from-v15x-to-v16x).
