### ISSUE TITLE
Support customized .terraformrc , credentials.tfrc.json and credentials-helper for private terraform registry

### ISSUE THREAD

**Issue by ramekris3163** [kubevela/kubevela#5512]
Sometimes users want to use customized .terraformrc , credentials.tfrc.json and credentials helper files. Here's one use case:

Use self-hosted JFrog Artifactory to proxy and cache AWS provider resource. These files are used to point to the self-hosted services and provide credentials. This is related to https://github.com/kubevela/terraform-controller/issues/350 

The schematic terraform cue must support passing the required configuration for mounting the above files by passing it on to the terraform controller if present.

**Comment by chivalryq** [comment]
Fixed in #5550
