### ISSUE TITLE
Kubevela rest API is not OpenAPI/Swagger spec compliant

### ISSUE THREAD

**Issue by h7kanna** [kubevela/kubevela#5536]
**Describe the bug**
Generating a client for KubeVela using openapi generator fails.

**To Reproduce**

1. Download spec from https://kubevela.stoplight.io/docs/kubevela/b8aer09sc4q9e-kube-vela-api-1-7
2. Run open generator tool
3. For example, a rust client: openapi-generator generate --skip-validate-spec -i .kubevela.yaml -g rust -o .
4. Or use Swagger editor to identify errors

**Expected behavior**
RestAPI OpenAPI compliant

**Screenshots**
<img width="1774" alt="Screenshot 2023-02-19 at 5 48 43 PM" src="https://user-images.githubusercontent.com/2949492/219982870-e96db724-7ca5-4c26-b80f-2cc2d70e2c81.png">
le, add screenshots to help explain your problem.

**KubeVela Version**
1.7

**Cluster information**
N/A

**Comment by barnettZQG** [comment]
#5428 
Can you try this spec file? 
https://github.com/kubevela/kubevela/blob/master/docs/apidoc/swagger.json

**Comment by h7kanna** [comment]
Yes, it is the same, tried both.
