### ISSUE TITLE
[Bug]  collect logs error

### ISSUE THREAD

**Issue by suwliang3** [kubevela/kubevela#5556]
**Describe the bug**

fail to collect logs
 
![lALPJxuMVGsB3_nNAszNBaI_1442_716](https://user-images.githubusercontent.com/105624645/220843233-0edd6eac-6da0-4e17-b5e9-9915dad4f1a9.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.6.5

**Cluster information**

1.21

**Additional context**

**Comment by chivalryq** [comment]
fixed in #5559
