### ISSUE TITLE
[Bug]Failed to query policy details generated by application

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/kubevela#5564]
**Describe the bug**

Failed to query policy details generated by application, as shown in the picture.
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/37976659/221140547-01d1e15c-cd97-440f-8f8e-9f4072e3fb34.png">
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/37976659/221140627-a90cc664-0512-4c58-b475-6342a8d371a0.png">

**To Reproduce**

1、vela addon enable dbtype=mongodb dbURL=mongodb://
2、use velaux to create application

![image](https://user-images.githubusercontent.com/37976659/221532931-a022bad8-e186-426e-91ad-bcae03da4663.png)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37976659/221466073-839575fa-08d1-485b-aef6-08b0b3db1837.png">
![image](https://user-images.githubusercontent.com/37976659/221532771-b9014d55-972e-4b2a-8bb3-9dafddb7fb41.png)
![image](https://user-images.githubusercontent.com/37976659/221533048-e6195429-146b-4a33-9e27-b182dfebd1b1.png)

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.7.4

**Cluster information**

1.21.5

**Additional context**

**Comment by barnettZQG** [comment]
@nuclearwu Can you descript how to reproduce?

**Comment by nuclearwu** [comment]
> @nuclearwu Can you descript how to reproduce?

1、vela addon enable dbtype=mongodb dbURL=mongodb://
2、use velaux to create application
