### ISSUE TITLE
[Feature] No matter what state the workflow is in, if the Application changes, the workflow status information must be recorded in the ApplicationRevision

### ISSUE THREAD

**Issue by yueyongyue** [kubevela/kubevela#5597]
**Is your feature request related to a problem? Please describe.**

No matter what state the workflow is in, if the Application changes, the workflow status information must be recorded in the ApplicationRevision

**Describe the solution you'd like**
(https://github.com/kubevela/kubevela/blob/master/pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go#L227)

**Describe alternatives you've considered**

**Additional context**

**Comment by FogDong** [comment]
Actually we'll store the workflow state in Application revision when workflow is finished(terminated, failed, succeeded), if the workflow is still running, then it should not be stored in Application revision.

However, if the spec is changed and the workflow is re-running, then we should record the former workflow status to the previous revision.
