### ISSUE TITLE
 Policy couldn't delete or display,hint the policies incorrect

### ISSUE THREAD

**Issue by evilabandon** [kubevela/kubevela#5633]
**Describe the bug**

 Policy couldn't delete or display,hint the policies incorrect
**To Reproduce**

1.VelaUx -- Applications/xxx/app-config
2.delte or click the  Policy

```apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/appAlias: ""
    app.oam.dev/appName: inspection-worker-test
    app.oam.dev/deployVersion: "20230308041227610"
    app.oam.dev/publishVersion: workflow-video-inspection-20230308041227614
    app.oam.dev/workflowName: workflow-video-inspection
  creationTimestamp: null
  labels:
    app.oam.dev/appName: inspection-worker-test
    app.oam.dev/source-of-truth: from-velaux
  name: inspection-worker-test
  namespace: video-inspection
  resourceVersion: "78331486"
spec:
  components:
  - name: inspection-worker-test
    properties:
      objects:
      - apiVersion: apps.kruise.io/v1alpha1
        kind: CloneSet
        metadata:
          labels:
          name: inspection-worker-base-c7a
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: inspection-worker-base-c7a
          template:
            metadata:
              annotations:
                k8s.aliyun.com/eci-use-specs: 0.25-0.5Gi
              labels:
                app: inspection-worker-base-c7a
            spec:
              containers:
              - image: inspection-worker-base:1.0.7
                name: main
              readinessGates:
              - conditionType: InPlaceUpdateReady
    type: k8s-objects
  policies:
  - name: local-video-inspection
    properties:
      clusters:
      - local
      namespace: video-inspection
    type: topology
  workflow:
    mode: {}
    steps:
    - meta:
        alias: Deploy To local-video-inspection
      name: local-video-inspection
      properties:
        policies:
        - local-video-inspection
      type: deploy
status: {}
```

**Expected behavior**

1.policy can be display or delete

**Screenshots**

![image](https://user-images.githubusercontent.com/863483/223651378-77e7d73a-04cc-46b5-8b03-8c485757332c.png)

**KubeVela Version**

vela-core:v1.7.5
UI Version: v1.7.4-51e71f1
API Version: v1.7.4-git-f3cdbcf

CLI Version: 1.7.5
**Cluster information**

v1.20.4-427
**Additional context**

**Comment by evilabandon** [comment]
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/appAlias: ""
    app.oam.dev/appName: inspection-worker-test
    app.oam.dev/deployVersion: "20230308041227610"
    app.oam.dev/publishVersion: workflow-video-inspection-20230308041227614
    app.oam.dev/workflowName: workflow-video-inspection
  creationTimestamp: null
  labels:
    app.oam.dev/appName: inspection-worker-test
    app.oam.dev/source-of-truth: from-velaux
  name: inspection-worker-test
  namespace: video-inspection
  resourceVersion: "78331486"
spec:
  components:
  - name: inspection-worker-test
    properties:
      objects:
      - apiVersion: apps.kruise.io/v1alpha1
        kind: CloneSet
        metadata:
          name: inspection-worker-base-c7a
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: inspection-worker-base-c7a
          template:
            metadata:
              annotations:
                k8s.aliyun.com/eci-use-specs: 0.25-0.5Gi
              labels:
                app: inspection-worker-base-c7a
            spec:
              containers:
              - image: inspection-worker-base:1.0.7
                name: main
              readinessGates:
              - conditionType: InPlaceUpdateReady
    type: k8s-objects
  policies:
  - name: local-video-inspection
    properties:
      clusters:
      - local
      namespace: video-inspection
    type: topology
  workflow:
    mode: {}
    steps:
    - meta:
        alias: Deploy To local-video-inspection
      name: local-video-inspection
      properties:
        policies:
        - local-video-inspection
      type: deploy
status: {}

**Comment by evilabandon** [comment]
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/appAlias: ""
    app.oam.dev/appName: inspection-worker-test
    app.oam.dev/deployVersion: "20230308041227610"
    app.oam.dev/publishVersion: workflow-video-inspection-20230308041227614
    app.oam.dev/workflowName: workflow-video-inspection
  creationTimestamp: null
  labels:
    app.oam.dev/appName: inspection-worker-test
    app.oam.dev/source-of-truth: from-velaux
  name: inspection-worker-test
  namespace: video-inspection
  resourceVersion: "78331486"
spec:
  components:
  - name: inspection-worker-test
    properties:
      objects:
      - apiVersion: apps.kruise.io/v1alpha1
        kind: CloneSet
        metadata:
          name: inspection-worker-base-c7a
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: inspection-worker-base-c7a
          template:
            metadata:
              annotations:
                k8s.aliyun.com/eci-use-specs: 0.25-0.5Gi
              labels:
                app: inspection-worker-base-c7a
            spec:
              containers:
              - image: inspection-worker-base:1.0.7
                name: main
              readinessGates:
              - conditionType: InPlaceUpdateReady
    type: k8s-objects
  policies:
  - name: local-video-inspection
    properties:
      clusters:
      - local
      namespace: video-inspection
    type: topology
  workflow:
    mode: {}
    steps:
    - meta:
        alias: Deploy To local-video-inspection
      name: local-video-inspection
      properties:
        policies:
        - local-video-inspection
      type: deploy
status: {}

**Comment by chivalryq** [comment]
See https://github.com/kubevela/kubevela/pull/5578

**Comment by chivalryq** [comment]
Fixed

**Comment by barnettZQG** [comment]
@evilabandon Are you using MongoDB right?
