### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by chengyh2go** [kubevela/kubevela#5680]
**Describe the bug**
用harbor搭建了镜像仓库，且启用了helm chart。
通过kubevela的web界面，在config中添加了harbor的helm repository，做了config的distribute
在实际部署helm应用的时候，报错：
Kind: HelmRepository
Namespace: demo
Name: test
Status: UnHealthy
Message: failed to fetch Helm repository index: failed to cache index to temporary file: Get "https://harbor.kubevirt.demo.com/chartrepo/starrocks/index.yaml": x509: certificate signed by unknown authority

通过helm客户端是可以添加这个repo，并且能够找到对应的chart：
helm search repo harbor
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
harbor/kube-starrocks   1.3.4           2.5.0-fix-uid   kube-starrocks collects Kubernetes manifests, s...

执行curl命令，是可以获取到index.yaml的：
curl -k https://harbor.kubevirt.demo.com/chartrepo/starrocks/index.yaml
apiVersion: v1
entries:
  kube-starrocks:
  - apiVersion: v2
    appVersion: 2.5.0-fix-uid
    created: "2023-03-14T08:35:09.883374043Z"
    description: kube-starrocks collects Kubernetes manifests, starrocks combined
      with documentation and scripts to provide easy to operate end-to-end Kubernetes
      cluster deploy starrocks using the starrocks operator.
    digest: ba19db70dfb736b41b71ccc6f63a95bcc3bf41ec9abbe7be427f3cfb0043886c
    home: https://github.com/StarRocks/starrocks-kubernetes-operator
    icon: https://avatars.githubusercontent.com/u/88238841
    keywords:
    - operator
    - starrocks
    - database
    - olap
    kubeVersion: '>=1.18.3-0'
    maintainers:
    - email: caixiaohua@starrocks.com
      name: Kevin Cai
    - email: shensida@starrocks.com
      name: SidaShen
    - email: fushilei@starrocks.com
      name: ShileiFu
    name: kube-starrocks
    sources:
    - https://github.com/StarRocks/helm-charts
    - https://github.com/StarRocks/starrocks
    type: application
    urls:
    - charts/kube-starrocks-1.3.4.tgz
    version: 1.3.4
generated: "2023-03-14T08:35:10Z"
serverInfo: {}

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

CLI Version: 1.7.5
Core Version: 1.7.5
GitRevision: git-1c2df102
GolangVersion: go1.19.6

**Cluster information**
k8s Version: v1.25.2

**Additional context**

**Comment by wangyikewxgm** [comment]
你的仓库是自签名的证书，你需要在 config 配置一下 CaFile。

**Comment by chengyh2go** [comment]
> 你的仓库是自签名的证书，你需要在 config 配置一下 CaFile。

配置了的
![image](https://user-images.githubusercontent.com/73768658/225235776-40b38914-793e-417a-8793-f37137b2d151.png)

**Comment by wangyikewxgm** [comment]
请贴一下 helmRepo 的 spec 字段。

**Comment by chengyh2go** [comment]
> 请贴一下 helmRepo 的 spec 字段。

spec:
  interval: 5m
  provider: generic
  timeout: 60s
  url: https://harbor.kubevirt.demo.com/chartrepo/starrocks

**Comment by wangyikewxgm** [comment]
没有 secretRef 字段吗？你在界面上不要手动填写 repo url ，要选择之前配置的 config。

**Comment by chengyh2go** [comment]
> 没有 secretRef 字段吗？你在界面上不要手动填写 repo url ，要选择之前配置的 config。

我在界面上，看不到之前配置的config
![image](https://user-images.githubusercontent.com/73768658/225248774-ce9daee2-7da4-4fe1-b843-a7ba8982d986.png)

**Comment by wangyikewxgm** [comment]
应该是你没有在 app 所在的项目下做分发。

**Comment by chengyh2go** [comment]
> 应该是你没有在 app 所在的项目下做分发。
之前新建了一个project：demo，请帮忙确认一下在demo这个project下的分发是否成功：
![image](https://user-images.githubusercontent.com/73768658/225261260-9f51cef0-a7de-4f05-9c96-97697da57924.png)

**Comment by chengyh2go** [comment]
@wangyikewxgm 能帮忙给出一个 secretRef 的参考格式吗？我手工操作引用一下生成的secret试试，看能否发布成功

**Comment by wangyikewxgm** [comment]
在浏览器控制台看下有没有什么报错，或者看下 apiserver 的日志。

**Comment by chengyh2go** [comment]
> 在浏览器控制台看下有没有什么报错，或者看下 apiserver 的日志。
@wangyikewxgm 感谢支持， secretRef 是个很重要的提示。
我手工编辑我环境中的HelmRepository，将secretRef指向生成的secret：
![image](https://user-images.githubusercontent.com/73768658/225316216-25c6a87a-550c-4239-86da-db78eff07786.png)
编辑之后，就可以发布成功了。
