### ISSUE TITLE
[Feature] context.environment

### ISSUE THREAD

**Issue by morigs** [kubevela/kubevela#5688]
**Is your feature request related to a problem? Please describe.**

I'd like to use environment name to automatically set NODE_ENV variable

**Describe the solution you'd like**

`context.environment` object with `name` field in the component definition context

**Describe alternatives you've considered**

Using namespace name can be a workaround, however, they're often not equal to env name

**Comment by StevenLeiZhang** [comment]
I think ENV is not a model of vela-core and OAM.  it is defined by vela-api-server. So you can not find it in the definition of Application.

If you need some customized infos, you could set them into labels, and the you can use it by `context.appLabels["foo"]`

**Comment by morigs** [comment]
That's unfortunate, but thanks, labels is ok as workaround.
I hope oam will address this in future

**Comment by morigs** [comment]
Btw it's a bit strange that `envbinding` is present as entity in `core.oam.dev/v1alpha1`, but env itself is not

**Comment by Somefive** [comment]
> Btw it's a bit strange that `envbinding` is present as entity in `core.oam.dev/v1alpha1`, but env itself is not

`envbinding` is deprecated for about one year and will be removed soon. The name of `envbinding` is confusing and does not mean the same thing with `ENV`.

**Comment by morigs** [comment]
Thx, if there are no plans for envs in oam, the issue can be closed
