### ISSUE TITLE
Pre-start-hook in >=1.7 doesn't respect --system-definition-namespace, pod fails to start

### ISSUE THREAD

**Issue by csomm** [kubevela/kubevela#5703]
**Describe the bug**
We have Kubevela installed in a namespace other than "vela-system", but the new pre-start-hook in 1.7 (in cmd/core/app/hooks/pre_start_hook.go) doesn't respect the namespace given on the command line using --system-definition-namespace, but uses the default Kubevela namespace "vela-system". Thus the pre-start-hook fails, because there is no namespace "vela-system" and the pod fails to start and enters a crash loop.

**To Reproduce**
- Try to install  Kubevela >=1.7 into a namespace other than vela-system
- Observe in the logs that the pre-start-hook fails, because there is no namespace "vela-system"
- Then the pod crashes

**Expected behavior**
The pre-start-hook should respect the command line option --system-definition-namespace, so the pre-start-hook is successful and the pod doesn't crash.

**KubeVela Version**
- Kubevela 1.7.5 installed via Helm Chart, but all Versions >= 1.7 seem to be affected.

**Cluster information**
- Kubernetes 1.24.9

**Comment by Somefive** [comment]
Thanks for reporting! That's a bug we should fix. But `systemDefinitionNamespace` is not preferred to be used here. Will the namespace where `vela-core` runs works for your scenario?

**Comment by csomm** [comment]
Maybe I misunderstood what `systemDefinitionNamespace` is supposed to do (or rather, what it is not supposed to do). And yes, as far as I understand it, the namespace where `vela-core` is running would need to be used for the hook.
