### ISSUE TITLE
[Feature] application_controller should be responsible for deleting application revision

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#5710]
**Is your feature request related to a problem? Please describe.**

When application is deleted, the application revision is deleted by Kubernetes following the OwnerReference mechanism. This could be slow when the system has high load. We should let application controller to handle it as well as a double check.

**Describe the solution you'd like**

Move pkg/controller/core.oam.dev/v1alpha2/application/apply.go:garbageCollection to pkg/resourcekeeper/gc.go:GarbageCollect and support cleaning up application revision when application is fully removed.

**Describe alternatives you've considered**

**Additional context**

**Comment by dhanusaputra** [comment]
hi @Somefive seems moving the package is difficult due to import cyclic between package application and package resourcekeeper
kindly help to quick check whether the draft is in the right direction
will do more improvement later, thank you
