### ISSUE TITLE
[Feature] Support skip reconcile application

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#5723]
**Is your feature request related to a problem? Please describe.**

In the case that we do not want KubeVela controller to reconcile application, we can support an annotation "controller.core.oam.dev/skip-reconcile". When application carries this annotation and the value is "true", the application controller will ignore it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Somefive** [comment]
> 

Label and functions are added here https://github.com/kubevela/pkg/pull/68.

**Comment by Mcduller** [comment]
> > 
> 
> Label and functions are added here [kubevela/pkg#68](https://github.com/kubevela/pkg/pull/68).
ok

**Comment by Somefive** [comment]
> > > 
> > 
> > 
> > Label and functions are added here [kubevela/pkg#68](https://github.com/kubevela/pkg/pull/68).
> > ok

Sorry, we have just raised the priority of this issue so it is just implemented in #5732. You can try another good first issue. Apologize for the late response.
