### ISSUE TITLE
traits 中 添加 storage 未触发应用部署

### ISSUE THREAD

**Issue by tsaiqili** [kubevela/kubevela#5764]
目的：create components
方式：直接访问Api的方式（postman）
功能：traits 中 添加 storage，如
`{
                    "type":"storage",
                    "properties":{
                        "pvc": [
                           {
                               "name":"logsDir",
                               "mountPath":"/home/logs"
                           }
                       ],
                       "emptyDir":[
                           {
                               "name":"logsDir",
                               "mountPath":"/home/logs"
                           }
                       ]
                    }
                }`
现象：api 请求返回200，实际未触发应用的部署

**Comment by chivalryq** [comment]
Please correct the markdown format with \``` code here ```

**Comment by tsaiqili** [comment]
```
{
                    "type":"storage",
                    "properties":{
                        "pvc": [
                           {
                               "name":"logsDir",
                               "mountPath":"/home/logs"
                           }
                       ],
                       "emptyDir":[
                           {
                               "name":"logsDir",
                               "mountPath":"/home/logs"
                           }
                       ]
                    }
                }
```

**Comment by tsaiqili** [comment]
kubeVela 1.7

**Comment by chivalryq** [comment]
Have you tried only attach `pvc` or only `emptyDir`? Seems the `name` of two fields conflicts

**Comment by tsaiqili** [comment]
测试过了，单独使用emptyDir 或者pvc 返回的都是http 200，未触发实际的部署

**Comment by chivalryq** [comment]
What's the API did you call? @tsaiqili

**Comment by tsaiqili** [comment]
http://xxx.xxx.xxx/v1/namespaces/ewt-testing/applications/mstsearchservice

**Comment by tsaiqili** [comment]
https://kubevela.stoplight.io/docs/kubevela/bb748c5ddcf30-create-or-update-oam-application-in-the-specified-namespace

**Comment by chivalryq** [comment]
Please provide some log from apiserver when you call the API. @tsaiqili

**Comment by tsaiqili** [comment]
找到了原因了，"name":"logsDir", logsDir 中包含了大写字母，感谢 @chivalryq 支持
