### ISSUE TITLE
Can't running addon-velaux

### ISSUE THREAD

**Issue by hautph** [kubevela/kubevela#5820]
# vela port-forward -n vela-system addon-velaux 9082:80
? There are 2 services match your filter conditions. Please choose one:
Cluster | Component | Service local | velaux | velaux
trying to connect the remote endpoint svc/velaux 9082:80 ..Forwarding from 127.0.0.1:9082 -> 80
Forwarding from [::1]:9082 -> 80

Forward successfully! Opening browser ...

Failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Comment by charlie0129** [comment]
The error on the last line shouldn't affect the actual port-forwarding. 

Have you tried opening `127.0.0.1:9082` manually?

**Comment by hautph** [comment]
i follow this document https://kubevela.io/docs/reference/addons/velaux

actualy i want to open ip_address:9082 manually, can you give for me a command

**Comment by charlie0129** [comment]
You can open that `ip_address:9082` in your web browser.

**Comment by hautph** [comment]
I run it on Ubuntu server, I using the ssh remote to the server and running it, I can't open ip_address:9082 in my web browser.

**Comment by charlie0129** [comment]
You can replace ip_address with the ip address of your ubuntu server, with the help of `--address 0.0.0.0` flag to make listen on all addresses, then open `your_ubuntu_server_ip:9082` in your web browser.

**Comment by hautph** [comment]
i was running

`vela port-forward addon-velaux -n vela-system 9082:80 --address 0.0.0.0`

how can I run with background if i exit the console. Thanks.

**Comment by charlie0129** [comment]
Try `tmux` and similar things. Note that it is not recommended. port-forwarding is only useful in temporary development environments. Otherwise, you should use something like LoadBalancer instead.

**Comment by hautph** [comment]
Thanks you, this is first time to running Kubevela, maybe I need more time to research it.
