### ISSUE TITLE
[Feature] Support CueX execution on vela cli

### ISSUE THREAD

**Issue by FogDong** [kubevela/kubevela#5862]
**Is your feature request related to a problem? Please describe.**

Currently, we can use CueX capability by importing the package, like Cue, CueX can also be used as a cli command and evaluate templates, we can add `cuex` command in `vela cli` to leverage the CueX capability.

**Describe the solution you'd like**

Add CueX command like:

```
vela cuex eval <cue file>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by FogDong** [comment]
Hi @rhzx3519 , I don't think we need all flags in `cue eval`.

This `vela cuex eval` command uses KubeVela CUE Engine to render templates, it is mainly used to let users have a consistent experience when applying components/traits/workflowsteps with this command.

**Comment by Somefive** [comment]
Close as #5562 merged.
