### ISSUE TITLE
[Feature] Support Bytebase as KubeVela addon

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#5878]
**Is your feature request related to a problem? Please describe.**

Bytebase is an open-source database DevOps tool, it's the GitLab for managing databases throughout the application development lifecycle. It offers a web-based workspace for DBAs and Developers to collaborate and manage the database change safely and efficiently.

We can make Bytebase as KubeVela addon as app developers may need this tool. The web portal is important in this case.

**Describe the solution you'd like**

The installation procss is clear:  https://www.bytebase.com/docs/get-started/install/deploy-to-kubernetes

It requires a postgres database that we can provision with this addon: https://github.com/kubevela/catalog/tree/master/experimental/addons/postgres-operator

**Describe alternatives you've considered**

We can also create a posgress database without relying on the postgres-operator.

**Additional context**

**Comment by MdSahil-oss** [comment]
@wonderflow assign this issue to me.
