### ISSUE TITLE
Failed to install Vela CLI 1.8.0

### ISSUE THREAD

**Issue by huaxk** [kubevela/kubevela#5881]
I execute script to install vela cli 1.8.0:

`curl -fsSl https://kubevela.io/script/install.sh | bash -s 1.8.0`

get error:
```
Installing v1.8.0 Vela CLI...
Downloading https://static.kubevela.net/binary/vela/v1.8.0/vela-v1.8.0-linux-amd64.tar.gz ...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to unpack Vela CLI executable.
Failed to install Vela CLI
For support, go to https://kubevela.io
```

perhaps unable to download the file: 
`https://static.kubevela.net/binary/vela/v1.8.0/vela-v1.8.0-linux-amd64.tar.gz`

**Comment by Somefive** [comment]
This should be fixed now. Could you try to reinstall it again?

**Comment by huaxk** [comment]
I successfully installed vela cli, but the next step is to execute the command to install velaux:
```
vela addon enable velaux --version=v1.8.0
```
error prompt appears:
```
Error: specified version v1.8.0 not exist
```

**Comment by Somefive** [comment]
You can try it now. The addon of velaux is not updated on time. https://github.com/kubevela/catalog/pull/676 It is related to this PR and it is merged now.

**Comment by huaxk** [comment]
Thanks, it's good job.
