### ISSUE TITLE
can't adopt helm release with chart that contain sub-chart

### ISSUE THREAD

**Issue by trueware** [kubevela/kubevela#5886]
**Describe the bug**

Installed an application through helm, there are 40 pods, and each pod has three resources: deployment, service, and confimap.
when adopt then application by "vela adopt testone --type helm", throw the following error:

$vela adopt testone --type helm
error: failed to make adoption application for resources: failed to parse adoption template: cue: marshal error: adopt.$returns.spec.components.0.properties.objects.0.metadata.namespace: cannot reference optional field: namespace

but adopt a single delpoyment is successed with the following command.
vela adopt deployment/app1 service/app1-service configmap/app1-configmap --app-name=app1

**To Reproduce**

1. Create a helm chart, including sub-charts, as follows:
   ├── testchart
    │   ├── Chart.yaml
    │   ├── charts
    │   └── values.yaml
   The charts directory contains many charts, and each chart's templates contain deployment, service, and configmap
2. release testchart with helm install
3.  adopt the release with vela adopt 

**Expected behavior**

vela can success adopt the application that install by helm
**Screenshots**

**KubeVela Version**

 v1.7.6
**Cluster information**

v1.24.8
**Additional context**

**Comment by Somefive** [comment]
Could you try to use the latest v1.8.0 CLI and see if this still happens? We have made some fixes which might be related to this one in #5728

**Comment by trueware** [comment]
> Could you try to use the latest v1.8.0 CLI and see if this still happens? We have made some fixes which might be related to this one in #5728

I tested the master branch code in the local development environment and found that the problem has been resolved. Thank you very much.

**Comment by trueware** [comment]
I tested with latest v1.8.0 CLI in the local development environment and found that the problem has been resolved. Thank you very much.
but the output log contain an error message as below:
E0420 10:01:20.024850   43441 compiler.go:194] failed to load external packages for cuex default compiler: the server could not find the requested resource
I0420 10:01:20.214457   43441 apply.go:121] "creating object" name="testone" resource="core.oam.dev/v1beta1, Kind=Application"

**Comment by Somefive** [comment]
Oh, this is an error message that you can omit for now. It is a very advanced feature planned in the next version. We will optimize it later.
