### ISSUE TITLE
[Feature] A proposed change to automatically add topology policy rules to addon

### ISSUE THREAD

**Issue by zhaohuiweixiao** [kubevela/kubevela#5932]
**Is your feature request related to a problem? Please describe.**
The current implementation will automatically add the topology policy for the addon which could be deployed to the runtime clusters but do not have the topology policy, which will modify the user's addon and cause the template set in the addon to be inconsistent with the actual rendered template content (the topology policy is added). 
Then the rules for defining addon are not completely white-box, and user-defined addon are different from the ones actually rendered.

**Describe the solution you'd like**

Considering that there is no way to define different topology policies based on clusters parameter in the yaml template of the addon, it is necessary to keep the logic of automatically adding the topology policy to the addon, but it is recommended to only apply this change to yaml addon to minimize the black-box behavior.

This way we can achieve a completely white-box definition of cue type addons, where what you see is what you get for cue type addons.

Therefore, it is recommended to restrict the rules that automatically add topology strategy to addons to be valid only for the yaml type.

**Additional context**

the model-serving template in addon catalog:
![image](https://user-images.githubusercontent.com/6092586/234799107-d8f6e3d4-d64c-4ff9-9d1b-28a64797b134.png)

the rendered template after rendered:
![image](https://user-images.githubusercontent.com/6092586/234798972-fbf5ac12-7edb-4e45-b78a-b636bb73a9d0.png)

**Comment by Somefive** [comment]
I agree with that.

**Comment by zhaohuiweixiao** [comment]
This change will affect addons that do not have a cue template file but iruntimeClass is true. I've screened all the official addons, and found the kruise-rollout is only one of those cases. Also, the rollout and netlify addon has not template file, but their runtimeClass are runtime true. for resolve above, i have submmit a pr(https://github.com/kubevela/catalog/pull/684/files)
