### ISSUE TITLE
In workflowrun, the status of apply-app step is failed, but app status in vela cli shows ready

### ISSUE THREAD

**Issue by xiaohuiliao** [kubevela/kubevela#5966]
**Describe the bug**
apply-app step failed in workflowrun, but app is running well from vela cli:

**To Reproduce**
I create the workflowrun in velaux web page, the yaml looks like:
`
- name: build-push-image-test
  alias: build-push-image-test
  type: build-push-image
  description: ''
  orderIndex: 0
  dependsOn: null
  properties:
    context:
      branch: main
      git: github.com/FogDong/simple-web-demo
    credentials:
      image:
        key: .dockerconfigjson
        name: <mysecret>
    dockerfile: ./Dockerfile
    image: >-
      <my image url>
    kanikoExecutor: oamdev/kaniko-executor:v1.9.1
    verbosity: info
- name: apply-app-test
  alias: apply-app-test
  type: apply-app
  description: ''
  orderIndex: 0
  dependsOn: null
  properties:
    data:
      apiVersion: core.oam.dev/v1beta1
      kind: Application
      metadata:
        name: my-vela-app-ci-wkfl
        namespace: <my namespace >
      spec:
        components:
          - name: my-web-ci-wkfl
            namespace: <my namespace>
            properties:
              image: >-
                <my image url>
              imagePullSecrets:
                - <my secret>
              ports:
                - expose: true
                  port: 80
            type: webservice
`

**Expected behavior**
apply-app status is ok

**Screenshots**
![image](https://user-images.githubusercontent.com/30194619/236795259-af686fa3-93af-44ef-97d2-9d4872e1ed3a.png)

![image](https://user-images.githubusercontent.com/30194619/236795397-1f8042f0-4d6d-4425-96a0-022b9d60155a.png)

![image](https://user-images.githubusercontent.com/30194619/236795296-7b149e0b-4d1a-4874-aaf7-cbaaf2400345.png)

**KubeVela Version**
CLI Version: 1.8.0
Core Version: 1.8.1
GitRevision: git-fcd721ff
GolangVersion: go1.19.8

**Cluster information**
![image](https://user-images.githubusercontent.com/30194619/236795182-4a58dcf2-bbf1-46eb-b0f3-a5bdd4e772fb.png)

**Additional context**

**Comment by matrixfish** [comment]
It's the same to me
