### ISSUE TITLE
[Feature] A proposal to refactor addon dependency installation logic

### ISSUE THREAD

**Issue by zhaohuiweixiao** [kubevela/kubevela#5967]
**Is your feature request related to a problem? Please describe.**
There are a few problems with the current addon dependency installation logic:

1. Locally installed addon will be overwritten by upstream dependent addon installation logic
2. .  In cases where a addon has multiple topologies(such as loki、prometheus-server),  using one of them as the installation clusters of the current addon is not accurate
3.  When a addon(such as loki) that can be installed on a subcluster depends on a addon(such as o11y-definitions) that can only be installed on the local cluster, installing the loki addon may change the clusters parameter of the o11y-definitions addon, which makes no sense since the o11y-definitions addon itself does not have a clusters parameter

**Describe the solution you'd like**
1. In the first case, add a check whether it is a local install, and if it is a local install, don't override it.
2. In the second case, change the addon's clusters parameter to get it from the secret file
3. In the third case,  add a test of whether the addon has a clusters parameterr

To summarize, the addon dependency installation logic will been refactored as follows:
![image](https://user-images.githubusercontent.com/6092586/236804825-da01fb7f-30d9-46fd-a8f3-e724a1e6d415.png)

**Describe alternatives you've considered**
For the third case, the method of modifying the topology policy of the application corresponding to the addon was considered, but when combing all the addon definitions in catalog repository, it was found that there was a case that a addon had more than one topology policy, so the method could not be implemented.

**Additional context**

second case:
![image](https://user-images.githubusercontent.com/6092586/236802212-2548a929-72cd-40a8-8cbb-45d7b2372dd3.png)
third case:
![image](https://user-images.githubusercontent.com/6092586/236802289-ebbbdcca-3773-4466-8301-c7d1c3ac0951.png)

**Comment by wangyikewxgm** [comment]
The solution is very clear, I agree with this proposal.
