### ISSUE TITLE
[Feature] Relax the maxDepth constraint for resource topology

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#6014]
**Is your feature request related to a problem? Please describe.**

In pkg/velaql/providers/query/tree.go, we have 
```golang
	if depth > maxDepth {
		klog.Warningf("listing application resource tree has reached the max-depth %d parentObject is %v", depth, parentResource)
		return nil, nil
	}
```

This prevent the user's query for the resource topology going too deep. The default value for `maxDepth` is 5. However, there is no place that could be used to configure this `maxDepth` value. I would suggest we could support reading "KUBEVELA_QUERYTREE_MAXDEPTH" environment variable and set it to 5 if not exist. This will let users be able to configure the query depth in their environment if wanted and configure it in the velaux apiserver as well.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qashlan** [comment]
I can take this

**Comment by zhaohuiweixiao** [comment]
I expect maxDepth to be extracted into the configuration. And I hope to achieve this function, can you give it to me?

**Comment by qashlan** [comment]
@Somefive does this change has any place in the docs ?

**Comment by Somefive** [comment]
@qashlan  No, I do not think we need to update the docs. It should be an underlying configuration. But it is absolutely okay to add some NOTICE section in the documentation if you want.

**Comment by Somefive** [comment]
Close as #6039 merged.
