### ISSUE TITLE
[Feature] Indicate the resources to be dispatched to which cluster

### ISSUE THREAD

**Issue by erolg** [kubevela/kubevela#6032]
**Is your feature request related to a problem? Please describe.**

We are developing custom components and traits to provide the capability to deploy cloud resources with the application. Sometimes we need to control where CRDs are generated. Trait definition has a "controlPlaneOnly" attribute which helps us to achieve what we want. But we can't do it for component definitions. 

If the desired resources are optional we provide the resource with a custom trait with the "controlPlaneOnly" attribute. But sometimes resources are mandatory for the component and we can't provide it as a trait.

For example, we developed a web service component. The component deploys the application to the remote clusters but also it generates auxiliary resources to bootstrap the observability configuration for the application. These CRDs are don't need on the remote clusters, we want to dedicate these to the hub cluster. 

**Describe the solution you'd like**

@Somefive : 
> One of the way that could be possible is to add some specific annotation to the rendered resource, like `app.oam.dev/cluster: local` and let the controller to be able to recognize that and put it on the hub cluster, as we cannot design only one field to describe multiple resources rendered by the componentdefinition.

**Comment by Somefive** [comment]
I think one of the way is to add special annotation/label to the rendered resources. For example set "app.oam.dev/cluster: local" will force the rendered resource to be dispatched to the hub cluster.
