### ISSUE TITLE
Certificate expired for *.kubevela.net

### ISSUE THREAD

**Issue by h7kanna** [kubevela/kubevela#6037]
**Describe the bug**
vela install -y fails with 
x509: certificate has expired or is not yet valid: “*.kubevela.net” certificate is expired

**To Reproduce**

**Expected behavior**
No certificate error

**Screenshots**
Check Requirements ...
Installing KubeVela Core ...
Error: loading the helm chart of kubeVela control plane failure, error retrieving Helm Chart at https://charts.kubevela.net/core/vela-core-1.9.0-alpha.5.tgz: Get "https://charts.kubevela.net/core/vela-core-1.9.0-alpha.5.tgz": x509: certificate has expired or is not yet valid: “*.kubevela.net” certificate is expired

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
updated thanks for reminding
