### ISSUE TITLE
Unable to return the PodIP When using VelaQL component-pod-view in vela 1.8

### ISSUE THREAD

**Issue by flysqrlboy** [kubevela/kubevela#6054]
**Describe the bug**

When using VelaQL component-pod-view, it's unable to return the IP address of the pod.

**To Reproduce**

Sending an HTTP request ：

 http://{velauxIP:PORT}/api/v1/query?velaql=component-pod-view{appNs=vela-system,appName=vela-xxx-client,name=vela-xxx-client}

The returned data is as follows:
```
{
    'podList': [
        {
            'cluster': 'local',
            'component': 'vela-xxx-client',
            'metadata': {
                'creationTime': '2023-05-27T07:52:29Z',
                'labels': {
                    'app': 'vela-xxx-client',
                    'pod-template-hash': '5ff94d7495'
                },
                'name': 'vela-xxx-client-5ff94d7495-gnjjd',
                'namespace': 'vela-system',
                'version': {
                    'deployVersion': '',
                    'publishVersion': ''
                }
            },
            'status': {
                'phase': 'Running'
            },
            'workload': {
                'apiVersion': 'apps/v1',
                'kind': 'ReplicaSet',
                'name': vela-xxx-client-5ff94d7495',
                'namespace': 'vela-system'
            }
        }
    ]
}
```
But according to the example in this [documentation ](https://kubevela.net/zh/docs/platform-engineers/system-operation/velaql), the returned response should include the PodIP field(status.podIP).
![image](https://github.com/kubevela/kubevela/assets/7646548/e0ddc751-cde7-489b-b3cb-c20b5a5f8e3f)

**Expected behavior**

 The response data for the `component-pod-view` velaql  request should include the PodIP .
**Screenshots**

**KubeVela Version**
CLI Version: 1.8.0
Core Version: 1.8.0
GitRevision: git-fcd721ff
GolangVersion: go1.19.8

**Cluster information**

k8s version : v1.25.7
**Additional context**

Velaux version: v1.8.1

**Comment by chivalryq** [comment]
The document's link is broken. Can you check again?

**Comment by flysqrlboy** [comment]
> The document's link is broken. Can you check again?

the document link: https://kubevela.net/zh/docs/platform-engineers/system-operation/velaql

**Comment by flysqrlboy** [comment]
Thanks！ I have found that the issue has been fixed.
How can I apply these changes to the vela-core that I'm currently using?

**Comment by Somefive** [comment]
> 

You have several ways to do it:
1. Build the docker image for vela-core on master branch.
2. Cherry-pick this commit to your forked branch and build docker image for your branch.
3. You can wait for a while. We will make a release of v1.9.0-beta.2 in this week and will contain this fix.

**Comment by Somefive** [comment]
FYI, for this issue, I think the fix does not need to build a new image. You can just apply this YAML in your cluster and it should work directly. https://github.com/kubevela/kubevela/blob/master/charts/vela-core/templates/velaql/component-pod.yaml
