### ISSUE TITLE
[Feature] add dapr addon with pub/sub trait 

### ISSUE THREAD

**Issue by resouer** [kubevela/kubevela#609]
Per offline discussed with @artursouza , let's ship dapr trait as a built-in capability. This will make kubevela the best platform to ship dapr apps.

**Comment by yaron2** [comment]
Hi, Dapr maintainer here. I'm excited to see Dapr integrated as a trait in Kubevela, let me know how we can help.

**Comment by resouer** [comment]
@yaron2 Thanks! We also feel excited about it. Assigning this task to @hongchaodeng who has already been working on this design internally.

**Comment by mhoad** [comment]
@hongchaodeng is this something that you are looking to include as a part of the 1.0 release? I see it on the Alpha release roadmap project but not tagged in the 1.0 release milestone I wasn't sure which one I should be referencing.

**Comment by wonderflow** [comment]
@mhoad  We'll support that in v1.1

**Comment by hongchaodeng** [comment]
Hi @mhoad , we are planning to add it in v1.1

**Comment by hongchaodeng** [comment]
ref: https://github.com/oam-dev/kubevela/issues/1425

We are considering to adopt Dapr to support observability features.

**Comment by allenhaozi** [comment]
> @wonderflow and I have discussed the next steps for shipping Dapr applications with ease on KubeVela. Here is an update of our plan on KubeVela project:
> 
> * Currently to ship a Dapr application on k8s involves [multiple manual steps](https://github.com/dapr/quickstarts/tree/v1.0.0/hello-kubernetes). For example
>   
>   * setup a redis/mysql resource
>   * setup the Deployment/Service of the app
>   * setup the Dapr Component resource which needs manually filling in the parameters (e.g. connection, credentials) from redis/mysql resource.
> * We could simplify Dapr experience on KubeVela by adding a Dapr trait that looks like below:
>   ```yaml
>   kind: Application
>   components:
>   - name: nodejs-app
>     type: webservice
>     properties:
>       image: dapriosamples/hello-k8s-node:latest
>     traits:
>     - type: dapr
>       properties:
>         resourceType: state.redis
>         provider: crossplane
>   
>   - name: python-app
>     type: webservice
>     properties:
>       image: dapriosamples/hello-k8s-python:latest
>     traits:
>     - type: dapr
>       properties:
>         resourceType: state.redis
>         provider: crossplane
>   ```
>   
>   
>   The Dapr trait will have a backing controller which automatically creates the resources needed and fills the necessary metadata (e.g. redisHost, redisPassword).
> 
> To sum it up, we will add two things:
> 
> * Dapr trait
> * Dapr controller

Dapr trait is responsible for rendering a `Dapr Componet` ?  any other tasks ? 
If I already have Dapr Operator installed, the second can be ignored ? 
I recently designed a Service Binding and am learning about Dapr

**Comment by hongchaodeng** [comment]
Hi @allenhaozi . 

> Dapr trait is responsible for rendering a Dapr Componet ? any other tasks ?

Yes. The Dapr trait will have a backing controller which automatically creates the resources needed and fills the necessary metadata (e.g. redisHost, redisPassword).

> If I already have Dapr Operator installed, the second can be ignored ?

What's the Dapr Operator you meant here? If you mean [the one from Dapr project](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/), they are for different purposes. They won't conflict.

> I recently designed a Service Binding and am learning about Dapr

Cool! One of the main tasks of the Dapr trait is to handle service binding, e.g. filling url/password for Dapr Component resource. If you are interested, we can involve you in the development work of the Dapr trait controller. It will be pure open source collaboration.

**Comment by artursouza** [comment]
> Hi @allenhaozi .
> 
> > Dapr trait is responsible for rendering a Dapr Componet ? any other tasks ?
> 
> Yes. The Dapr trait will have a backing controller which automatically creates the resources needed and fills the necessary metadata (e.g. redisHost, redisPassword).
> 
> > If I already have Dapr Operator installed, the second can be ignored ?
> 
> What's the Dapr Operator you meant here? If you mean [the one from Dapr project](https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/), they are for different purposes. They won't conflict.
> 
> > I recently designed a Service Binding and am learning about Dapr
> 
> Cool! One of the main tasks of the Dapr trait is to handle service binding, e.g. filling url/password for Dapr Component resource. If you are interested, we can involve you in the development work of the Dapr trait controller. It will be pure open source collaboration.


Dapr installation (sidecar injector, placement service, operator, etc) is a cluster concern, so an app does not "install Dapr for itself". There are some conversations about making Dapr installation scoped per app but that is an ongoing matter and not sure if we will make that change in Dapr.

Just to make it clear that the Dapr sidecar is per app (Pod) once Dapr is installed in the cluster.

**Comment by abserari** [comment]
It seems so good, so it would be support in v1.2?

**Comment by wonderflow** [comment]
@yaron2 @ab @artursouza  Sorry for the delay, we're looking for some good user story. All I can think of right now is to simplify the installation step of dapr. That's not make any different with just using `helm install`. We hope to find some more values.

Do you have any better idea? Or do the users from dapr community have some scenarios that with KubeVela can make something better？ I think we will have more strong motivation if we can figure out that. Thanks.

**Comment by geffzhang** [comment]
Have you had a plan to support it recently, and with this feature, I really want to use kubevela power

**Comment by yaron2** [comment]
> @yaron2 @ab @artursouza Sorry for the delay, we're looking for some good user story. All I can think of right now is to simplify the installation step of dapr. That's not make any different with just using `helm install`. We hope to find some more values.
> 
> Do you have any better idea? Or do the users from dapr community have some scenarios that with KubeVela can make something better？ I think we will have more strong motivation if we can figure out that. Thanks.

I think it could be great to add an eventing system into KubeVela that's backed by Dapr. Since you already have the concept of an Application, you could abstract the operational concerns of using needing to setup Dapr pub/sub and automatically inject sidecars with the proper configuration in place. It could be a pub/sub trait that enables this functionality.

**Comment by wonderflow** [comment]
> I think it could be great to add an eventing system into KubeVela that's backed by Dapr. Since you already have the concept of an Application, you could abstract the operational concerns of using needing to setup Dapr pub/sub and automatically inject sidecars with the proper configuration in place. It could be a pub/sub trait that enables this functionality.

Thanks, it's good idea!

**Comment by wonderflow** [comment]
@yaron2  BTW, do you have some demo from dapr about the pub-sub story? Maybe someone from KubeVela community will be interested about it and contribute.

In my view, this feature including three parts:

1. add a dapr addon https://kubevela.io/docs/platform-engineers/addon/intro  this will including the dapr Controller（helm chart） along with the eventing system server
2. write traitdefinition for the pub and sub injection, it can apply to webservice component for the first step.
3. add some demo (examples) and write some docs about the usage.

**Comment by chwetion** [comment]
I am interested in this feature, I can try to implement it.

**Comment by wonderflow** [comment]
> I am interested in this feature, I can try to implement it.

Great, you can request more details here if there's any need. Thanks and looking forward to your contributions!

**Comment by yaron2** [comment]
> @yaron2 BTW, do you have some demo from dapr about the pub-sub story? Maybe someone from KubeVela community will be interested about it and contribute.
> 
> In my view, this feature including three parts:
> 
> 1. add a dapr addon https://kubevela.io/docs/platform-engineers/addon/intro  this will including the dapr Controller（helm chart） along with the eventing system server
> 2. write traitdefinition for the pub and sub injection, it can apply to webservice component for the first step.
> 3. add some demo (examples) and write some docs about the usage.

This is a good video: https://www.youtube.com/watch?v=PwA6UbeneE4.

Other than that, I suggest to read this overview article: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/.
