### ISSUE TITLE
Unable to install observability components

### ISSUE THREAD

**Issue by gowtham500** [kubevela/kubevela#6113]
Hello team,

## Platform 

Red Hat Enterprise Linux Server release 7.9 (Maipo)

## kubevela version
```
CLI Version: 1.9.0-beta.3
Core Version: 1.8.2
GitRevision: git-c0cbe24d
GolangVersion: go1.19.9
```
## kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Downloaded latest kubevela and installed it via helm. Installation succeeded.
- I tried to follow steps to setup monitoring as in https://kubevela.io/docs/platform-engineers/operations/o11y/installation/
- kubestate metrics and node exporter - add ons installed successfully.

` vela addon enable prometheus-server`  --> `Error: specified version 0.2.6 not exist`

Please let me know as to how to resolve this issue.

**Comment by Somefive** [comment]
I saw the latest version of prometheus-server addon is v0.3.2. https://github.com/kubevela/catalog/blob/93c2ae10203f67058636a384f278b06c9d48f379/addons/prometheus-server/metadata.yaml#L2

Could you try running `vela addon list` and `vela addon registry list` and show the registry and available addons?

**Comment by gowtham500** [comment]
@Somefive please find output below

`vela addon list`
![image](https://github.com/kubevela/kubevela/assets/30665730/f2b05846-196f-4c2a-9c4c-a604bf896514)


`vela addon registry list`

![image](https://github.com/kubevela/kubevela/assets/30665730/41cb7a3f-4330-4915-b061-17f748af1dfa)

### Trying to enable add on with version

`vela addon enable prometheus-server -v v0.3.2` -- > `Error: specified version 0.2.6 not exist`

### Trying to enable add on with verbose

```
GET https://<IP>:6443/apis/core.oam.dev/v1beta1/namespaces/vela-system/applications/o11y-definitions
INFO vela-cli 2023-06-13T00:44:53-04:00 [/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.3/transport/round_trippers.go:574] Response Status: 404 Not Found in 185 milliseconds
```

### My assumption was it was looking for the addon o11y-definitions

`vela addon enable o11y-definitions`  ---> `Error: render addon definitions fail: fail to render definition: grafana-access.cue in cue's format: invalid definition spec: json: unknown field "podDisruptive"`

**Comment by Somefive** [comment]
Ah, I see the issue here. The 0.2.6 refers to o11y-definition? And the grafana-access.cue seems to have some error fields which are rejected by the latest CLI. I have just submitted a bug fix. You can either try the fix a bit later (after it is merged) or temporarily use a old version CLI where the check is not enabled.

Ref: https://github.com/kubevela/catalog/pull/700

**Comment by gowtham500** [comment]
@Somefive  Thanks, I used older version of kubevela - `1.8.2` and it has resolved the issue.
