### ISSUE TITLE
helm repo 地址无法作用于vela安装插件时候的配置文件

### ISSUE THREAD

**Issue by SevenEarth** [kubevela/kubevela#6125]
**Describe the bug**
helm repo 地址无法作用于vela安装插件时候的配置文件
已经将helm的repo地址更新到最新的地址，但是安装terraform插件还是失败，
<img width="1719" alt="image" src="https://github.com/kubevela/kubevela/assets/45937856/ea1ce68e-26ed-4803-9905-5aeaacab0ff7">
<img width="1389" alt="image" src="https://github.com/kubevela/kubevela/assets/45937856/1af96dff-3347-4e99-b7ac-485d94fd2e08">
<img width="498" alt="image" src="https://github.com/kubevela/kubevela/assets/45937856/3048356c-0f2e-49e6-8043-b5538e0a4fe3">

**KubeVela Version**
<img width="1061" alt="image" src="https://github.com/kubevela/kubevela/assets/45937856/1a5a669a-9658-465c-b387-c22a5a2104b6">

**Cluster information**
<img width="1724" alt="image" src="https://github.com/kubevela/kubevela/assets/45937856/49c01a2d-b5ab-479e-883f-8156d00836f1">

**Comment by Somefive** [comment]
I guess we need to change the charts.kubevela.net/addons to kubevela.github.io/catalog/official as the old oss address is dropped now.

**Comment by wonderflow** [comment]
Notice: the "hub.kubevela.net", "charts.kubevela.net" and "addons.kubevela.net" will not be served in the future.

For docker images in "hub.kubevela.net", replace it with "docker.io" or "ghcr.io/kubevela".
For helm charts in "charts.kubevela.net", replace it with "kubevela.github.io/charts".
For addons in "addons.kubevela.net", replace it with "kubevela.github.io/catalog/official".
You can run the following command to update your addon registry.

```
vela addon registry delete KubeVela
vela addon registry add KubeVela --type helm --endpoint=https://kubevela.github.io/catalog/official
vela addon registry add experimental --type helm --endpoint=https://kubevela.github.io/catalog/experimental
```
