### ISSUE TITLE
velaux 1.9.1  Configure the gateway, and convert the port into a string

### ISSUE THREAD

**Issue by Louse-luo** [kubevela/kubevela#6165]
**Describe the bug**

velaux 1.9.1  Configure the gateway, and convert the port into a string
**To Reproduce**

cannot generate manifests from components and traits: evaluate template trait=gateway app=third-app1-prod: invalid template of trait gateway after merge with parameter and context: outputs.service.spec.ports.0.port: conflicting values "8090" and int (mismatched types string and int) (and 3 more errors)
**Expected behavior**

**Screenshots**

**KubeVela Version**
1.9.1

**Cluster information**

**Additional context**

**Comment by chivalryq** [comment]
Could you provide a screenshot?

**Comment by Kolossi** [comment]
@Louse-luo : please provide an example manifest which fails, thanks.

**Comment by wonderflow** [comment]
Same issue reported in Dingtalk, I'm copy-pase the screenshoots here:


![image](https://github.com/kubevela/kubevela/assets/2173670/add175d5-2e52-4c6c-bebf-51c669a188da)


![image](https://github.com/kubevela/kubevela/assets/2173670/2b475f07-a7d1-4b45-9095-f554d3abf967)

**Comment by Kolossi** [comment]
thanks @wonderflow do we know the last version where this _didn't_ happen?

and can you publish a full repro for getting to this state shown in the screenshot?

**Comment by wonderflow** [comment]
@Kolossi Thanks Paul for investigating this issue. The reporter didn't send the full repro, so I can't provide that.

I checked the gateway trait: 

https://github.com/kubevela/kubevela/blob/v1.9.2/vela-templates/definitions/internal/trait/gateway.cue#L149

It's defined as `http: [string]: int` in CUE, AFAIK, the port must be a `int`, why it become a string in this case?

**Comment by Kolossi** [comment]
Indeed, I looked and saw the same.  

Also, my changes to gateway were included in v1.9.0 and doing a diff to previous 1.8.2, there's nothing changed around port - https://github.com/kubevela/kubevela/compare/v1.8.2...v1.9.1#diff-eb6e43f0e2cf800a96e1dac66f3f4871067f865d5c694d9efa5c84cb2529a5a0

Is there something hardcoded in velaux about ports which has broken (again I tried a github search and couldn't find anything).

🤔

**Comment by wonderflow** [comment]
ping @chivalryq @barnettZQG , will it possible that's a bug caused by velaux?

**Comment by chivalryq** [comment]
I will dig into this recently.

**Comment by lxkaka** [comment]
same problem in 1.9.1； now we degrade to 1.8.1 ; keep an eye  on this

**Comment by Kolossi** [comment]
@lxkaka : can you post the steps to reproduce this issue please

**Comment by lxkaka** [comment]
@Kolossi 
![image](https://github.com/kubevela/kubevela/assets/10549664/2a5a866e-6a27-4bb2-814b-ba5f3d3e6430)
in 1.9.1 the port will be render to "8888" in yaml

**Comment by Kolossi** [comment]
@chivalryq I really can't see anything in either kubevela or velaux diff between 1.8.1 and 1.9.1.  Perhaps it's a change in the underlying cue version that has changed the behaviour?  I'm going to have to leave this with you.

**Comment by chivalryq** [comment]
@chivalryq No worry. Will take care of this.

**Comment by chivalryq** [comment]
I try to repro with: 
velaux: v1.9.1, run the server locally.
vela-core v1.9.3
gateway trait: master.

When creating trait, velaux send the request to apiserver with the value of string type. 

<img width="1019" alt="image" src="https://github.com/kubevela/kubevela/assets/47812250/c7c6e2e4-ec2b-4ce9-90c6-fe3898b4bca3">

**Comment by chivalryq** [comment]
OpenAPI schema is like below. It's like there's something wrong in grammar. Still investigating.

```json
{
  "properties": {
    "class": {
      "default": "nginx",
      "description": "Specify the class of ingress to use",
      "title": "class",
      "type": "string"
    },
    "classInSpec": {
      "default": false,
      "description": "Set ingress class in ''.spec.ingressClassName'' instead of ''kubernetes.io/ingress.class'' annotation.",
      "title": "classInSpec",
      "type": "boolean"
    },
    "domain": {
      "description": "Specify the domain you want to expose",
      "title": "domain",
      "type": "string"
    },
    "gatewayHost": {
      "description": "Specify the host of the ingress gateway, which is used to generate the endpoints when the host is empty.",
      "title": "gatewayHost",
      "type": "string"
    },
    "http": {
      "additionalProperties": {
        "type": "integer"
      },
      "description": "Specify the mapping relationship between the http path and the workload port",
      "title": "http",
      "type": "object"
    },
    "secretName": {
      "description": "Specify the secret name you want to quote to use tls.",
      "title": "secretName",
      "type": "string"
    }
  },
  "required": [
    "http",
    "class",
    "classInSpec" [],
    "type"
    :
    "object"
    }
```

**Comment by lxkaka** [comment]
@chivalryq we will keep an eye on this

**Comment by chivalryq** [comment]
Openapi schema is not wrong. It's a k9s [bug](https://github.com/derailed/k9s/issues/2167).
