### ISSUE TITLE
Clicking the hyperlink appears page not found

### ISSUE THREAD

**Issue by liuzel01** [kubevela/kubevela#6172]
**Describe the bug**

When I enter the [official documentation](https://kubevela.io/zh/docs/install/), I am unable to navigate through the hyperlinks here. 

- [独立安装](https://kubevela.io/zh/docs/install/installation/standalone)
- [集群安装](https://kubevela.io/zh/docs/install/installation/kubernetes)

**To Reproduce**

1. Access this page.
2. Click the link here.
3. "Page not found" appears.

![image](https://github.com/kubevela/kubevela/assets/26734740/43d36ae6-a34f-4ee1-aaf3-0d98b21c8778)

**Expected behavior**

Normal hyperlink navigation.

**Screenshots**

![image](https://github.com/kubevela/kubevela/assets/26734740/ddc30854-d337-4fc5-95a9-c0779fde6d37)

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
The righe link is: https://kubevela.io/zh/docs/installation/standalone/

Your link is: https://kubevela.io/zh/docs/install/installation/standalone

Seems there's an extra "install" prefix .

**Comment by wonderflow** [comment]
It should be a doc link bug.

**Comment by ali-dot-com** [comment]
Your links appears to be invalid. Correct links are as follows:

1st link: https://kubevela.io/zh/docs/installation/standalone/
2nd link: https://kubevela.io/zh/docs/installation/kubernetes/

**Comment by nikhilchauhangithub** [comment]
@ali-dot-com  kindly assign this issue to me

**Comment by chivalryq** [comment]
@nikhilchauhangithub You can fix the link in the https://github.com/kubevela/kubevela.io

**Comment by nikhilchauhangithub** [comment]
i created a pull request for issue  #6172 kindly look into it
