### ISSUE TITLE
hub.kubevela.net 's site SSL cert is expired

### ISSUE THREAD

**Issue by iambocai** [kubevela/kubevela#6222]
**Describe the bug**

hub.kubevela.net 's site SSL Cert is Expired

**To Reproduce**

1. Open [hub.kubevela.net](https://hub.kubevela.net/v2/oamdev/cloudshell-operator/manifests/v0.3.0)
7. See error

**Expected behavior**

[hub.kubevela.net](https://hub.kubevela.net/v2/oamdev/cloudshell-operator/manifests/v0.3.0) should be accessble by https. 

**Screenshots**

![image](https://github.com/kubevela/kubevela/assets/2259715/c4ea9f10-4118-42ad-a6bf-e2603c926f5a)

cloudshell addon install failed:
![image](https://github.com/kubevela/kubevela/assets/2259715/66de976b-9ab8-4eb0-9827-c9f0c55adfd5)

**KubeVela Version**

1.8.0

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
Yes, it's deprecated, please use "docker.io" or "ghcr.io/kubevela" registry instead.

https://kubevela.io/docs/developers/references/devex/faq#why-things-of-httpskubevelanet-is-out-of-date
