### ISSUE TITLE
hyperlink path problem [en]

### ISSUE THREAD

**Issue by nikhilchauhangithub** [kubevela/kubevela#6238]
Standalone and Kubernetes hyperlink error in page https://kubevela.io/docs/install

https://kubevela.io/docs/install/installation/standalone replace this with https://kubevela.io/docs/installation/standalone
https://kubevela.io/docs/install/installation/kubernetes replace this with https://kubevela.io/docs/installation/kubernetes/

**Screenshots**

**Comment by nikhilchauhangithub** [comment]
i am working on it

**Comment by chivalryq** [comment]
Fixed in https://github.com/kubevela/kubevela.github.io/issues/1268
