### ISSUE TITLE
Incorrect hyperlinks in documentation

### ISSUE THREAD

**Issue by vmary2014** [kubevela/kubevela#6241]
**Describe the bug**
There appears to be an issue with the hyperlinks on the documentation

**To Reproduce**

1. Go to https://kubevela.io/docs/end-user/workflow/overview/ for example
2. At the bottom, select any link
3. Current issue:
![image](https://github.com/kubevela/kubevela/assets/7021103/0f4d9beb-3f79-4ea0-af38-02f9fb770239)

<hr/>

It is worth noting that the navigation links at the bottom of the page, under `Next`, appear to be working:
![image](https://github.com/kubevela/kubevela/assets/7021103/a8fd070a-b6f6-4b16-9be7-70aecdcd2ff9)

It seems that the hyperlinks add an extra element in the url path, in this case it adds `overview`

**Comment by chivalryq** [comment]
Fixed in https://github.com/kubevela/kubevela.github.io/issues/1268
