### ISSUE TITLE
Vela CLI is using stderr to print the output

### ISSUE THREAD

**Issue by pranavek** [kubevela/kubevela#6268]
**Describe the bug**
It seem like some commands in`vela` CLI are using stderr IO channel for printing the output. I'm not sure if this was by design or a conscious choice.

**Expected behavior**
 Use stdout to print the output

**Screenshots**
<img width="1018" alt="Screenshot 2023-08-14 at 3 53 04 PM" src="https://github.com/kubevela/kubevela/assets/6043543/efaf5938-db6c-4dd9-a0fc-7b17bae0aa8a">

**KubeVela Version**
CLI Version: 1.9.5

**Comment by chivalryq** [comment]
I think this is caused by we are using `cmd.Print` series function in `references/cli/def.go` which try to get out writer or fallback to stderr.

```go
// Print is a convenience method to Print to the defined output, fallback to Stderr if not set.
func (c *Command) Print(i ...interface{}) {
	fmt.Fprint(c.OutOrStderr(), i...)
}
```

And we are not setting by cmd.SetOut()

**Comment by pranavek** [comment]
Got it. I will set stdout in Cobra cmd object and will raise a PR.
