### ISSUE TITLE
[BUG] Namespace gets overwritten

### ISSUE THREAD

**Issue by hprotzek** [kubevela/kubevela#6269]
I think the problem is related to this change https://github.com/kubevela/kubevela/pull/6228

We have a Velero backup component and set the namespace fixed in the cue template of the component. 

```
#backupMetadata: {
		name:      "\(context.namespace)--\(context.name)"
		namespace: "velero"
	}
```

With kubevela 1.9.3 this still works, but after upgrade to 1.9.5, the namespace gets overwritten by the default namespace.

**Comment by wonderflow** [comment]
It's reverted in https://github.com/kubevela/kubevela/pull/6247 , does it work?

**Comment by hprotzek** [comment]
Thanks @wonderflow, in 1.9.6 it works again.
