### ISSUE TITLE
addon  enable prometheus-server error

### ISSUE THREAD

**Issue by henkuaifacai** [kubevela/kubevela#6295]
[root@master01 ~]# vela  addon  list  | grep prome                       
prometheus-server               KubeVela        An open-source monitoring system with a dimensional data mod... [v0.3.2]                        -               
[root@master01 ~]# vela addon enable prometheus-server  
Error: specified version 0.3.0 not exist
[root@master01 ~]# vela addon enable prometheus-server  --version  v0.3.2
Error: specified version 0.3.0 not exist

[root@master01 ~]# vela  version
CLI Version: 1.9.6
Core Version: 1.9.6
GitRevision: git-9c57c098
GolangVersion: go1.19.12

kubernetes Version: v1.23.8

**Comment by gogeof** [comment]
Not only prometheus-server, but also loki and grafana will report this error when installed.

**Comment by elamaran11** [comment]
Any luck with this issue?

**Comment by gw-lgunta** [comment]
The prometheus-server has dependency on o11y-definitions addon, which is in turn has dependency on vela-prism addon. To install `prometheus-server` addon, you need to install the following addon  `vela addon enable vela-prism` , `vela addon enable o11y-definitions` and then `vela addon enable prometheus-server`

**Comment by chivalryq** [comment]
@gw-lgunta has mentioned a walkaround by enable them on by one 

Here's a bug fixing PR. https://github.com/kubevela/catalog/pull/726

**Comment by elamaran11** [comment]
Thankyou for the information. It works now
