### ISSUE TITLE
镜像拉不下来了

### ISSUE THREAD

**Issue by dockercore** [kubevela/kubevela#6325]
**Describe the bug**

docker pull hub.kubevela.io/oamdev/cloudshell-operator:v0.3.0
Error response from daemon: Get "https://hub.kubevela.io/v2/": dialing hub.kubevela.io:443 manual override has no HTTPS proxy: resolving host hub.kubevela.io: lookup hub.kubevela.io: no such host

Briefly describe what this pull request does. We love pull requests that resolve an open KubeVela issue. If yours does, you
can uncomment the below line to indicate which issue your PR fixes, for example
"Fixes #500":

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by StevenLeiZhang** [comment]
能否给下更多的信息？ 如何复现这个问题？你是在通过vela命令行工具安装插件吗？

**Comment by chivalryq** [comment]
You're using a wrong host. Just use dockerhub:
```shell
docker pull oamdev/cloudshell-operator:v0.3.0
```

**Comment by dockercore** [comment]
> You're using a wrong host. Just use dockerhub:你正在使用错误的主机。只需使用dockerhub：
> 
> ```shell
> docker pull oamdev/cloudshell-operator:v0.3.0
> ```

Thank you  
            The problem has been resolved ！！！
