### ISSUE TITLE
[Bug] KubeVela and EKS integration

### ISSUE THREAD

**Issue by mrzhengp** [kubevela/kubevela#6332]
There is an issue to have KubeVela to centrally manage clusters from Amazon EKS. 
Following the documentation to use vela CLI to join cluster that is hosted from Amazon EKS, running below command will generate errors:

vela cluster join devops-cluster-admin-config 
Error: invalid resource name "arn:aws:eks:ap-southeast-1:095972840660:cluster/hybrid-cluster": [may not contain '/']

**Comment by mrzhengp** [comment]
This is resolved. The default kubeconfig will not work. Instead a new service account needs to be created and binded with the cluster admin role, following below steps should resolve this issue:

kubectl create ns vela-system
kubectl create sa kubevela-vela-core -n vela-system
kubectl create clusterrolebinding default-sa-vela --clusterrole=cluster-admin --serviceaccount=vela-system:kubevela-vela-core
kubectl create token kubevela-vela-core -n vela-system | kubectl view-serviceaccount-kubeconfig > kubeconfig-sa2.yaml

Then use the kubeconfig-sa2.yaml as the kubeconfig for "vela cluster join"

**Comment by yanghengtai** [comment]
view-serviceaccount-kubeconfig 你好，我这里运行没有这个命令哟

**Comment by mrzhengp** [comment]
需要使用krew安装
https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin
