### ISSUE TITLE
can't create helm repository config when specify caFile

### ISSUE THREAD

**Issue by lixd** [kubevela/kubevela#6362]
**Describe the bug**

can't create helm repository config when specify caFile.
![image](https://github.com/kubevela/kubevela/assets/31980412/d16cd0ef-8a6e-49f2-af7b-7943a3d9ddb6)

**To Reproduce**

1.install kubevela
2.enable fluxcd
3.try to create helm repository by velacli
**Expected behavior**

**Screenshots**

**KubeVela Version**

```bash
[root@test ~]# vela version
CLI Version: 1.9.5
Core Version: 1.9.5
GitRevision: git-00ae0c94
GolangVersion: go1.19.11
```

**Cluster information**

**Additional context**

**Comment by FogDong** [comment]
Did you encode the caFile with base64?

**Comment by lixd** [comment]
> Did you encode the caFile with base64?

yes,maybe this is a type convert error,
template:
```cue
  type: "Opaque"
  stringData: {
   url: parameter.url
   if parameter.username != _|_ {
    username: parameter.username
   }
   if parameter.password != _|_ {
    password: parameter.password
   }

  }
  data: {
   if parameter.caFile != _|_ {
    caFile: parameter.caFile
   }
  }
```
and secret struct:
```go
type Secret struct {
    metav1.TypeMeta `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

    Data map[string][]byte `json:"data,omitempty" protobuf:"bytes,2,rep,name=data"`
    StringData map[string]string `json:"stringData,omitempty" protobuf:"bytes,4,rep,name=stringData"`
}
```
i think can't convert string to []byte,so create failed.


change template to this can fix it:
```cue
		type: "Opaque"
		stringData: {
			url: parameter.url
			if parameter.username != _|_ {
				username: parameter.username
			}
			if parameter.password != _|_ {
				password: parameter.password
			}
			if parameter.caFile != _|_ {
				caFile: parameter.caFile
			}
		}
```
I'm new to CUE,maybe there are another better resolv.

**Comment by FogDong** [comment]
Thanks for the deep investigation. I think the conversion of byte and string is the root cause.
Though if we change caFile to stringData, we no longer need the base64 encode.
Can you help to create a PR to fix this?

**Comment by lixd** [comment]
ok,i will fix it later

**Comment by lixd** [comment]
fixed in https://github.com/kubevela/catalog/pull/730 with fluxcd addon 2.3.8,uischema fixed in https://github.com/kubevela/catalog/pull/731  with fluxcd addon 2.3.9
