### ISSUE TITLE
dry-run seems to ignore the -n flag

### ISSUE THREAD

**Issue by Fifix** [kubevela/kubevela#6366]
**Describe the bug**
I want to be able to dry-run my vela application so I'm able to deliver a "pure K8S" manifest.
This app plays around two custom traits, which use the "context.namespace" namespace (so, no hardcoded namespace there)
I did manage to run it on both online and offline modes, and the manifest itself runs fine.

On the other hand, it seems the -n flag (to directly set a namespace in the manifest instead of using the default namespace) is ignored.

**To Reproduce**
vela dry-run --offline -n cis -d ../kubevela-conf/definitions/ -f ../kubevela-conf/first-hotstandby-app.yaml

**Expected behavior**
All fields pertaining to a namespace are set with "cis" instead of "default"

**KubeVela Version**
$ vela version
CLI Version: 1.8.2
Core Version: 1.8.2
GitRevision: git-360f69be
GolangVersion: go1.19.9

**Comment by FogDong** [comment]
I think it is fixed in `CLI Version: 1.9.6`, please upgrade the cli and try again.

**Comment by Fifix** [comment]
Uninstalled 1.8.2, downloaded 1.9.6 and installed it.
Running the same command yields the expected result : The -n flag is taken into account.

Thanks ! :D
