### ISSUE TITLE
Add KubeVela to awesome-go list

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#641]
https://github.com/avelino/awesome-go

**Comment by szihai** [comment]
https://github.com/avelino/awesome-go/pull/3377#pullrequestreview-545189999
Golint and Codecov not meeting requirement.

**Comment by wonderflow** [comment]
@szihai  Thanks ! @zzxwill @captainroy-hy  Let's try to fix them.

**Comment by captainroy-hy** [comment]
Got it.

**Comment by zzxwill** [comment]
Got it.

**Comment by zzxwill** [comment]
@wonderflow @captainroy-hy 
To fix [golint](https://goreportcard.com/report/github.com/oam-dev/kubevela#golint) issues:
I will take `gocyclo 96%` part and 1/3 of `golint 62%`. The second  1/3 is divided for @wonderflow and the last 1/3 is divided for @captainroy-hy. Is it okay for both of you?

To improve coverage, We also need to make a plan.

------------------------start @zzxwill 
Golint is a linter for Go source code.

kubevela/pkg/server/appHandlers.go
Line 11: warning: exported method APIServer.UpdateApps should have comment or be unexported (golint)
Line 14: warning: exported method APIServer.GetApp should have comment or be unexported (golint)
Line 32: warning: exported method APIServer.ListApps should have comment or be unexported (golint)
Line 50: warning: exported method APIServer.DeleteApps should have comment or be unexported (golint)
kubevela/pkg/oam/application.go
Line 23: warning: exported const DefaultChosenAllSvc should have comment (or a comment on this block) or be unexported (golint)
Line 30: warning: exported type ApplicationMetaList should have comment or be unexported (golint)
Line 52: warning: exported type Option should have comment or be unexported (golint)
Line 59: warning: exported type DeleteOptions should have comment or be unexported (golint)
Line 105: warning: exported function ListComponents should have comment or be unexported (golint)
Line 133: warning: exported function RetrieveApplicationStatusByName should have comment or be unexported (golint)
Line 167: warning: exported method DeleteOptions.DeleteApp should have comment or be unexported (golint)
Line 205: warning: exported method DeleteOptions.DeleteComponent should have comment or be unexported (golint)
kubevela/pkg/server/traitHandler.go
Line 22: warning: comment on exported method APIServer.AttachTrait should be of the form "AttachTrait ..." (golint)
Line 42: warning: exported method APIServer.GetTrait should have comment or be unexported (golint)
Line 55: warning: exported method APIServer.ListTrait should have comment or be unexported (golint)
Line 66: warning: exported method APIServer.DetachTrait should have comment or be unexported (golint)
Line 88: warning: exported method APIServer.DoAttachTrait should have comment or be unexported (golint)
Line 122: warning: exported method APIServer.DoDetachTrait should have comment or be unexported (golint)
kubevela/pkg/oam/trait_checker.go
Line 22: warning: exported type CheckStatus should have comment or be unexported (golint)
Line 25: warning: exported const StatusChecking should have comment (or a comment on this block) or be unexported (golint)
Line 29: warning: exported function GetChecker should have comment or be unexported (golint)
Line 42: warning: exported type Checker should have comment or be unexported (golint)
Line 46: warning: exported type DefaultChecker should have comment or be unexported (golint)
Line 50: warning: exported method DefaultChecker.Check should have comment or be unexported (golint)
Line 71: warning: exported type MetricChecker should have comment or be unexported (golint)
Line 75: warning: exported method MetricChecker.Check should have comment or be unexported (golint)
Line 96: warning: exported type RouteChecker should have comment or be unexported (golint)
Line 100: warning: exported method RouteChecker.Check should have comment or be unexported (golint)
Line 140: warning: exported type AutoscalerChecker should have comment or be unexported (golint)
Line 144: warning: exported method AutoscalerChecker.Check should have comment or be unexported (golint)
Line 177: warning: exported function GetUnstructured should have comment or be unexported (golint)
Line 186: warning: exported function GetStatusFromObject should have comment or be unexported (golint)
kubevela/pkg/controller/v1alpha1/autoscaler/keda.go
Line 102: warning: exported type CronTypeCondition should have comment or be unexported (golint)
Line 119: warning: exported function GetCronTypeCondition should have comment or be unexported (golint)
kubevela/pkg/controller/v1alpha1/autoscaler/types.go
Line 1: warning: package comment should be of the form "Package autoscalers ..." (golint)
Line 9: warning: exported const CronType should have comment (or a comment on this block) or be unexported (golint)
kubevela/pkg/application/app.go
Line 29: warning: exported type Application should have comment or be unexported (golint)
Line 41: warning: exported function LoadFromFile should have comment or be unexported (golint)
Line 62: warning: exported function Load should have comment or be unexported (golint)
Line 70: warning: exported function Delete should have comment or be unexported (golint)
Line 78: warning: exported function List should have comment or be unexported (golint)
Line 104: warning: exported function MatchAppByComp should have comment or be unexported (golint)
Line 119: warning: exported method Application.Save should have comment or be unexported (golint)
Line 136: warning: exported method Application.Validate should have comment or be unexported (golint)
Line 155: warning: exported method Application.GetComponents should have comment or be unexported (golint)
Line 164: warning: exported method Application.GetServiceConfig should have comment or be unexported (golint)
Line 172: warning: exported method Application.GetWorkload should have comment or be unexported (golint)
Line 187: warning: exported method Application.GetTraitNames should have comment or be unexported (golint)
Line 199: warning: exported method Application.GetTraits should have comment or be unexported (golint)
Line 215: warning: exported method Application.GetTraitsByType should have comment or be unexported (golint)
Line 227: warning: comment on exported method Application.OAM should be of the form "OAM ..." (golint)
Line 242: warning: exported function GetAppConfig should have comment or be unexported (golint)
kubevela/e2e/commonContext.go
Line 51: warning: exported var DeleteEnvFunc should have comment or be unexported (golint)
kubevela/pkg/server/scopeHandlers.go
Line 5: warning: comment on exported method APIServer.CreateScope should be of the form "CreateScope ..." (golint)
Line 9: warning: exported method APIServer.UpdateScope should have comment or be unexported (golint)
Line 12: warning: exported method APIServer.GetScope should have comment or be unexported (golint)
Line 15: warning: exported method APIServer.ListScope should have comment or be unexported (golint)
Line 18: warning: exported method APIServer.DeleteScope should have comment or be unexported (golint)
kubevela/pkg/appfile/service.go
Line 21: warning: exported type Service should have comment or be unexported (golint)
Line 23: warning: exported const DefaultWorkloadType should have comment or be unexported (golint)
Line 25: warning: exported method Service.GetType should have comment or be unexported (golint)
Line 33: warning: exported method Service.GetUserConfigName should have comment or be unexported (golint)
Line 41: warning: exported method Service.GetConfig should have comment or be unexported (golint)
Line 54: warning: exported method Service.GetBuild should have comment or be unexported (golint)
Line 140: warning: exported method AppFile.GetServices should have comment or be unexported (golint)
kubevela/pkg/commands/capability.go
Line 18: warning: exported function CapabilityCommandGroup should have comment or be unexported (golint)
Line 36: warning: exported function NewCenterCommand should have comment or be unexported (golint)
Line 51: warning: exported function NewCapCenterConfigCommand should have comment or be unexported (golint)
Line 76: warning: exported function NewCapInstallCommand should have comment or be unexported (golint)
Line 106: warning: exported function NewCapUninstallCommand should have comment or be unexported (golint)
Line 135: warning: exported function NewCapCenterSyncCommand should have comment or be unexported (golint)
Line 156: warning: exported function NewCapListCommand should have comment or be unexported (golint)
Line 184: warning: exported function NewCapCenterListCommand should have comment or be unexported (golint)
Line 197: warning: exported function NewCapCenterRemoveCommand should have comment or be unexported (golint)
Line 210: warning: exported function ListCapCenters should have comment or be unexported (golint)
Line 224: warning: exported function RemoveCapCenter should have comment or be unexported (golint)
kubevela/pkg/commands/show.go
Line 16: warning: exported function NewAppShowCommand should have comment or be unexported (golint)
kubevela/hack/frontend/source.go
Line 45: warning: exported function PrintToFile should have comment or be unexported (golint)
kubevela/pkg/controller/v1alpha1/podspecworkload/podspecworkload_controller.go
Line 68: warning: comment on exported method Reconciler.Reconcile should be of the form "Reconcile ..." (golint)
Line 269: warning: exported method Reconciler.SetupWithManager should have comment or be unexported (golint)
kubevela/pkg/controller/dependency/install.go
Line 80: warning: comment on exported function Uninstall should be of the form "Uninstall ..." (golint)

------------------------start @wonderflow 
kubevela/pkg/controller/dependency/promethus.go
Line 16: warning: exported function InstallPromethusInstance should have comment or be unexported (golint)
kubevela/pkg/oam/capability.go
Line 29: warning: exported function AddCapabilityCenter should have comment or be unexported (golint)
Line 56: warning: exported function SyncCapabilityFromCenter should have comment or be unexported (golint)
Line 64: warning: exported function AddCapabilityIntoCluster should have comment or be unexported (golint)
Line 78: warning: exported function InstallCapability should have comment or be unexported (golint)
Line 155: warning: exported function GetSyncedCapabilities should have comment or be unexported (golint)
Line 170: warning: exported function ListCapabilityCenters should have comment or be unexported (golint)
Line 185: warning: exported function SyncCapabilityCenter should have comment or be unexported (golint)
Line 220: warning: exported function RemoveCapabilityFromCluster should have comment or be unexported (golint)
Line 229: warning: exported function RemoveCapability should have comment or be unexported (golint)
Line 243: warning: exported function UninstallCap should have comment or be unexported (golint)
Line 280: warning: exported function ListCapabilities should have comment or be unexported (golint)
Line 306: warning: exported function ListCenterCapabilities should have comment or be unexported (golint)
Line 326: warning: exported function RemoveCapabilityCenter should have comment or be unexported (golint)
Line 359: warning: exported function GatherWorkloads should have comment or be unexported (golint)
Line 372: warning: exported function CheckInstallStatus should have comment or be unexported (golint)
kubevela/pkg/oam/workload.go
Line 20: warning: exported type RunOptions should have comment or be unexported (golint)
Line 30: warning: exported function LoadIfExist should have comment or be unexported (golint)
Line 46: warning: exported function BaseComplete should have comment or be unexported (golint)
Line 121: warning: exported function BaseRun should have comment or be unexported (golint)
kubevela/pkg/commands/status.go
Line 75: warning: exported const ErrNotLoadAppConfig should have comment (or a comment on this block) or be unexported (golint)
Line 105: warning: exported function NewAppStatusCommand should have comment or be unexported (golint)
kubevela/pkg/commands/trait.go
Line 32: warning: exported function AddTraitCommands should have comment or be unexported (golint)
kubevela/pkg/commands/traits.go
Line 15: warning: exported function NewTraitsCommand should have comment or be unexported (golint)
kubevela/pkg/server/util/middleware.go
Line 1: warning: package comment should be of the form "Package util ..." (golint)
Line 35: warning: exported type ContextKeyType should have comment or be unexported (golint)
Line 46: warning: comment on exported const RootPath should be of the form "RootPath ..." (golint)
Line 48: warning: exported const EnvironmentPath should have comment (or a comment on this block) or be unexported (golint)
Line 105: warning: comment on exported function GetContext should be of the form "GetContext ..." (golint)
kubevela/pkg/appfile/template/manager.go
Line 8: warning: exported type Manager should have comment or be unexported (golint)
Line 13: warning: exported function Load should have comment or be unexported (golint)
Line 28: warning: exported type Template should have comment or be unexported (golint)
kubevela/pkg/server/componentHandlers.go
Line 14: warning: exported method APIServer.GetComponent should have comment or be unexported (golint)
Line 33: warning: exported method APIServer.DeleteComponent should have comment or be unexported (golint)
kubevela/pkg/oam/component.go
Line 11: warning: exported function RetrieveComponent should have comment or be unexported (golint)
kubevela/pkg/commands/env.go
Line 18: warning: exported function NewEnvCommand should have comment or be unexported (golint)
Line 33: warning: exported function NewEnvListCommand should have comment or be unexported (golint)
Line 52: warning: exported function NewEnvInitCommand should have comment or be unexported (golint)
Line 86: warning: exported function NewEnvDeleteCommand should have comment or be unexported (golint)
Line 105: warning: exported function NewEnvSetCommand should have comment or be unexported (golint)
Line 124: warning: exported function ListEnvs should have comment or be unexported (golint)
Line 143: warning: exported function DeleteEnv should have comment or be unexported (golint)
Line 157: warning: exported function CreateOrUpdateEnv should have comment or be unexported (golint)
Line 171: warning: exported function SetEnv should have comment or be unexported (golint)
Line 184: warning: exported function GetEnv should have comment or be unexported (golint)
kubevela/pkg/commands/exec.go
Line 31: warning: exported type VelaExecOptions should have comment or be unexported (golint)
Line 47: warning: exported function NewExecCommand should have comment or be unexported (golint)
Line 99: warning: exported method VelaExecOptions.Init should have comment or be unexported (golint)
Line 129: warning: exported method VelaExecOptions.Complete should have comment or be unexported (golint)
Line 173: warning: exported method VelaExecOptions.Run should have comment or be unexported (golint)
kubevela/pkg/appfile/template/fake.go
Line 3: warning: exported type FakeTemplateManager should have comment or be unexported (golint)
Line 7: warning: exported function NewFakeTemplateManager should have comment or be unexported (golint)
kubevela/pkg/application/run.go
Line 16: warning: exported method Application.BuildRun should have comment or be unexported (golint)
Line 24: warning: exported method Application.Run should have comment or be unexported (golint)
Line 37: warning: exported function CreateOrUpdateComponent should have comment or be unexported (golint)
Line 50: warning: exported function CreateOrUpdateAppConfig should have comment or be unexported (golint)
Line 67: warning: exported function CreateScopes should have comment or be unexported (golint)
kubevela/pkg/appfile/appfile.go
Line 21: warning: exported var ErrImageNotDefined should have comment or be unexported (golint)
Line 24: warning: exported const DefaultAppfilePath should have comment or be unexported (golint)
Line 26: warning: exported type AppFile should have comment or be unexported (golint)
Line 36: warning: exported function NewAppFile should have comment or be unexported (golint)
Line 44: warning: exported function Load should have comment or be unexported (golint)
Line 48: warning: exported function LoadFromFile should have comment or be unexported (golint)
Line 155: warning: exported function FormatDefaultHealthScopeName should have comment or be unexported (golint)
kubevela/e2e/cli.go
Line 31: warning: exported function Exec should have comment or be unexported (golint)
Line 40: warning: exported function ExecAndTerminate should have comment or be unexported (golint)
Line 51: warning: exported function LongTimeExec should have comment or be unexported (golint)
Line 61: warning: exported function AsyncExec should have comment or be unexported (golint)
Line 69: warning: exported function InteractiveExec should have comment or be unexported (golint)
Line 97: warning: exported function BeforeSuit should have comment or be unexported (golint)
kubevela/api/api.go
Line 1: warning: package comment should be of the form "Package api ..." (golint)
kubevela/pkg/controller/utils/utils.go
Line 16: warning: exported const LabelPodSpecable should have comment or be unexported (golint)
Line 18: warning: exported function GetPodSpecPath should have comment or be unexported (golint)
Line 33: warning: exported function DiscoveryFromPodSpec should have comment or be unexported (golint)
kubevela/pkg/application/modify.go
Line 9: warning: exported method Application.SetWorkload should have comment or be unexported (golint)
Line 26: warning: exported method Application.SetTrait should have comment or be unexported (golint)
Line 52: warning: exported method Application.RemoveTrait should have comment or be unexported (golint)
Line 65: warning: exported method Application.RemoveComponent should have comment or be unexported (golint)
kubevela/pkg/commands/cli.go

------------------------start @captainroy-hy 
Line 23: warning: exported function NewCommand should have comment or be unexported (golint)
Line 109: warning: exported function PrintHelpByTag should have comment or be unexported (golint)
Line 121: warning: exported function NewVersionCommand should have comment or be unexported (golint)
kubevela/pkg/commands/completion.go
Line 40: warning: exported function NewCompletionCommand should have comment or be unexported (golint)
kubevela/pkg/commands/workloads.go
Line 14: warning: exported function NewWorkloadsCommand should have comment or be unexported (golint)
kubevela/pkg/controller/v1alpha1/autoscaler/autoscaler_controller.go
Line 64: warning: comment on exported method AutoscalerReconciler.Reconcile should be of the form "Reconcile ..." (golint)
Line 142: warning: exported method AutoscalerReconciler.SetupWithManager should have comment or be unexported (golint)
kubevela/pkg/commands/dashboard.go
Line 34: warning: exported function NewDashboardCommand should have comment or be unexported (golint)
Line 71: warning: exported type Options should have comment or be unexported (golint)
Line 81: warning: exported method Options.GetStaticPath should have comment or be unexported (golint)
Line 132: warning: exported function SetupAPIServer should have comment or be unexported (golint)
Line 191: warning: comment on exported function OpenBrowser should be of the form "OpenBrowser ..." (golint)
Line 208: warning: exported function CheckVelaRuntimeInstalledAndReady should have comment or be unexported (golint)
kubevela/pkg/commands/ls.go
Line 21: warning: exported function NewListCommand should have comment or be unexported (golint)
Line 131: warning: exported function GetCompMeta should have comment or be unexported (golint)
kubevela/pkg/controller/common/error.go
Line 1: warning: package comment should be of the form "Package common ..." (golint)
Line 5: warning: exported const ErrLocatingWorkload should have comment (or a comment on this block) or be unexported (golint)
kubevela/hack/chart/generate.go
Line 26: warning: exported function PrintToFile should have comment or be unexported (golint)
kubevela/pkg/server/workloadHandler.go
Line 1: warning: package comment should be of the form "Package server ..." (golint)
Line 19: warning: comment on exported method APIServer.CreateWorkload should be of the form "CreateWorkload ..." (golint)
Line 64: warning: exported method APIServer.UpdateWorkload should have comment or be unexported (golint)
Line 67: warning: exported method APIServer.GetWorkload should have comment or be unexported (golint)
Line 79: warning: exported method APIServer.ListWorkload should have comment or be unexported (golint)
kubevela/pkg/commands/system.go
Line 26: warning: exported type VelaRuntimeStatus should have comment or be unexported (golint)
Line 29: warning: exported const NotFound should have comment (or a comment on this block) or be unexported (golint)
Line 55: warning: exported function SystemCommandGroup should have comment or be unexported (golint)
Line 68: warning: exported function NewAdminInfoCommand should have comment or be unexported (golint)
Line 97: warning: exported function NewInstallCommand should have comment or be unexported (golint)
Line 177: warning: comment on exported function CheckCapabilityReady should be of the form "CheckCapabilityReady ..." (golint)
Line 223: warning: exported function InstallOamRuntime should have comment or be unexported (golint)
Line 254: warning: exported function GetOAMReleaseVersion should have comment or be unexported (golint)
Line 268: warning: exported function PrintTrackVelaRuntimeStatus should have comment or be unexported (golint)
kubevela/hack/utils/common.go
Line 8: warning: comment on exported function FprintZipData should be of the form "FprintZipData ..." (golint)
kubevela/pkg/commands/template.go
Line 11: warning: exported function NewTemplateCommand should have comment or be unexported (golint)
Line 26: warning: exported function NewTemplateContextCommand should have comment or be unexported (golint)
kubevela/pkg/commands/up.go
Line 34: warning: exported function NewUpCommand should have comment or be unexported (golint)
Line 71: warning: exported type AppfileOptions should have comment or be unexported (golint)
Line 93: warning: exported method AppfileOptions.Run should have comment or be unexported (golint)
Line 180: warning: comment on exported method AppfileOptions.ApplyAppConfig should be of the form "ApplyAppConfig ..." (golint)
Line 221: warning: exported method AppfileOptions.Info should have comment or be unexported (golint)
kubevela/pkg/commands/comp.go
Line 18: warning: exported const Staging should have comment (or a comment on this block) or be unexported (golint)
Line 31: warning: exported function AddCompCommands should have comment or be unexported (golint)
Line 46: warning: exported function NewCompDeployCommands should have comment or be unexported (golint)
Line 90: warning: exported function GetWorkloadNameFromArgs should have comment or be unexported (golint)
kubevela/pkg/commands/init.go
Line 281: warning: exported function GetCapabilityByName should have comment or be unexported (golint)
kubevela/pkg/server/capabilityHandlers.go
Line 11: warning: exported method APIServer.AddCapabilityCenter should have comment or be unexported (golint)
Line 24: warning: exported method APIServer.ListCapabilityCenters should have comment or be unexported (golint)
Line 33: warning: exported method APIServer.SyncCapabilityCenter should have comment or be unexported (golint)
Line 42: warning: exported method APIServer.AddCapabilityIntoCluster should have comment or be unexported (golint)
Line 52: warning: exported method APIServer.DeleteCapabilityCenter should have comment or be unexported (golint)
Line 58: warning: exported method APIServer.RemoveCapabilityFromCluster should have comment or be unexported (golint)
Line 68: warning: exported method APIServer.ListCapabilities should have comment or be unexported (golint)
kubevela/pkg/server/envHandlers.go
Line 13: warning: comment on exported method APIServer.CreateEnv should be of the form "CreateEnv ..." (golint)
Line 38: warning: exported method APIServer.UpdateEnv should have comment or be unexported (golint)
Line 51: warning: exported method APIServer.GetEnv should have comment or be unexported (golint)
Line 67: warning: exported method APIServer.ListEnv should have comment or be unexported (golint)
Line 71: warning: exported method APIServer.DeleteEnv should have comment or be unexported (golint)
Line 78: warning: exported method APIServer.SetEnv should have comment or be unexported (golint)
kubevela/pkg/commands/config.go
Line 23: warning: exported function NewConfigCommand should have comment or be unexported (golint)
Line 43: warning: exported function NewConfigListCommand should have comment or be unexported (golint)
Line 68: warning: exported function ListConfigs should have comment or be unexported (golint)
Line 101: warning: exported function NewConfigGetCommand should have comment or be unexported (golint)
Line 145: warning: exported function NewConfigSetCommand should have comment or be unexported (golint)
Line 218: warning: exported function NewConfigDeleteCommand should have comment or be unexported (golint)
kubevela/pkg/commands/portforward.go
Line 34: warning: exported type VelaPortForwardOptions should have comment or be unexported (golint)
Line 51: warning: exported function NewPortForwardCommand should have comment or be unexported (golint)
Line 97: warning: exported method VelaPortForwardOptions.Init should have comment or be unexported (golint)
Line 128: warning: exported function GetRouteServiceName should have comment or be unexported (golint)
Line 143: warning: exported method VelaPortForwardOptions.Complete should have comment or be unexported (golint)
Line 237: warning: exported method VelaPortForwardOptions.Run should have comment or be unexported (golint)
kubevela/pkg/commands/refresh.go
Line 24: warning: exported function RefreshDefinitions should have comment or be unexported (golint)
kubevela/pkg/server/util/api.go
Line 1: warning: package comment should be of the form "Package util ..." (golint)
Line 13: warning: exported var DefaultDashboardPort should have comment or be unexported (golint)
Line 15: warning: exported const DefaultAPIServerPort should have comment or be unexported (golint)
Line 17: warning: exported function AssembleResponse should have comment or be unexported (golint)
Line 34: warning: exported function URL should have comment or be unexported (golint)
kubevela/pkg/server/miscHandlers.go
Line 12: warning: exported method APIServer.GetVersion should have comment or be unexported (golint)
kubevela/pkg/oam/trait.go
Line 20: warning: exported function ListTraitDefinitions should have comment or be unexported (golint)
Line 34: warning: exported function GetTraitDefinition should have comment or be unexported (golint)
Line 68: warning: exported function ConvertApplyTo should have comment or be unexported (golint)
Line 91: warning: exported function In should have comment or be unexported (golint)
Line 100: warning: exported function Parse should have comment or be unexported (golint)
Line 113: warning: exported function SimplifyCapabilityStruct should have comment or be unexported (golint)
Line 125: warning: exported function ValidateAndMutateForCore should have comment or be unexported (golint)
Line 202: warning: exported function TraitOperationRun should have comment or be unexported (golint)
Line 214: warning: exported function PrepareDetachTrait should have comment or be unexported (golint)
kubevela/pkg/appfile/build.go
Line 11: warning: exported type Build should have comment or be unexported (golint)
Line 16: warning: exported type Docker should have comment or be unexported (golint)
Line 21: warning: exported type Push should have comment or be unexported (golint)
Line 47: warning: exported method Build.BuildImage should have comment or be unexported (golint)
kubevela/pkg/plugins/cluster.go
Line 26: warning: comment on exported const DescriptionUndefined should be of the form "DescriptionUndefined ..." (golint)
kubevela/pkg/commands/logs.go
Line 24: warning: exported function NewLogsCommand should have comment or be unexported (golint)
Line 58: warning: exported type Args should have comment or be unexported (golint)

**Comment by captainroy-hy** [comment]
@wonderflow @zzxwill As for Golint coverage, the report was generated based on the codes two weeks ago. And I have fixed most lint issues recently. And after refreshing the report, [Golint coverage ](https://goreportcard.com/report/github.com/oam-dev/kubevela#golint)has already reached 94%.

**Comment by Hanmengnan** [comment]
@wonderflow I have submitted a new PR to add KubeVela to the awesome-go list: https://github.com/avelino/awesome-go/pull/4776
