### ISSUE TITLE
vela show --web warnings

### ISSUE THREAD

**Issue by rakeshreddyrg09** [kubevela/kubevela#6411]
**Describe the bug**

Running vela show --web is triggering warnings.

Steps to Reproduce

1. CLI Version: 1.7.3

   - Core Version:
      - Git Revision: git-f49f11dd
      - Golang Version: go1.19.5
- Kubernetes Version: v1.26
- Vela Core Version: v1.9.4
- Execute vela show --web
-   ![image](https://github.com/kubevela/kubevela/assets/48629246/0ab59110-cfa7-4652-8102-da66b2527f3a)

can you team help me how to resolve these.!
thank you.

**Comment by rakeshreddyrg09** [comment]
![image](https://github.com/kubevela/kubevela/assets/48629246/c919cebe-432c-4d5f-9fd1-c9a73812e9d9)
even the same issue coming in default helm chart 
please refer above image

**Comment by sathyanarays** [comment]
@rakeshreddyrg09 , could you provide steps to reproduce this issue?

If you could create a new cluster, install kubevela and run the `vela show --web`, do we still get the error?

**Comment by rakeshreddyrg09** [comment]
this is working now with this CLI Version: 1.9.9 version
thank you.
