### ISSUE TITLE
Fix documentation where schematic for component definition refers to kube

### ISSUE THREAD

**Issue by anoop2811** [kubevela/kubevela#6436]
Refer to this slack conversation: https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1704394842494259

The kube scematic was deprecated in this commit: https://github.com/kubevela/kubevela/commit/f1bae16723a819d0efea43b6b18e2d7cedb1ec90

However we still have documentation like [here](https://kubevela.io/docs/platform-engineers/kube/component/) where it refers to kube schematic. We should update this to using cue.

**Comment by professorabhay** [comment]
Hey, @anoop2811 ! I would like to give it a try. 
Is there anything else related to this that can help?

**Comment by anoop2811** [comment]
Hey @professorabhay ! Welcome to the community. One way you could do is search in the code under the docs directory for  "kube:" and look for occurrences under schematic, convert them to using cue and test the same locally. You can refer to an example here: https://kubevela.io/docs/platform-engineers/oam/x-definition/#specpoddisruptive. Let us know if you need any further help.

**Comment by professorabhay** [comment]
Ok @anoop2811, I got it almost. Just one question - 
I found `kube` in `docs/` at two places.

1 - `docs/examples/workflow/Li-Auto-Inc/common-definitions.yaml`

2 -  `docs/examples/kube-module/kube-worker-cd.yaml`

In both files `kube` is written under the `schematic:` and I have to change it to `cue`. Am I right?

![image](https://github.com/kubevela/kubevela/assets/76243309/4d7744c8-9066-4b3b-929e-f92d2fef2cca)

*both are same

**Comment by kartikaysaxena** [comment]
Hi @anoop2811 I have opened a PR, can you please take a look at it? Thanks
