### ISSUE TITLE
[Bug]Vela uses zstd compression function causing OOM

### ISSUE THREAD

**Issue by msun1996** [kubevela/kubevela#6462]
**Describe the bug**
2C2G specification vela-core service, after releasing applications containing large content configmaps multiple times, you will find that the vela-core memory usage will increase step by step, and under certain circumstances it will fluctuate to 2G, causing the program to restart after OOM.

**To Reproduce**
The k8s container deploys the vela-core service with the default parameters and publishes application CRs with content larger than 128KB multiple times. Observing pprof, you can find that the memory occupied by the ensureHist method continues to grow until the memory grows to the number of CPU cores of the node where the vela-core container is located multiplied by 16M.

**Expected behavior**
The zstd function used by vela-core takes up reasonable memory

**Screenshots**
pprof:
![image](https://github.com/kubevela/kubevela/assets/27460507/81f0ffef-4015-4ef2-a5ce-af9c511f0c56)

**KubeVela Version**
1.9.2
**Cluster information**
1.19
**Additional context**

**Troubleshooting reasons:**
The default parameters of zstd client are as follows. Use the GOMAXPROCS method to obtain the number of CPU cores and create an encoder with the same number of cores. The block size is 128KB and the window size is 8M. When compressing content larger than 128KB, each encoder will create a 2*8M map cache block.
![image](https://github.com/kubevela/kubevela/assets/27460507/5ddc9719-382a-4ecd-bb76-da6157a1b81d)
![image](https://github.com/kubevela/kubevela/assets/27460507/99edadff-9571-4ad1-a503-9938f8e9a6b9)

When k8s container GOMAXPROCS obtains the CPU core number, the core number of the node where the container is located will be incorrectly obtained.

**Solution:**
main()   **import _ "go.uber.org/automaxprocs"**    sorted at the top。

**Comment by StevenLeiZhang** [comment]
I think we need expose the count of encoder to Helm values, allow users set it. If user dose not set it ,  the default value is cpu count.

**Comment by dhiguero** [comment]
Thanks for the detailed report, we need to investigate potential fixes.

**Comment by charlie0129** [comment]
Thanks for the report and solution. Yes, I think simply importing `_ "go.uber.org/automaxprocs"` should fix this problem. The concurrent encoders will be set correctly according to CPU quota instead of the CPU count on the node. As a bonus, performance should increase a bit because of reduced context switching.

**Comment by wonderflow** [comment]
https://github.com/kubevela/pkg/releases/tag/v1.9.0 I've released the new version with bugfix PR merged. Can someone help upgrade the pkg version for kubevela?
