### ISSUE TITLE
kubevela.io domain is down?

### ISSUE THREAD

**Issue by alex-dovnar-astrix** [kubevela/kubevela#6525]
**Describe the bug**
[kubevela.io is not resolvable from any DNS](https://dnschecker.org/#A/kubevela.io)

**To Reproduce**
1. Try to open the site - DNS issue
2. Dig kubevela.io - DNS issue

**Expected behavior**

**Comment by Hanmengnan** [comment]
+1, BTW, you can try to access [https://kubevela.net/](https://kubevela.net/)
