### ISSUE TITLE
Cannot install new version of vela with kubevela.net

### ISSUE THREAD

**Issue by jmarchel7bulls** [kubevela/kubevela#6526]
When attempting to install KubeVela version 1.9.11 on a Kubernetes cluster running using the vela CLI tool, the installation process fails due to an issue with retrieving and loading the Helm chart. The specific error encountered indicates a problem with the Helm chart file's gzip header.

**To Reproduce**
Pull kubevela:
curl -fsSl https://kubevela.net/script/install.sh | bash'
Run the following command to install KubeVela:
sh
vela install --version 1.9.11

**KubeVela Version**
v1.9.11

**Cluster information**
1.24.0

**Additional context**
Installing KubeVela Core ...
Error: loadding the helm chart of kubeVela control plane failure, error retrieving Helm Chart at https://charts.kubevela.net/core/vela-core-1.9.11.tgz: gzip: invalid header

**Comment by FogDong** [comment]
Can you help this? @barnettZQG

**Comment by kishorkn** [comment]
Kubevela.io is up now. Try again and see if it works

**Comment by ealogar** [comment]
Working for me

**Comment by FogDong** [comment]
Recovered.
