### ISSUE TITLE
Unexpectedly Leaving GOMAXPROCS=128: CPU quota undefined

### ISSUE THREAD

**Issue by aiyijing** [kubevela/kubevela#6535]
Hi there！
I use the vela command on our experimental physics machine, regardless of which subCommand I use. There will be the following alarms, which can be uncomfortable to use
```shell
$ vela version
maxprocs.go:47: maxprocs: Leaving GOMAXPROCS=128: CPU quota undefined
CLI Version: 1.9.11
Core Version: 0.1.0
GitRevision: git-89177805
GolangVersion: go1.19.13
```
I think it's related to my physical machine configuration. My machine configuration is as follows:
```shell
$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
....
```
Is there any way to solve it?

**Comment by bugbounce** [comment]
Will be fixed by this . https://github.com/kubevela/kubevela/pull/6530

**Comment by aiyijing** [comment]
thx
