### ISSUE TITLE
Roadmap for Updating controller-runtime Dependency to Support cluster-gateway v1.9.0 and Dynamic Cluster Token Feature?

### ISSUE THREAD

**Issue by bugbuilder** [kubevela/kubevela#6649]
Hi there!

I was wondering if there’s any plan on the roadmap to update [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0), ideally to at least version 0.15.0? Currently, without this update, it’s a bit challenging to upgrade [github.com/oam-dev/cluster-gateway](https://github.com/oam-dev/cluster-gateway) to v1.9.0, which in turn blocks access to the new dynamic cluster token feature. This functionality would be really helpful for us, so I wanted to check if there’s an anticipated timeline or any possible workarounds for using this feature with the current setup.

Thanks a lot for any guidance or updates you can provide! 😊

**Comment by FogDong** [comment]
We're trying to update controller-runtime and kubernetes version, start with pkg: https://github.com/kubevela/pkg/pull/109
